### ISSUE TITLE
BIDS + branched analysis error

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#165]
Has anyone run a BIDS + branched analysis recently? I'm having problems with a very basic tasklist:

> 	
			<module><name>aamod_structuralfromnifti</name></module>
			<module><name>aamod_reorienttomiddle_structural</name></module>
			<module><name>aamod_epifromnifti</name></module>
			<module><name>aamod_reorienttomiddle_epi</name></module>		
			<module><name>aamod_realign</name></module>  
			<module><name>aamod_coreg_noss</name></module>
			<module><name>aamod_segment8_multichan</name>	</module>	
			<module><name>aamod_norm_write</name></module>
			<module><name>aamod_smooth</name></module>

  			<module>
				
			<branch>
                  		<selected_sessions>Flanker_run-1</selected_sessions>
				<module><name>aamod_firstlevel_model</name></module>
			</branch>
						
			<branch>
                   		<selected_sessions>Flanker_run-2</selected_sessions>
  				<module><name>aamod_firstlevel_model</name></module>
			</branch>

			</module>

This gives me a strange warning on start-up:

> WARNING: Renaming output epi of aamod_firstlevel_model_00001 to .
  It might breake dependency for the consecuting module(s).
  Make sure that you know what you are doing!

If I let the analysis proceed, SPM crashes with an out-of-memory error.

My userscript is just some basic setup and a call to aas_processBIDS. I'm not doing any stream renaming. aa says Flanker_run-1 and Flanker_run-2 are valid session names (and I still get the error even if I remove the _selected_sessions_ statements, so that doesn't seem to be the problem).

Here's a screen grab of my BIDS directory:

![ds000102_directory_tree](https://user-images.githubusercontent.com/25826038/44935168-40647f00-ad35-11e8-9099-44354eccd40c.jpg)

Maybe branched analysis got broken recently? Or am I doing something wrong? 

Regards,
Mike

**Comment by jones-michael-s** [comment]
Hi Johan,

Sorry for the delayed reply (yesterday was a holiday here).

I've looked into the code and I now understand what's going on a little better. 

There's good news and bad news.

The stream renaming is happening during "check requirements"  in aamod_firstlevel_model. Apparently epi only exists as an output stream to save residuals, and if the option isn't set to save them then the module deletes the stream (I would suggest we add a more informative warning message, but that is a separate issue). So that is not the problem.

The out-of-memory error I got was a red herring. After exiting/restarting aa, I now get the analysis to complete normally. (I was doing lots of testing and perhaps somehow got aa/spm into a weird state).

The bad news is I have now gone back to testing selected sessions and there is a problem.

This tasklist works fine:

> 
    <branch>
        <selected_sessions>Flanker_run-1</selected_sessions>
        <module><name>aamod_firstlevel_model</name></module>
    </branch>

    <branch>
        <selected_sessions>Flanker_run-1</selected_sessions>
        <module><name>aamod_firstlevel_model</name></module>
    </branch>

This tasklist works fine:

> 
    <branch>
        <selected_sessions>Flanker_run-2</selected_sessions>
        <module><name>aamod_firstlevel_model</name></module>
    </branch>

    <branch>
        <selected_sessions>Flanker_run-2</selected_sessions>
        <module><name>aamod_firstlevel_model</name></module>
    </branch>

This tasklist crashes:

> 
    <branch>
        <selected_sessions>Flanker_run-1</selected_sessions>
        <module><name>aamod_firstlevel_model</name></module>
    </branch>

    <branch>
        <selected_sessions>Flanker_run-2</selected_sessions>
        <module><name>aamod_firstlevel_model</name></module>
    </branch>

Here is the error:

load stream from file /Users/amber/DATA/RESULTS_ds000102/aamod_firstlevel_model_00002/sub-01/Flanker_run-2/stream_epi_outputfrom_aamod_firstlevel_model_00002.txt, but not
found

The second aamod_firstlevel_module (i.e., aamod_firstlevel_module_00002) is trying to load the files for session Flanker_run-2 but can't find them. Why not? _Because aa is copying over the wrong session files._ Here's a screen grab:

![flanker_run_1_run_2](https://user-images.githubusercontent.com/25826038/45056020-4620d400-b057-11e8-9019-4761df849aa2.jpg)

(The folder Flanker_run-1 should be Flanker_run-2.)

I'm describing this in excruciating detail rather than just trying to fix it because this looks like a bug down in the aa engine. Maybe someone familiar with the scheduler code could look into this? I'm loathe to start hacking stuff like aa_doprocessing_onetask.

Thoughts?
Mike

**Comment by tiborauer** [comment]
I agree with @jooh, that it is hard to say anything without seeing the code and the data.

**Comment by jones-michael-s** [comment]
Update: Okay, so this looks like it is indeed a separate bug and not related to 166 or 167.

Specifically it appears to be a cache issue. This is not a code area I know much about. All I know that disabling the cache fixes the bug. That is, I've changed aas_cache_put.m to this as a workaround:

>  % function [hit]=aas_cache_put(aap,name,value,varargin)
% global aacache
% 
% try
%     key=aas_cache_getkey(aap,varargin{:});
%     aacache.(name).(key)=value;
%     hit=true;
% catch errcode
%     hit=false;
% end;
%
function [hit]=aas_cache_put(aap,name,value,varargin)
hit=false;

I'm not proposing this as a serious fix;  I'm hoping someone familiar with aa internals might grab the ball here.

Here's a user script that will trigger the problem:


% ---------------------------------------------------------------------------------
aa_ver5;
aap = aarecipe(YOUR_PARAMETERFILE_HERE, 'ds000102_ss_bug.xml'); 
aap.acq_details.root =  SET ROOT HERE
aap.directory_conventions.analysisid = SET ANALYSISID HERE
aap.directory_conventions.rawdatadir = SET RAWDATADIR HERE

aap.options.autoidentifystructural_choosefirst = 1;
aap.options.autoidentifystructural_chooselast = 0;
aap.options.NIFTI4D = 1;

aap = aas_processBIDS(aap);
				   
aa_doprocessing(aap);
aa_close(aap);
% ---------------------------------------------------------------------------------

Here's the associated tasklist ds000102_ss_bug.xml

> <aap>
    <tasklist>
        <initialisation>
			
			<module><name>aamod_study_init</name></module>

        </initialisation>
		
        <main>
			
			<module><name>aamod_structuralfromnifti</name></module>
			<module><name>aamod_reorienttomiddle_structural</name></module>f
			<module><name>aamod_epifromnifti</name></module>
			<module><name>aamod_reorienttomiddle_epi</name></module>
			
			<module><name>aamod_realign</name></module>  
			<module><name>aamod_coreg_noss</name></module>	
			<module><name>aamod_segment8_multichan</name>
				<extraparameters>
					<aap><tasklist><currenttask><settings>
						<samp>5</samp>
					</settings></currenttask></tasklist></aap>
				</extraparameters>
			</module>
			<module><name>aamod_norm_write</name></module>
			<module><name>aamod_smooth</name></module>
					
			<module>
				
				<branch>
					<selected_sessions>Flanker_run-1</selected_sessions>
					<module><name>aamod_firstlevel_model</name></module>
				</branch>
				
				<branch>
					<selected_sessions>Flanker_run-2</selected_sessions>
 					<module><name>aamod_firstlevel_model</name></module>
				</branch>	
								
			</module>
	
        </main>
    </tasklist>
</aap>


(I set samp to 5 just to get segmentation to complete faster)

Run this twice. The first run will complete normally. Then delete aamod_firstlevel_00001 and aamod_firstlevel_00002 and re-run. The new run of aamod_firstlevel_00002 will crash because the wrong files get copied (see screengrab in previous post).

Data is from ds000102 from openfMRI. I removed all but the first subject to get to the crash faster.

Cheers,
Mike

**Comment by jones-michael-s** [comment]
Hello all,

So I now understand the problem and have implemented a tentative fix.

The problem:  aas_getdependencies_bydomain saves the correct session information to the cache (i.e., including selected_sessions, if any), however it doesn't use the selected sessions info when creating the hash. As such, any subsequent read of the cache just pulls out whatever got put in first because the hash key isn't unique.

The solution: extract selected sessions from aap.acq_details.selected_sessions and include it in the hash.

I've been testing this for the last day or so and it fixes all my problems. I'll continue to test it locally before putting in a PR. However, before mucking up the repo, I would first ask: Does anyone ("anyone" == the person who wrote aas_getdependencies_bydomain ) see anything this is going to break? 

Mike

PS: Using _analysisid_suffix_ in the tasklist doesn't fix this.

**Comment by jones-michael-s** [comment]
Here's code snippets to better evaluate my fix:

> function [deps commonind desc]=aas_getdependencies_bydomain(aap, sourcedomain, targetdomain, indices, whattoreturn, modulenum)
>
>if ~exist('modulenum','var')
>       modulenum=[];
>end;
>if ~exist('whattoreturn','var')
>       whattoreturn='possiblestreamlocations';
>end;
>
>selected_sessions = aap.acq_details.selected_sessions; % THIS IS NEW
>
>%  [hit resp]=aas_cache_get(aap,mfilename,sourcedomain,targetdomain,indices,whattoreturn,modulenum); % THIS IS THE OLD CALL
>
>[hit resp]=aas_cache_get(aap,mfilename,sourcedomain,targetdomain,selected_sessions,indices,whattoreturn,modulenum); % THIS IS THE NEW CALL
>

 A corresponding change is made to aas_cache_put near the end of file:

> %   aas_cache_put(aap,mfilename,{deps commonind},sourcedomain,targetdomain,indices,whattoreturn,modulenum); % THIS IS THE OLD CALL
>
>    aas_cache_put(aap,mfilename,{deps commonind},sourcedomain,targetdomain,selected_sessions,indices,whattoreturn, modulenum); % THIS IS THE NEW CALL
>	

Both aas_cache_get and aas_cache_put will varargs the last few parameters passed in and use all of them to create a hash key (or whatever the correct term is). I just added "selected_sessions" to the call.

**Comment by tiborauer** [comment]
👍

**Comment by jpeelle** [comment]
We agreed that @jones-michael-s is going to make a pull request to implement these changes.

**Comment by jones-michael-s** [comment]
Addendum: Did a PR for the fix.

Will close the issue when the PR is accepted.
