### ISSUE TITLE
Unable to run aa demo file on v5.4

### ISSUE THREAD

**Issue by kxchia** [automaticanalysis/automaticanalysis#175]
Hi,

I've recently installed v5.4 and was unable to run the demo file. There is no tasklist file (fmri_noslicetiming_withmodel_firstlevelonly.xml). Would it be possible to upload the tasklist file or use an alternative? Kindly advise, thank you!

Please see the error message below:
Cannot find file aap_tasklist_fmri_noslicetiming_withmodel_firstlevelonly.xml as specified in call to aarecipe
for help, see the aa wiki
Error using aas_log (line 65)
aa error:
see above (or set aap.options.verbose

Error in aarecipe (line 93)
        aas_log(aap,true,sprintf('Cannot find file %s as specified in call to aarecipe',tasklistxml));

Error in aa_user_demo_v1 (line 9)
aap = aarecipe('aap_tasklist_fmri_noslicetiming_withmodel_firstlevelonly.xml');

**Comment by tiborauer** [comment]
It seems that you have tried the release rather then the latest version (of the master branch).
