### ISSUE TITLE
aas_convertseries_fromstream bug

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#178]
Hello all,

We've run into a dicom header extraction bug in aas_convertseries_fromstream. I've isolated the glitch, but it's tricky for me to fix because: 1) I don't know much about Dicom headers, 2) the function has custom code for different scanner types and I can't test data from scanners we don't have.

Instead, I will describe the problem and perhaps it will be obvious to someone familiar with the code what should be done.

In short: If there's not enough available memory to process all the volumes in one pass (see line 215) breaking up the files into multiple passes results in an "index exceeds array size" error during the sorting at line 284. (The code works fine if you have enough memory to process all the volumes in one pass, which might be why this bug doesn't happen on your ginormous Linux boxes but does on our puny macs :-)

The cause of this is before the break on line 217, the last entry in DICOMHEADERS gets truncated (line 216). Now DICOMHEADERS and firstsliceInd differ in length by 1, leading to the index exceeds array size crash on line 284.

I don't understand: Why is the last entry in DICOMHEADERS truncated on line 216? Is this a typo? It sure seems like it on our data, but -- as mentioned above -- perhaps this is necessary/correct for data from other scanners.

Anyone have any thoughts?

Mike

PS: Also, I believe there is a non-fatal bug here as well. The sorting at line 284 processes a _chunksize_volumes_ subset of the data. I believe this is wrong. You need to do ONE sort over ALL the volumes. Multiple sorts over subsets is not the same thing. Again, this is something you will not notice if your memory does not require the function to process the dicoms in multiple passes.

**Comment by tiborauer** [comment]
I have also noticed this issue some time ago and fixed (?) it in [this commit](https://github.com/automaticanalysis/automaticanalysis/pull/173/commits/ccecef0efcb989f32a8e8f81c2593813fdacff5d), which is part of the the current active PR (#173).

**Comment by tiborauer** [comment]
I think you are right!
The whole lot of lines 284 -290 should be moved after the while loop, right before line 292. I have access to both Philips and GE data apart from Siemens, so I can test it. I am still at the HBP CodeJam in Palermo, but will test it once back in the UK.

**Comment by jones-michael-s** [comment]
I'm afraid we've run into another problem with this code.

We've started working with dicoms from a new (to us) Philips scanner. The dicoms it generates are one file per volume (not one file per slice) which is causing many crashes in aas_convertseries_fromstream and elsewhere. Also, TR is defined in a different field in the header (Private_2005_1030) and TE isn't defined at all (as far as I can tell).

If I click though SPM dicom import, the conversion looks okay. But I can't get conversion to work using aa.

Is this something you have encountered? I'm hoping there might be an aap settting to work around this but I don't see anything obvious.

**Comment by jones-michael-s** [comment]
Opened a PR on this.

**Comment by jones-michael-s** [comment]
PR has been merged
