### ISSUE TITLE
Incorrect documentation in aamod_compSignal

### ISSUE THREAD

**Issue by jooh** [automaticanalysis/automaticanalysis#179]
Yes, same module again! From reading the code, compSignal outputs signal for grey matter, white matter, CSF, and possibly out-of-brain if the BET stream is present:

```
compTC(e,1) = mean(Y(mGM>0));
compTC(e,2) = mean(Y(mWM>0));
compTC(e,3) = mean(Y(mCSF>0));
if hasBET, compTC(e,4) = mean(Y(mOOH>0)); end
```

But the documentation describes the outputs as being organised rather differently:

```
% COMP_SIGNAL creates regressors with mean signal intensity values for each
% segmented compartment [WhiteMatter (WM), CerebralSpinalFluid (CSF) and
% Out-of-Brain (OOB)] separately for each image. The resulting three
% regressors are saved in a mat file (structure: [WM CSF OOB]).
```

The documentation should be updated to reflect what the module actually outputs.

**Comment by tiborauer** [comment]
Closed by [commit 999984d](https://github.com/automaticanalysis/automaticanalysis/commit/999984d211dfdf5aa2ce1c265653c071425b8cd4)
