### ISSUE TITLE
Difficulties with aa_downloaddemo.m

### ISSUE THREAD

**Issue by jpeelle** [automaticanalysis/automaticanalysis#183]
I'm having trouble understanding the logic in aa_downloaddemo.m. On line 24 and following it checks to see whether DEMODIRBASENAME (which is 'aa_demo') is in aap_directory_conventions.rawdatadir, and if not, generates an error:

```
sources = strsplit(aap.directory_conventions.rawdatadir,':')';
demoind = cell_index(sources, DEMODIRBASENAME);
assert(~any(demoind==0), ...
    ['did not find ''' DEMODIRBASENAME ''' directory in aap.directory_conventions.rawdatadir'])
```

so if I do something like this:

```
aap.directory_conventions.rawdatadir = '~/data';
```

I get an error. If I then do 

```
aap.directory_conventions.rawdatadir = '~/data/aa_demo';
```

then the data downloads...BUT the script creates an 'aa_demo' folder as a subfolder of the rawdatadir, on line 33:

```
if ~exist('rawdir','var') || ~exist(fullfile(demodir,rawdir),'dir') % we need to download
    aas_makedir(aap,demodir);
```

the result is my data are in ~/data/aa_demo/aa_demo and the rest of the aa_user_demo script fails to run.

I may be missing something obvious about the logic here. What's the reason that 'aa_demo' is required to be in aap.directory_conventions.rawdatadir?

**Comment by tiborauer** [comment]
The reason for aa_demo to allow automatic download into a central storage place shared within lab; so demo data is downloaded only once.

It is intentional (even if a little confusing) to have aa_demo/aa_demo. The first aa_demo is the name of the central store, while the second is actually the demo dataset. For BIDS114 it is aa_demo/ds114_test2.

Try using full path rather than "~".

**Comment by jpeelle** [comment]
Ah, I see now. I agree having the automatic download is excellent and it's an elegant script.

The other nonspecific error I reported has gone away.

I'm going to make a few modifications to aa_user_demo.m which I'm happy for feedback on, primarily adding more explanations in the comments (documenting all of the things I had to do in order to get the script to run).
