### ISSUE TITLE
Shell expansion in modules

### ISSUE THREAD

**Issue by jpeelle** [automaticanalysis/automaticanalysis#184]
I notice in aamod_segment8.xml:

```
     <tpm desc='path to tissue probability map file'>$SPMDIR/tpm/TPM.nii</tpm>
```

but unfortunately when I run this, aa tried to look for `/tpm/TPM.nii` (suggesting that $SPMDIR did not expand). @jooh is this something you were working with? I think in the old days this could be left blank and then the module itself would just look for something like `fullfile(aap.directory_conventions.spmdir, 'tpm', 'TPM.nii')` which typically worked.

To be clear I like the idea of expanding path names but just not the fact that it crashed my analysis. :)

I guess my questions are - how does variable expansion work, and why didn't it work for me? And is there something we can do to make it fail more gracefully? My workaround is just to specify TPMs but it would be nice if the defaults didn't fail (e.g. for new users).

**Comment by jooh** [comment]
SPMDIR gets set during aarecipe, so I'm a little surprised that it isn't working for you. The relevant lines are [here].(https://github.com/automaticanalysis/automaticanalysis/blob/06e0ac5f8fe01d4bf2c399af4248a3c00a61d28d/aa_engine/aarecipe.m#L148-L152)

Is aap.directory.conventions.spmdir set?

**Comment by jpeelle** [comment]
Ah I see—I had tried to set aap.directory_conventions.spmdir in the user script after aarecipe. Doing it the normal way (i.e. in my parameterset file) works. (I think in the old days it was possible to do it both ways but I might just be rusty.) Thanks!
