### ISSUE TITLE
Functions in /external (and elsewhere) are shadowing Matlab 

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#190]
Went to use a few functions from the signal processing toolbox today only to discover they're being shadowed by mfiles in /external/MRTools (e.g., filtfilt, butter). 

Does anyone know where these files came from? Why are they there? Can we delete them? 

Utilities are swell; utilities that prevent me from using Matlab functions I trust are not.

**Comment by jooh** [comment]
I would imagine the purpose is to avoid depending on the signal processing toolbox, which isn't included in all installs. But perhaps that dependency is already assumed by other parts of the code anyway.

**Comment by tiborauer** [comment]
All externals are listed in [README.json].(https://github.com/automaticanalysis/automaticanalysis/blob/master/external/README.json). MRTools is coming from http://mrtools.mgh.harvard.edu/index.php?title=Downloads

**Comment by tiborauer** [comment]
We rely on only Statistics and Image Processing toolboxes. See: [aa_build_standalone_2_build.m](https://github.com/automaticanalysis/automaticanalysis/blob/master/aa_toolbox/aa_build_standalone_2_build.m), lines 15-16

**Comment by jones-michael-s** [comment]
So it sounds like we're trying to be nice to people who don't have the signal processing toolbox installed.

Fair enough, but I'd still prefer to not have an installed toolbox shadowed. This happens because aa_init does an addpath(genpath(...)) on startup -- might using a -END option here fix the problem (i.e., _append_ rather than prepend the aa directories)?

**Comment by jpeelle** [comment]
We decided that having at the beginning of the path was better for reproducibility.
