### ISSUE TITLE
Tips for improving cluster performance?

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#194]
Hello all,

We are currently grinding though a new analysis on our cluster

Some modules are exhibiting excessively long (and wildly variable) run times. 

For example, on about 75% of the subjects, aamod_firstlevel_model finishes in about 3-4 hours. However, on the others the module runs for almost 24 hours.

For comparision, on my desktop machine (i.e., non-cluster) aamod_firstlevel finishes consistently
on this data in about two hours.

I've been adjusting walltime and mem requests, but I can't find settings that produce
consistent (and, ideally, shorter!) run times.

To be clear, I don't think this is a problem with aa, I think it is a problem (or a bad interaction)
with our cluster. One novel (for us) aspect of this analysis is we are saving the residuals for
subsequent processing. The residuals are floating point so the output files are huge (multi GB).
I don't understand why that would be a problem on a modern computing cluster, but apparently
it is on ours.

I realize its hard to diagnose the problem remotely, but does anyone have any suggestions? Or 
even what tools I could use to explore what the problem is?

Thanks for any help,
Mike

**Comment by tiborauer** [comment]
File I/O can explain the difference. When using cluster with a shared data space, then there is a considerable about of network traffic between compute nodes and data storage nodes (not only writing but reading, too); which is usually far from modern PCs/laptops; especially with SSDs.

**Comment by jones-michael-s** [comment]
Hi Tibor,

Thanks for the quick reply.

Apparently, we're stuck with our slow cluster. :-(

M

**Comment by tiborauer** [comment]
There may be things you can improve. E.g. if you are sure you have shared file system (i.e.) data storage is mapped to compute nodes. Make sure that AutoAttach is set. If you use `qsub`, then it is so:

https://github.com/automaticanalysis/automaticanalysis/blob/ee48221924755790fc91d4170ce9da6fc8d566df/aa_engine/aaq/aaq_qsub.m#L448

**Comment by jones-michael-s** [comment]
I found that one of the choke points on our cluster is spm_get_data() which I was using for ROI extraction. After rewriting the code to call it once with a collection of ROI rather than calling it for each ROI, the code runs much better on our cluster.

There are still other parts of the code that perform poorly on our cluster, but that's more a problem for us and not aa. I'll close the issue.
