### ISSUE TITLE
Domain wildcarding not working for us

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#195]
Recently tried the new aamod_norm_write which has been changed to domain='*' in the header (the previous version was domain session). Unfortunately this crashed. Temporarily changed the header back to domain session and the module ran fine.

Is there something we need to modify in our userscript or tasklist to take advantage of this feature?

Apologizes if this has been discussed elsewhere...

Mike

**Comment by tiborauer** [comment]
Can you tell a bit more about it? What is the error message? At what phase (loading tasklist, initialization, input retrieval, module execution)?
Do you use the latest version?
Can you send the tasklist and the UMS?

**Comment by jones-michael-s** [comment]
This was one of our postdocs; she cloned the distribution yesterday. The userscript and tasklist are a straightforward preprocessing pipeline (read, convert, realign, coreg, segment, norm, and smooth).

The crash happened during module execution trying to norm write an epi. We stepped through with the debugger and noticed the module is passed a subject index (line 57) but not a session index (line 58). It's as if the scheduler isn't recognizing the usage is session domain.

I don't have access to her machine at the moment (she doesn't come in on Friday) so unfortunately I can't list the exact error message, but I would say the crux of the problem is in the scheduler, not the module.

**Comment by tiborauer** [comment]
The order of the modules might be also important, because generic modules determine level based on input. Following on that, if aamod_norm_write receives output from realign, which outputs epi on subject level, then it may confound this process.

What would happen if you would also insert a slicetiming module, which operates on session level, between realign and  norm_write?

**Comment by jones-michael-s** [comment]
> Do you use coreg_extended(2)?

She's using aamod_coreg_noss.

I'll have to wait until Monday to follow up on the effects of modifying the pipeline.  I'll pass along more information then.

**Comment by tiborauer** [comment]
I think we all agreed on abandoning *_noss modules. Try building your pipeline based on the example(s)!

**Comment by jones-michael-s** [comment]
Will pass that along.  Thanks.
