### ISSUE TITLE
Questions about aa_export_toBIDS usage

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#197]
Have a few questions about aa_export_toBIDS:

1) aa_export_toBIDS uses the subject ID I supply in aas_addsubject in the filenames it creates. Is there an option to convert these to sub-01, sub-02, etc? This seems to be the preferred practice on, e.g., OpenNeuro.

2) Our experiments can have more than one timing data that applies to the same epi file. For example, we might present words in noise and analyze the response as words vs non-words or we might do an item analysis.  I believe BIDS handles this by allowing multiple columns in the the events tsv files. Is there a way to create this type of multi-column file using aa_export_toBIDS?

3)  My understanding of the BIDS standard is .nii files (and the associated json and tsv) should be named: subject-name_task-name_session-name. However, aa_export_toBIDS is using my session identifier as the task identifier, and isn't including a session identifier at all. Am I using it incorrectly? I don't see a way to pass a task identifier.

Thanks for any help,
Mike

**Comment by tiborauer** [comment]
Ad 1. What do you mean "convert to sub-01..."? The "sub" prefix is already added to the subjname. Numbering (i.e. 01, 02, etc.) is not required according to BIDS. Any alphanumeric ID can be used.

Ad 2.  I am afraid aa_export_toBIDS and aas_processBIDS cannot handle multiple models. There is some felxibility: https://github.com/automaticanalysis/automaticanalysis/blob/bcc9dca765200ab476bc6b9cbe8dc8c1c24f40b3/aa_toolbox/aa_export_toBIDS.m#L16-L17 https://github.com/automaticanalysis/automaticanalysis/blob/bcc9dca765200ab476bc6b9cbe8dc8c1c24f40b3/aa_toolbox/aa_export_toBIDS.m#L35-L37 It is on the to-do list to make it more felxible. There is a [BIDS extension proposel (BEP) for representing models in BIDS](https://docs.google.com/document/d/1bq5eNDHTb6Nkx3WUiOBgKvLNnaa5OMcGtD0AZ9yms2M), but it is not finalised, yet; and I did not want to develop in parallel. 

Ad 3. BIDS speicifcation is: `sub-<label>[_ses-<label>]_task-<label>[_run-<index>]`. However, session and task is specified differently in BIDS and aa. BIDS "session" is visit (e.g. pre and post), which is not defined in aa; while BIDS "task" is equivalent with aa "session". Maybe that causes the confusion.

**Comment by jones-michael-s** [comment]
> Ad 1. What do you mean "convert to sub-01..."? The "sub" prefix is already added to the subjname. Numbering (i.e. 01, 02, etc.) is not required according to BIDS. Any alphanumeric ID can be used.

The "sub" prefix is okay by me, but export_toBIDS is appending our internal subject identifiers (because this is what I use in aas_addsubject). We'd like to change those to the generic "01", "02", etc before making our data public. For now,  I can write a shell script to rename the files. Maybe eventually we could include an option in export_toBIDS to swap in generic subject names?

> It is on the to-do list to make it more felxible. There is a BIDS extension proposel (BEP) for representing models in BIDS, but it is not finalised, yet; and I did not want to develop in parallel.

No problem. This is something we can work around in the short-term.

 > However, session and task is specified differently in BIDS and aa. BIDS "session" is visit (e.g. pre and post), which is not defined in aa; while BIDS "task" is equivalent with aa "session". Maybe that causes the confusion.

Can I just rename the files to include a session and a task name? (That seems to be how data on OpenNeuro are named.) Or will that cause confusion with aas_processBIDS? (I suppose I could just try it and find out :-)

**Comment by tiborauer** [comment]
I suggest you reding the [BIDS specificatrion](https://bids-specification.readthedocs.io/en/stable/) rather than taking an example dataset, which may not be completely aligned with BIDS.


Ad 1.: [Here](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#participant-names-and-other-labels) you can read that participant ID are lables,. which "are strings and MUST only consist of letters (lower or upper case) and/or numbers".

Ad 3.: [Here](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#directory-structure) you can see that session name (in BIDS term) does not have to be included in case of a single session.
