### ISSUE TITLE
Bad interaction of FSL with filenames containing hyphens

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#199]
Hello all,

Recent testing uncovered a crash caused by calling FSL "slices" with a file having a hyphen in the name.

Recall the slices command syntax:

`slices input input2 -s <scale> -o output`

The problem is if the input filename contains an "-o", slices interprets this as the -o flag. For example:

`slices sub-01_task-overtverb_bold.nii t1.nii -s 3 -o output.gif`

will crash with slices complaining that it can't find the file "sub-01_task" (i.e., it thinks everything after the -o is the output filename). I should note this crash happens outside of aa -- i.e., when running slices from the command line. This isn't really an aa bug, it's an FSL bug.

So far I've only found this in slices and only with "-o" (filenames containing "-s" work ok). But BIDS generates a bazillion filenames with hyphens, so it seems to me this is a ticking time bomb. I also don't see an easy fix (unless we swap out every hyphen for an underscore every time aa generates a file, or FSL fixes its parser).

On the other hand, maybe it really is only slices and -o. Has anyone else encountered this (or a similar problem in other FSL functions)?

Regards,
Mike

**Comment by tiborauer** [comment]
I have not noticed it, but I am not surprised, either. I do not think we can do anything other than notifying FSL.
Have you tried putting the filename in quotation marks (single or double)? This might prevent slices to slipt it.

**Comment by jones-michael-s** [comment]
Yeah I tried the usual shell escape tricks. No joy.

I thought about modifying aamod_epifromnifti (and probably aamod_structuralfromnifti) to swap underscores for dashes in the output filename before we desc the output . Any idea whether that would create other problems? It seems to me it doesn't matter what the filename is -- aa traffics in streamnames not filenames. 

This isn't the first problem a dash in a filename has caused, and I'm pretty sure it won't be the last.

**Comment by tiborauer** [comment]
I guess it should not cause an issue unless aa_export_to BIDS relies on filename (which I doubt).

**Comment by jones-michael-s** [comment]
Closing issue because there's not much we can do about this.
