### ISSUE TITLE
Hard link

### ISSUE THREAD

**Issue by tiborauer** [automaticanalysis/automaticanalysis#206]
https://github.com/automaticanalysis/automaticanalysis/blob/6c036f0114657e90af5f457c759547bd6bb65b0d/aa_engine/aas_retrieve_inputs_part2.m#L128-L135 uses hard link to copy streams for certain cases (`~ismodified`), which is problematic for several reasons:
- The assumption that it acts like a `cp` and source is not deleted with the destination is not true. See: https://www.unixtutorial.org/reference/what-is-ln
- Certain systems (e.g. in Surrey) does not allow using hard links

Therefore, I propose replacing it with `cp` or `rsync` (i.e. removing condition check).

AFAIK, the original idea was to introduce links to avoid data redundancy; but it may be dangerous.

**Comment by tiborauer** [comment]
Any comments on this issue? I would really like to remove the hand links because it causes a serious issue in Surrey.

**Comment by jones-michael-s** [comment]
To make what is probably an obvious suggestion, could we make hard/soft links an option in the parameters file?

I seem to recall aa uses hardlinks for a reason, but that decision was way before my time...

**Comment by tiborauer** [comment]
An option can certainly work.
