### ISSUE TITLE
Odd aamod_coreg_extended behavior under SPM12 (7487)

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#207]
Hello all,

Recently noticed some odd behavior when using aamod_coreg_extended after upgrading SPM.

Here's a typical diagnostic graphic when running under old SPM12 (6906):
![aamod_coreg_extended__PL00016](https://user-images.githubusercontent.com/25826038/69354728-35518380-0c46-11ea-8fd8-93952af72d23.jpeg)

Here's results for the same subject and same pipeline running under SPM12 (7487):

![aamod_coreg_extended__PL00016](https://user-images.githubusercontent.com/25826038/69354798-51552500-0c46-11ea-88d3-6370e17c363b.jpeg)

The template mapping is now wonky.

I might assume this is harmless, but some of my t-maps are clearly not positioned correctly on the anatomy in aamod_firstlevel_threshold. The weird thing is the coreg diagnostic is wrong for _every_ subject in the dataset, but only _some_ of the threshold maps are wrong.

Has anybody else seen this? Did something change between 6906 and 7487? Do I need to change a parameter somewhere?

Thanks for any help,
Mike

**Comment by tiborauer** [comment]
Hi @jones-michael-s, I have not experienced any such oddities when switching between SPM versions. Is it a clean and full analysis or have you switched in-between. If the latter, then I would suggest re-running it from scratch into an empty folder. 
Also, have you restarted MATLAB and/or checked the path to make sure that there is only one version of SPM present?

**Comment by jones-michael-s** [comment]
Yep -- I ran the analysis from scratch into an empty folder after restarting Matlab. 

In fact, we noticed the wonky maps on a new machine that only has 7487 installed then tested the same pipeline and data on an older machine that only has 6906 installed (which produced good maps).

The final test was to install new SPM on the old machine, which now produces wonky maps.

Very puzzling.

**Comment by jooh** [comment]
What exactly looks wonky to you in the above graphic?

**Comment by jones-michael-s** [comment]
In the second graphic, the template (upper left) is not centered and is scaled differently than the structural (upper right).

Perhaps this is harmless?

**Comment by jones-michael-s** [comment]
Update: This is an SPM bug. If you step through the code. SPM draws the template views correctly, then wrecks them when it adds the structural (spm_orthviews redraws all existing window content every time new content is added).

You can test this via the GUI: Do a Check Reg and pick the T1 template and a structural (display wonky) then do Check Reg again and pick the files in the opposite order (display correct). You might have to use a structural that's larger than the template to trigger the bug.

Do we want to do anything about this? The SPM code is rather gnarly (I did a diff on spm_orthviews.m and there's been many changes between 6906 and 7487 so it's unclear what got broken). However, a simple work around would be to plot the structural first in the diagnostic image generated by aamod_coreg_extended.

M

**Comment by tiborauer** [comment]
It is great that you dig up so thoroughly!
If I understand it correctly, it depends which image has larger bounding box. So if we draw a structural, which is smaller, fist then the display can be also wonky.

**Comment by jones-michael-s** [comment]
Yes, I think it is the bounding box that is the issue and so you're right that there can be problems either way.

**Comment by tiborauer** [comment]
So we have to check the bounding box and set the order accordingly.

**Comment by jones-michael-s** [comment]
Alternatively, do you think we could get one of the SPM guys to look into fixing spm_orthviews?

**Comment by tiborauer** [comment]
You can certainly raise an issue. However, it might be an intended behaviour (determine bounding box based on the first image).

**Comment by tiborauer** [comment]
Is there any update on this issue? Is there anything we need to do about it or shall we close it?

**Comment by jones-michael-s** [comment]
Ultimately it's just a display issue (the coreg is correct). Until SPM fixes their code, we'll have to live with it.

Closed.
