### ISSUE TITLE
Shall we extend "meg" to "meeg"

### ISSUE THREAD

**Issue by tiborauer** [automaticanalysis/automaticanalysis#212]
I wonder whether we could use the same machinery for eeg and meg. it would mean that
- rawmegdatadir --> rawmeegdatadir
- megsubjectoutputformat --> meegsubjectoutputformat
- aas_add_meg_session --> aas_add_meeg_session
- megname --> meegname
- megseriesnumbers -->meegseriesnumbers
- meg_sessions --> meeg_sessions

Later some modules maye be also renames/repurposed. I am recently working on EEGLAB and FieldTrip, so I am not interested in using the existing modules at the moment but rather writing new ones.

**Comment by tiborauer** [comment]
Right now, I simply use the abovementioned meg machinery for eeg, which should work. But it would be nice (and perhaps less confusing) to reflect this in their name.

**Comment by jpeelle** [comment]
This makes sense to me. We are not doing any MEG/EEG at the moment so don't
care too much!

**Comment by tiborauer** [comment]
I am doing it then.
