### ISSUE TITLE
Is the file URL in aa_downloaddemo.m still valid?

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#234]
Finally getting around to automated testing.

I can't download the default file listed in aa_downloaddemo.m:

https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/57e549f9b83f6901d457d162

Is this URL still valid?

**Comment by tiborauer** [comment]
Yes, the link is still valid. I can also download it from within my browser, however, it may be possible that the link works better from within MATLAB (using the function).

**Comment by jones-michael-s** [comment]
Yeah I can get if from within a browser; I'm trying to hack together something using curl (wget doesn't play nice with OS-X).

**Comment by jones-michael-s** [comment]
Ok, never mind. Got it working (was a redirect thing).

**Comment by jones-michael-s** [comment]
Actually, while I'm here: Does anyone know if its possible to download data from OpenNeuro using curl or wget? I see options for browser, aws, Node.js, and DataLad -- shouldn't there be a URL for the data I can just grab?

**Comment by tiborauer** [comment]
I have never tried, but if a wrapper around DataLad seems to be an option. Or you can try incorporate Node.js using https://uk.mathworks.com/matlabcentral/fileexchange/68977-nodejs-in-matlab.
