### ISSUE TITLE
BUG -  aas_processBIDS crashing if data is already unzipped

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#236]
Hello all,

We occasionally come across BIDS data that has the nifti files already unzipped (i.e., the data directories will be populated with foo.nii rather than foo.nii.gz.)

However, aas_processBIDS expects to find .gz files and fails if it can't. 

Is there a reason aas_processBIDS couldn't also check if the files have already been unzipped and use those?

Our workaround has been to go into the data and re-zip all the nifti files. Modifying aas_processBIDS to be more flexible seems like a more sensible solution, but I'm never sure what is and isn't a violation of the BIDS standard.

Regards,
Mike

**Comment by tiborauer** [comment]
There is no reason. I have never encountered unzipped data, yet; however, you are right that it does not violate the standard.

**Comment by tiborauer** [comment]
You may want to check out [BIDS-MATLAB](https://github.com/bids-standard/bids-matlab), as well.

**Comment by Remi-Gau** [comment]
Thanks for the ping @tiborauer 

Yup .nii is BIDS valid.

BIDS-matlab is able to index a BIDS dataset and then query it using some specific "filters" including one based on extension if you want to only select `.nii` or `.nii.gz` files.

The `dev` branch should be stable enough for the most basic functionalities: https://github.com/bids-standard/bids-matlab/tree/dev

Example [here](https://github.com/bids-standard/bids-matlab/blob/b7732b0cb2103ee0cfa095ee604bee4086844cad/tests/test_bids_query.m#L49)

Very rudimentary [Read the docs](https://bids-matlab.readthedocs.io/en/latest/function_description.html#+bids.query)

**Comment by jones-michael-s** [comment]
Fixed this and pushed to my current PR (#240).

FYI.
