### ISSUE TITLE
Git no longer recognizes main repo as my upstream

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#237]
Hello all,

Getting ready to open a PR for my new developer tools, so I decide to first make sure my fork is up-to-date before pushing my local changes. However, instead I get this:

```
$ git pull upstream master
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

It's been awhile since I submitted a PR, but I've done this exact operation successfully in the past.

Has something changed?

Any tips for fixing this?

Thanks for any help,
Mike

**Comment by tiborauer** [comment]
I suggest you test your local repo settings. by typing `git remote -v`

**Comment by jones-michael-s** [comment]
Update: Re-adding the upstream seems to have fixed the problem (which I guess was the obvious solution but is still weird I needed to do this a second time).

Anyways, looks to be working now. 

Closing.
