### ISSUE TITLE
New toolbox loading crashes under PCT (OS-X)

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#239]
Example: aamod_segment8 line 54:

`[junk, SPMtool] = aas_cache_get(aap,'spm');`

This works fine in localsingle, but SPMtool is returned empty 
 when running under PCT. SPMtool.load then crashes.

IIRC, toolbox handling was recently rewritten. Might there
be a setting that needs tweaked in our aa parameter file?

Regards,
M

**Comment by tiborauer** [comment]
What is the error message?
Do you have SPM configured properly in the paremeterset?

**Comment by jones-michael-s** [comment]
> What is the error message?

`Dot indexing is not supported for variables of this type.`

(which is just SPMtool.load failing because SPMtool is empty)

> Do you have SPM configured properly in the paremeterset?

I think so -- as I noted, the analysis runs fine in localsingle.

Are there PCT-specific settings?

**Comment by tiborauer** [comment]
Shall we skype/teams/zoom?

**Comment by jones-michael-s** [comment]
That'd be great. 

Today is kind of busy for me, however. Would tomorrow work for you?

**Comment by tiborauer** [comment]
I think I found the issue:
`aacache` is a global variable and it is stored separately. When you run locally, it is available, however, when you use PCT, it has to be passed to the worker. `aaq_qsub` has been updated accordingly, but `aaq_matlab_pct` has not (in the central repo). @hhentschke has updated `aaq_matlab_pct` (see his [repo](https://github.com/hhentschke/automaticanalysis/blob/7ab1ab35d9ba6d7045e31ccbd39847e27ff10142/aa_engine/aaq/aaq_matlab_pct.m#L252-L259) and compare with the [central copy](https://github.com/automaticanalysis/automaticanalysis/blob/c8b1aa304b55de52015c6424ae948f99d991d261/aa_engine/aaq/aaq_matlab_pct.m#L199_L200)) but his commits have not been merged, yet.

You can either check out his repo (which also contains most of my recent developments) or take the snippet and insert it into your local copy.

**Comment by jones-michael-s** [comment]
That fixed it!

I'll include the 2 lines modification to aaq_matlab_pct in my PR.

Closing...
