### ISSUE TITLE
Parameter file XML include not looking in the distribution

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#247]
Finally getting around to organizing our parameter files by using the include feature (rather than customizing a full file). For example:

```
<?xml version="1.0" encoding="utf-8"?>
<aap xmlns:xi="http://www.w3.org/2001/XInclude">
    <xi:include href="aap_parameters_defaults.xml" parse="xml"/>
    <local>
	<directory_conventions>
        <spmdir desc="Path(s) to SPM software (>SPM12 r6470 required)" ui="dir">/Applications/spm12</spmdir>		
	</directory_conventions>
    </local>
</aap>
```
However, the xi:include fails unless I copy `aap_default_parameters.xml` to my working directory.  This is odd, because Matlab knows `aap_default_parameters.xml` lives in the repo (i.e., it's returned by `which('aap_default_parameters.xml') `).

Is this the intended behavior?

**Comment by tiborauer** [comment]
Certainly not intended. However, I have not seen this before. Are you sure you initialize aa properly and its subfolders are on the top of your MATLAB path?

**Comment by tiborauer** [comment]
Do you store your parameterset file(s) within aa (i.e. next to `aap_parameters_defaults.xml`?
If not, then you need to provide a full path to `aap_parameters_defaults.xml`. That is also how the user-specific `aap_parameters_user.xml` includes the sire-specific parameterset.

**Comment by tiborauer** [comment]
So, yes it is somewhat expected behaviour. `XML include` does not rely on MATLAB.

**Comment by jones-michael-s** [comment]
Okay, just verified that either storing my parameter file in /aa_parametersets fixes the problem and so does specifying a fullpath in the xml include. Neither are optimal solutions, but the latter is the lesser evil as we shouldn't require a user to modify the repo just to use AA.

**Comment by tiborauer** [comment]
You do not have to modify the repo when storing the parameterset (under a distinct name) in aa_parametersets. You do not have to commit them or worry about losing them during push/pull.
I think the whole idea of having aa_parametersets is to store parametersets there. Alternatively, we could just add (a few of) them to the examples; which also sounds plausible to me.

**Comment by jones-michael-s** [comment]
I don't mean modifying in the sense of push/pull.

Simply adding a file to the repo is "modifying the repo". 

User customization files don't belong in the code distribution. It's poor design.

**Comment by tiborauer** [comment]
Do you suggest, then, adding these parametersets to the examples?

**Comment by jones-michael-s** [comment]
I think there's already an adequate set of example parameter files in the distribution. IMO, what would really help is expanding the documentation. You've made a good start on the AA wiki parameterset section, but there's some critical details missing (like specifying a full path to the parameter file to be included, unless you put your parameter file in the distribution, which we now all agree is a bad thing :-)

**Comment by tiborauer** [comment]
Sorry. I meant MOVING (the subset of) the existing parametersets to the examples and omit the aa_parametersets folder.

I agree on expanding the documentation. @hhentschke is going to go through the ["Getting Started" section of the website](https://automaticanalysis.github.io/gettingstarted/), but feel free to contribute to it via PRs.

**Comment by jones-michael-s** [comment]
> Sorry. I meant MOVING (the subset of) the existing parametersets to the examples and omit the aa_parametersets folder.

Hmm. When I hear "examples" I think example _scripts_. But I don't feel strongly either way. 

> I agree on expanding the documentation.

I'm currently finishing up an AA tutorial (based on the auditory example in the SPM manual). I'm trying to make it sufficiently detailed so that an absolute AA newbie could successfully run the analysis. Perhaps we could include it as an appendix on the wiki.
