### ISSUE TITLE
ENH - Do not use pwd in aa_test

### ISSUE THREAD

**Issue by AljenU** [automaticanalysis/automaticanalysis#275]
The test log is currently written in pwd, i.e. the current directory. This is ill-defined, as it is possible to start running aa_test from any directory.
What is the expected location for the aa_log file? Then make sure it is put there.

**Comment by AljenU** [comment]
Since aa_test log is created before any parameter file is read, its not possible to put it in the acq_details main folder.
Also, if multiple tests are run, they all write to this same log file.
And, for CI, this would actually be a file that you DO want in the artifacts, to be able to look at the contents, so it should be at a well defined location.

Thus, although it is not that nice to put new files within the main directory structure, in this case it would be most logical to put it either in the main aa folder, or in the ./developer folder next to aa_test.m

**Comment by jones-michael-s** [comment]
I implemented logging thinking it was a useful addition because the tests would run unattended.

If its not workable with CI (or the group feels it is not useful) I would be open to removing it.

**Comment by tiborauer** [comment]
I'd rather keep the logfile and use it as the main artifact extended with the [aa_jpeg_crawler.m](https://github.com/automaticanalysis/automaticanalysis/blob/master/developer/aa_jpeg_crawler.m).

**Comment by AljenU** [comment]
Yes, my idea was just that in the two times that there is `fullfile(pwd,'aa_test.log')`, the pwd should be replaced with either aa.Path [but that is only available later, so needs some code shuffling], or fileparts(mfilename('full path')) [directly available, and if there is logging during aaClass it will be included].

[Actually, the filename should be created only once and put in a variable, not constructed-on-the-fly twice]
