### ISSUE TITLE
BUG - Fail to start BrainWavelet toolbox

### ISSUE THREAD

**Issue by ethanknights** [automaticanalysis/automaticanalysis#286]
**Describe the bug**
Fail to start BrainWavelet toolbox. 

The path to the BWT toolbox hasn't been altered in the CBU cluster for a few years. 
So, instead, I suspect it might be related recent commits that introduce new toolbox classes (in this recent commit): cef8e471ae7d3704019d859807e545748d215741
e.g. in file: aa_modules/aamod_waveletdespike.m  

I haven't quite followed how to start toolboxes with these classes. Maybe these methods are still a work-in-progress, or perhaps I'm missing a critical step for initialising the toolbox. At the moment, I am not specifying any toolbox path or command to set them up, other than the default path definition in this parameter set: https://github.com/automaticanalysis/automaticanalysis/blob/cef8e471ae7d3704019d859807e545748d215741/aa_parametersets/aap_parameters_defaults_CBSU.xml#L66

**To Reproduce**
The aa masterscript and tasklist.xml are here: https://github.com/ethanknights/tmp_CC280_rest

Error:
```
**** automatic analysis failed - see reason and line numbers below
Wavelet despiking toolbox not found
for help, see the aa wiki
Error using aas_log (line 67)
aa error:
see above (or set aap.options.verbose)
```

**Environment (please complete the following information):**
 - OS with version: CentOS 7
 - MATLAB version: 2019a
 - Relevant toolboxes with version: 1.1

** Additional Info **
The waveletdespike.m function uses aas_cache_get, which fails specifically here:
https://github.com/automaticanalysis/automaticanalysis/blob/cef8e471ae7d3704019d859807e545748d215741/aa_modules/aamod_waveletdespike.m#L12-L13 

Maybe I should have done something earlier (e.g. in masterscript?) to load the toolbox. Something to the effect of:
```
>> bwtClass('/imaging/local/software/BrainWavelet')

ans = 

  bwtClass with properties:

          name: ''
      toolPath: '/imaging/local/software/BrainWavelet'
      autoLoad: 0
    keepInPath: 0
       showGUI: 0
        status: 'defined'
```

This isn't a major issue for me, as I'll try fall back to an older version for now, but thought might be a useful flag about updates. Any advice appreciated though, thanks!

**Comment by tiborauer** [comment]
Hi @ethanknights,
We have recently introduced "[toolboxes](https://automaticanalysis.github.io/_pages/toolboxes.html)" for tighter integration of tools. We started converting previously integrated tools into toolboxes, and `BrainWavelet` is our next "victim".
From now on, setting `BrainWaveletdir` is obsolete and your parameterset should rather contain this section:

``` xml
        <toolbox desc='Toolbox with implemented interface in extrafunctions/toolboxes' ui='custom'>
            <name desc='Name corresponding to the name of the interface without the "Class" suffix' ui='text'>bwt</name>
            <dir ui='dir'>/imaging/local/software/BrainWavelet</dir>
        </toolbox>
```
Please. keep in mind that all toolbox specifications MUST follow each other (i.e. after https://github.com/automaticanalysis/automaticanalysis/blob/cef8e471ae7d3704019d859807e545748d215741/aa_parametersets/aap_parameters_defaults_CBSU.xml#L26-L50), as they form a single list in the XLM.

**Comment by ethanknights** [comment]
Thankyou @tiborauer! Pull request https://github.com/automaticanalysis/automaticanalysis/pull/283 now suggests to make this change in the default CBSU parameter file.
