### ISSUE TITLE
BUG - hardcoded path in aas_getfiles_bystream

### ISSUE THREAD

**Issue by AljenU** [automaticanalysis/automaticanalysis#294]
in aas_getfiles_bystream

line 140

unix('touch /Users/peellelab/000_AAS_GETFILE_FAIL3.txt');

**Comment by tiborauer** [comment]
My #293 already contains the fix

**Comment by jones-michael-s** [comment]
This was my screwup.

I was trying to track down an intermittent problem with the PCT. Forgot to strip all my diagnostic code. Trying to do too much at once...

Mea culpa.
