### ISSUE TITLE
ENH - Make all absolute path settings in parameter defaults xml empty.

### ISSUE THREAD

**Issue by AljenU** [automaticanalysis/automaticanalysis#297]
Currently, assumptions are made, and user-specific folders are present. This does not work well when a new user derives from the defaults xml. Make all entries that should contain absolute paths, empty in the defaults xml.

See also https://github.com/automaticanalysis/automaticanalysis/discussions/254#discussioncomment-1669801

The entries:
acq_details/root
rawdatadir
rawmeegdatadir
fsldir
freesurferdir
condorwrapper
ROIdir
realtime/path

Already empty:
toolbox/spm/dir
toolbox/eeglab/dir

**Comment by jones-michael-s** [comment]
Should we also add empty toolbox stubs for bwt, wls, conn, fieldtrip, hcpwb, cosmomvpa, and tdt (so the user knows they are available)?

**Comment by tiborauer** [comment]
I also think it is a good idea, however, some changes in aa_init will be also required.
As it is now, aa_init tries adding the toolboxes specified in the parameterset. An additional condition should be added to https://github.com/automaticanalysis/automaticanalysis/blob/58856ea2cf538658b0f4670f3168e6095336f078/aa_engine/aa_init.m#L117-L122 to avoid aa_init processing specification with an empty path.

**Comment by AljenU** [comment]
Fixed with #298 (not sure why it did not close automatically)
