### ISSUE TITLE
BUG - aa_ver5 takes too long

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#330]
When I follow the tutorial, and add SPM as a path along with aa, running the aa_ver5 commands takes very long.  I waited for 10 minutes and didn't receive a welcome message. Granted my computer is pretty powerful, if this process is just adding a few paths, it should take at most a minute. Something is wrong here. What should I do?

**Comment by TamerGezici** [comment]
![image](https://user-images.githubusercontent.com/11014942/170941483-a446480f-a419-4f6a-b4bb-35421218c446.png)

And here's what happened after running the command for 45~ minutes

**Comment by jones-michael-s** [comment]
Hello,

Sorry to hear about your aa difficulty!

Could you provide some information about your system? Specifically, which OS are you running (Linux, OS, or Windows) and what version of Matlab. Also, do you have any SPM extensions (i.e., [any of these](https://www.fil.ion.ucl.ac.uk/spm/ext/#toolboxes)) installed?

Thanks much,
Mike

**Comment by jones-michael-s** [comment]
Ok, thanks.

Let me look into this a bit...

**Comment by TamerGezici** [comment]
Sure. Thanks a lot. By the way we can also use this with docker if it will work fine. It's just that the container is 3 years old, is it still upto date? And is there a tutorial on how to use aa with docker?

**Comment by TamerGezici** [comment]
> Hi @TamerGezici, Thank you for submitting the issue. I have just tested it on Windows (without ) and was not able to replicate this. issue. However, the note on infinite recursion gives a clue. I think the issue is an unresolved Windows compatibility and that you do not have write-access in the current folder. `aaClass` tries to create the '.aa' folder in `HOME`, which is not defined in Windows. Therfore, aa tries to create the folder in the current folder. If you do not have write-access, then it calls `aas_log`, which, again, calls `aaClass`; thus leading to an infinite recursion.
> 
> I have just committed [a quick patch](https://github.com/automaticanalysis/automaticanalysis/commit/2769f142f2b3bd12852a52bd930e1796b1048e96), which is expected to solve this issue. Please, give it a try!

Thank you. This solved the problem and I have been able to run the tutorial script just fine on my personal computer. Tomorrow I will try it on the lab computer and see if it's fine there as well.

**Comment by TamerGezici** [comment]
It works just fine on all our lab computers. Thank you for your quick fix.

**Comment by tiborauer** [comment]
Thank you for your cooperation and patience!
