### ISSUE TITLE
BUG - Issue with using rm in windows

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#335]
- OS with version: Win 10
 - MATLAB version: R2021b
 - Relevant toolboxes with version: [e.g. SPM12 r7771]
![image](https://user-images.githubusercontent.com/11014942/174430218-f7d91349-bafa-43d4-b952-888f0e7892ed.png)

(This is a different computer than others I ran this script on, this issue had not happened on my other 2 computers)

```
***LINUX ERROR FROM SHELL 'rm' is not recognized as an internal or external command,
operable program or batch file.

***WHILE RUNNING COMMAND
rm E:

**** automatic analysis failed - see reason and line numbers below
***WITH ENVIRONMENT VARIABLES
The system cannot find the path specified.

for help, see the aa wiki
Error using aas_log (line 67)
aa error:
see above (or set aap.options.verbose)


Error in aas_shell (line 58)
    aas_log([],stopforerrors,sprintf('***WITH ENVIRONMENT VARIABLES\n%s',wenv));

Error in aamod_norm_write (line 107)
                    aas_shell(['rm ' thisfile]);

Error in aa_feval (line 15)
    [varargout{:}]=feval(funcname,varargin{:});

Error in aa_feval_withindices (line 4)
[aap,resp]=aa_feval(mfile_alias,aap,task,ci{:});

Error in aa_doprocessing_onetask (line 191)
            [aap,~]=aa_feval_withindices(mfile_alias,aap,task,indices);

Error in aaq_localsingle/runall (line 15)
                aa_doprocessing_onetask(obj.aap,job.task,job.k,job.indices);

Error in aa_doprocessing (line 361)
            taskqueue.runall(dontcloseexistingworkers, false);

Error in HCF_prep_BIDS (line 59)
aa_doprocessing(aap);

```
In aamod_norm_write.m: line 107, it tries to execute `aas_shell(['rm ' thisfile]);`  however, rm doesn't exist as a windows command and I think this causes an issue with the paths. Assume my path was: 'E:\path\to\analysis\dir'. The path was only interpreted as 'E:' when the command ran, it failed and complained that the path did not exist. I think it wasn't interpreting the path properly. 

**I was able to fix the issue by replacing this line with:**

`aas_shell(['del ' thisfile]);`

**Comment by tiborauer** [comment]
Thank you! It is yet another Windows compatibility issue. The code should check whether it is running on Windows (`ispc`) and use `del` instead `rm` (which is for cases `~ispc`.

**Comment by TamerGezici** [comment]
> Thank you! It is yet another Windows compatibility issue. The code should check whether it is running on Windows (`ispc`) and use `del` instead `rm` (which is for cases `~ispc`.

Yeah. I guess we can also use "rmpath", an inbuilt matlab function. This would make it cross-platform compatible and cause less code clutter. But I couldn't get that function working for some reason.

**Comment by tiborauer** [comment]
Ah, indeed, MATLAB has inbuilt function for deletion, but it is called `delete`. `rmpath` removes the folder from the MATLAB path.
