### ISSUE TITLE
Excluding subjects from first level analysis.

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#336]
My data is roughly in BIDS. So I use BIDS processing to load them in to aap structure. But my study consists of different types of tasks and not all participants undergo the same tasks, so not each subject number has the same task in their directories.

Since my data is in BIDS, and when I run a first level analysis, it complains that it can not find a model specification for specific participants (their event specification). I am guessing this is because their details are in aap.acq_details.subjects.subjname but there is no model specification for them in aap.tasksettings.aamod_firstlevel_model.model  

Is there a way to exclude specific subjects from going through first level analysis? I know that you can specify contrasts for participants, but for first level everyone is processed if they are in the aap structure. So although I specify contrasts for participants, that doesn't help because participants which I don't want to process are attempted for analysis.

I was thinking of emptying the aap.acq_details.subjects.subjname field and filling them with my own subjects, but MATLAB is kinda quirky, so I wanted to ask here first.

When I used addsubject and provided files generated from the last step of preprocessing (smoothened files) as inputs, the script thought they were new participants are started preprocessing them from scratch.

**Comment by tiborauer** [comment]
Do you use `aas_processBIDS`?

**Comment by TamerGezici** [comment]
> Do you use `aas_processBIDS`?

Yes.

**Comment by tiborauer** [comment]
Then you should have all subjects added to the aamod_firstlevel_model, which you can confirm by looking at `aap.tasksettings.aamod_firstlevel_model.model`

**Comment by TamerGezici** [comment]
Sorry for not being specific. I do use processbids for nifti images, but I add my event files seperately (I am not putting each event file next to the nifti's and pairing them with each other) so not all my participants end up being in `aap.tasksettings.aamod_firstlevel_model.model`

**Comment by tiborauer** [comment]
`aas_addsubject` only adds subject to the workflow in general. To add subject(s) to the first level modelling, you have to use `aas_add_event`.

**Comment by TamerGezici** [comment]
Okay let's scratch that. The situation is different and I think I couldn't explain it in an understandable way. But that's fine, we don't need to spend time on solving the issue this way.

I think I will opt-out of using processbids and use addsubject instead. Can you please direct me in the right direction to use addsubject? 

Is the example above the correct usage? And how can I solve the issue of AA not being able to find the header (TR values etc.)

**Comment by tiborauer** [comment]
Use `aas_addsubject` and specify functional input as a structure:
https://github.com/automaticanalysis/automaticanalysis/blob/2769f142f2b3bd12852a52bd930e1796b1048e96/aa_engine/aas_addsubject.m#L42

**Comment by TamerGezici** [comment]
> Use `aas_addsubject` and specify functional input as a structure:
> 
> https://github.com/automaticanalysis/automaticanalysis/blob/2769f142f2b3bd12852a52bd930e1796b1048e96/aa_engine/aas_addsubject.m#L42
> 
> 
> where header can be the BIDS JSON file

I'm so sorry. This is what I understood.

```
subject_data.fname = 'E:\fMRI\fr-pr-3-AA\fmri_raw_bids\bids\sub-01\ses-1\func\sub-01_ses-1_task-discrB_run-01_bold.nii';
subject_data.hdr = 'E:\fMRI\fr-pr-3-AA\fmri_raw_bids\bids\sub-01\ses-1\func\sub-01_ses-1_task-discrB_run-01_bold.json';

aap = aas_addsubject(aap,'sub-01_sess-1',1,'functional',subject_data);
```

**Comment by tiborauer** [comment]
Close! :-) The structure replaces the string but the input  is supposed to be a cell array. So you have to put the subject_data into curly brackets.

**Comment by TamerGezici** [comment]
Yes. That worked. Thanks a lot!

**Comment by TamerGezici** [comment]
Dear @tiborauer 

Is this the correct way of specifying multiple sessions per subject? Where subject_number is a string such as "sub-01"

`aap = aas_addcontrast(aap, 'aamod_firstlevel_contrasts', {subject_number}, 'session:discrB_run-01+session:discrB_run-02', [-1 -1 -1 -1 1 1 1 1 0 0 0 0], 'S_M_R', 'T');`

**Comment by tiborauer** [comment]
- The third iinput must be a string. Either the same as the subject name (i.e. 'sub-01'), or '*' for all subjects (if all of them have both sessions).
- I suggest removing "-" from the session name because it may confuse the interpreter.
- The specification of your conrtasts vector assumes thah both sessions have 12 events in the same order. Is that the case?

**Comment by TamerGezici** [comment]
The contrast vector is fine. Because I was able to replicate previous analysis I have done before for a single subject. The issue arises when I have several subjects, and not all of them have equal amount of sessions and when I add contrasts for them.

**Comment by tiborauer** [comment]
> - The third input must be a string. Either the same as the subject name (i.e. 'sub-01'), or '*' for all subjects (if all of them have both sessions).

I.e.

`aap = aas_addcontrast(aap, 'aamod_firstlevel_contrasts', subject_number, 'session:discrB_run-01+discrB_run-02', [-1 -1 -1 -1 1 1 1 1 0 0 0 0], 'S_M_R', 'T');`
or
`aap = aas_addcontrast(aap, 'aamod_firstlevel_contrasts', '*', 'session:discrB_run-01+discrB_run-02', [-1 -1 -1 -1 1 1 1 1 0 0 0 0], 'S_M_R', 'T');`

**Comment by TamerGezici** [comment]
If it helps, let me paste my source code here:
```

%% NOTES:
%aas_garbagecollection(aap,1) % run this (in the command line) to delete duplicate files
% <module><name>aamod_segment8_multichan</name>
% <module><name>aamod_biascorrect_structural</name></module>
% - Motion FingerPrint instead of simple mocoparameters in fmri_advanced.m
% Check MVPA 
% Check autoidentifystructuralmultiple (in aap structure)


%% Settings:
aa_ver5;
aap = aarecipe('aap_parameters_user.xml','HCF_analysis.xml'); % HCF_prep_BIDS % HCF_analysis
DATA_PATH = 'E:\fMRI\fr-pr-3-AA\fmri_raw_bids\bids';
ROOT_PATH = 'D:\HCFprep\AAresults';
RESULTS_DIR = 'test';
aap.directory_conventions.analysisid = RESULTS_DIR;
aap.directory_conventions.rawdatadir = DATA_PATH;
aap.directory_conventions.subject_directory_format = 1;
aap.acq_details.root = ROOT_PATH;

% feature('numcores') % First get the no of cores on your machine
% aap.options.wheretoprocess='parpool'; 
% aap.directory_conventions.poolprofile = 'local';
% Set your workers accordingly. (Number of cores - 1)
% Allocate 2GB RAM per worker and leave 4GB RAM for your OS.
% aap.options.aaparallel.numberofworkers = 5; %

aap.tasksettings.aamod_slicetiming.sliceorder=[32:-1:1];
aap.tasksettings.aamod_slicetiming.refslice = 16;
aap.tasksettings.aamod_smooth.FWHM = 6;
aap.acq_details.numdummies = 0;
aap.acq_details.input.correctEVfordummies = 0;
aap.options.NIFTI4D = 1;
aap.options.garbagecollection = 1;

aap.tasksettings.aamod_firstlevel_model.xBF.name = 'hrf';
aap.tasksettings.aamod_firstlevel_model.xBF.UNITS = 'secs';
aap.tasksettings.aamod_firstlevel_model.includemovementpars = 1; % Include/exclude Moco params in/from DM, typical value 1
%aap = aas_processBIDS(aap);

%% Process participants
session_identifier = '_ses-1'; % this will be merged with the subject name / number to find the subject and cater to the BIDS format
select_func = 'bold';
subj_list = {'sub-01','sub-02','sub-05','sub-07','sub-08','sub-09','sub-12','sub-13','sub-14','sub-19'}; % ,
% d = dir(fullfile(DATA_PATH,'sub*')) % get all subjects as a list

for i=1:size(subj_list,2)
    subj = subj_list{i};
    anat_dir = fullfile(DATA_PATH,subj,session_identifier(2:6),'anat');
    anat_path = dir(fullfile(anat_dir,'*run-1_T1w.nii'));
    anat_hdr = dir(fullfile(anat_dir,'*run-1_T1w.json'));

    func_dir = fullfile(DATA_PATH,subj,session_identifier(2:6),'func');
    func_path = dir(fullfile(func_dir,strcat('*',select_func,'*','.nii'))); 
    func_hdr = dir(fullfile(func_dir,strcat('*',select_func,'*','.nii')));

    subject_data_anat = struct;
    subject_data_anat.fname = fullfile(anat_path.folder,anat_path.name);
    subject_data_anat.hdr = fullfile(anat_hdr.folder,anat_hdr.name);

    subject_data_func = struct;
    for i=1:size(func_path,1)
        subject_data_func(i).fname = fullfile(func_path(i).folder,func_path(i).name);
        subject_data_func(i).hdr = fullfile(func_hdr(i).folder,func_hdr(i).name);
    end
    aap = aas_addsubject(aap,subj,'functional',{subject_data_func},'structural',{subject_data_anat});
end

%%
tasknames = {'discrB_run-01','discrB_run-02','discrB_run-03'};
for i = 1:size(tasknames,2)
    aap = aas_addsession(aap,tasknames{i}); 
end

evnames{1} = 'r1';
evnames{2} = 'r2';
evnames{3} = 'r3';
evnames{4} = 'r4';
evnames{5} = 's1';
evnames{6} = 's2';
evnames{7} = 's3';
evnames{8} = 's4';
evnames{9} = 'start';
evnames{10} = 'session_rest';
evnames{11} = 'rs';
evnames{12} = 'ITE';
n_conditions = length(evnames); 

events_folder = 'D:\HCFprep\events_sr';
for sub = 1:size(subj_list,2)
    subject_number = subj_list(sub);
    subject_number = subject_number{1};
    %participant_tasks = subjects(subject_number);
    %your event file names need to be in sub-n format
    events = load(fullfile(events_folder, subject_number(1:6))); % only take the sub-n part for example: sub-01
    participant_name=fieldnames(events); % get the participant name as a string
    eval(strcat('events=events.',participant_name{end},';')); % take this participant from the struct
    n_sessions = max(events(:,1));
    participant_sessions = 'sessions:';
    for session = 1:n_sessions % runs (or tasks)
        session_onsets = events(events(:,1)==session,2:4);
        session_name = aap.acq_details.sessions(session).name;
        participant_sessions = strcat(participant_sessions,session_name,'+');
        for condition = 1:(n_conditions) % loop through event types
            session_events = find(session_onsets(:,1)==condition); % get index of events matching current type
            if ~isempty(session_events)
                durs = session_onsets(session_events,3);
                onsets = session_onsets(session_events,2);
                %task_name = participant_tasks{session};
                condition_name = evnames{condition};
                aap = aas_addevent(aap,'aamod_firstlevel_model_*',subject_number,...
                    aap.acq_details.sessions(session).name,... % run    %task_name,... % run/session/task
                    condition_name,... % condition name
                    onsets',... % onset
                    durs'); % duration
            end
        end
    end
    participant_sessions = participant_sessions(1:end-1); % remove the "+" at the end
    %aap = aas_addcontrast(aap, 'aamod_firstlevel_contrasts', subject_number, 'sessions:discrB_run-01+discrB_run-02+discrB_run-03', [-1 -1 -1 -1 1 1 1 1 0 0 0 0], 'S_M_R', 'T');
    aap = aas_addcontrast(aap, 'aamod_firstlevel_contrasts', subject_number, participant_sessions, [-1 -1 -1 -1 1 1 1 1 0 0 0 0], 'S_M_R', 'T');
    aap = aas_addcontrast(aap, 'aamod_firstlevel_contrasts', subject_number, participant_sessions, [0 -1 -1 -1 0 1 1 1 0 0 0 0], 'S_M_R_2', 'T');
    aap = aas_addcontrast(aap, 'aamod_firstlevel_contrasts', subject_number, participant_sessions, [0 0 -1 -1 0 0 0 0 0 0 0 0], 'S_M_R_POS_1', 'T');
    aap = aas_addcontrast(aap, 'aamod_firstlevel_contrasts', subject_number, participant_sessions, [0 0 0 0 0 0 0 0 0 -1 1 0], 'ITE_M_SESSR', 'T');
end

%aa_doprocessing(aap);
```

**Comment by TamerGezici** [comment]
After doing some debugging I noticed something weird. Check aas_addcontrast.m

Line 274 is a for loop which lists over the subject list provided to the function.

At line 288 subj (as a number) is passed onto get_series. 

However, this assumes the subject that is currently being worked on is equal to the subject number. If you pass on a single subject to add_contrast one by one for each subject like I'm doing it, it will always get the series for subject 1.

Instead, shouldn't this code use "subjname" as an identifier for subjects, and then find that subject's index in the `aap.acq_details.subjects.subjname` and use that index to grab the series? 

Because think of a situation where you are passing a list of subjects like: {'sub-01','sub-03'} to add contrasts, skipping the second subject, wouldn't this cause an indexing mistake? Subj 1 will be 1, but subj 3 will be index 2, and the wrong series will be selected?

**Comment by TamerGezici** [comment]
I figured what the issue was. I thought add_subject would accept an indexed struct, turns out that each struct with hdr and fname need to be given to the cell array seperately, so doing it like this fixed it:

```
 subject_data = {};
    for i=1:size(func_path,1)
        tmp_struct = struct('fname',fullfile(func_path(i).folder,func_path(i).name),'hdr',fullfile(func_hdr(i).folder,func_hdr(i).name));
        subject_data{end+1} = tmp_struct;
    end
    aap = aas_addsubject(aap,subj,'functional',subject_data,'structural',{subject_data_anat});
```

Though, I feel like what I wrote above aas_addcontrast.m still holds true, I'm sure there's an issue there.

**Comment by tiborauer** [comment]
Yes, that is what I wrote earlier [here](https://github.com/automaticanalysis/automaticanalysis/issues/336#issuecomment-1159787613).
