### ISSUE TITLE
Elaboration on some modules

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#337]
My current module list is as this: 

My questions regarding the modules are at the end.

```
<?xml version="1.0" encoding="utf-8"?>
<aap>
    <tasklist>
        
        <initialisation>	
            <module><name>aamod_study_init</name></module>
        </initialisation>
		
        <main>
                    
        <!-- preprocessing -->

        <module><name>aamod_structuralfromnifti</name></module>
        <module><name>aamod_reorienttomiddle_structural</name></module>

        <module><name>aamod_epifromnifti</name></module>
        <module><name>aamod_reorienttomiddle_epi</name></module>

        <module><name>aamod_realign</name></module> 
        <module><name>aamod_slicetiming</name></module>
        <module><name>aamod_coreg_extended</name></module>
        <module><name>aamod_biascorrect_structural</name></module>

        <module><name>aamod_segment_structural</name></module>

        <module><name>aamod_norm_write_epi</name></module>

        <module><name>aamod_smooth</name></module>

        <!-- first-level model -->
            
        <module><name>aamod_firstlevel_model</name></module>
        <module><name>aamod_firstlevel_contrasts</name></module> 
        <module><name>aamod_firstlevel_threshold</name></module>

        <!-- second-level model -->

        <module><name>aamod_secondlevel_model</name></module>	
        <module><name>aamod_secondlevel_contrasts</name></module>
        <module><name>aamod_secondlevel_threshold</name></module>	 
        </main>
    </tasklist>
</aap>
```

- SPM_CH30 tutorial module list did not have slicetiming, I added it explicitly. Is that fine?
- Shall I add tsdiffana here? And I see that this module is used two times in fmri_advanced.xml. Is there a specific order of things I should follow and where I should place it? (Sorry if its a too newbie question, I haven't seen or heard of this before)
- I noticed there is MVPA integration. Which MVPA toolbox does it utilize? Is it decoding toolbox or libsvm? Is it feasible to use it since the last commit on the files was 9 years ago?
- MVPA has a "how to" file. Are there any example scripts for marsbar integration as well?
- Does my module list do structural coregisteration? When I look at fmri_advanced.xml, I see that there are three coregisterations. Should I add them as well?
- I wanted to add bias correction with `aamod_biascorrect_structural` but when I did that, It complained about not finding TPM.nii, which is fine, I specified it myself like this: `aap.tasksettings.aamod_biascorrect_structural.tpm = fullfile(spm('dir'), 'tpm', 'TPM.nii'); `But I noticed it was looking for it in` Error in aamod_biascorrect_segment8_multichan (line 64)` which was weird. Because I don't have that as a module. So is my current segment structural compatible with biascorrection? And also what is the difference between the two? Or am I supposed to add `aamod_biascorrect_segment8_multichan` instead? 

I know there are a lot of questions. Thanks in advance for your answers :)

**Comment by tiborauer** [comment]
- Adding slicetiming is fine, however you have to specify `aap.tasksettings.aamod_slicetiming.refslice` and `aap.tasksettings.aamod_slicetiming.sliceorder`or `aap.tasksettings.aamod_slicetiming.autodetectSO`. See the [module header](https://github.com/automaticanalysis/automaticanalysis/blob/master/aa_modules/aamod_slicetiming.xml) for further documentation.
- tsdiffana is a fMRI QA module. You can add anywhere and anytime between `aamod_reorienttomiddle_epi` and `aamod_firstlevel_model`. I usually use twice, before and after the preprocessing.
- If you mean [mvpaa](https://github.com/automaticanalysis/automaticanalysis/tree/master/aa_tools/mvpaa), then it is an obsolete and untested set of modules, and I cannot say more about it. It may work, though, but I cannot guarantee it. There are, however, newer modules integrating CoSMoMVPA and TDT toolboxes. See modules with the names of the toolboxes in them.
- marsbar is not integrated, and it is not even in the plans. I usually use roiextract on firstlevel betas or contrasts to get estimates.
- In your workflow, `aamod_coreg_extended` does structural coregistration. fmri_advanced uses a two-stage approach I described earlier
- If you look at the module header of `aamod_biascorrect_structural`, you see that it actually calls `aamod_biascorrect_segment8_multichan.m` (see `mfile_alias='aamod_biascorrect_segment8_multichan'`). This is a common aa-practice to reuse module bodies (m-files) with different pre-specified parameters or even different streams. Also, some cases, such as bias correction, need some clean-up to remove redundancies and ambiguities. You are on the safe side as long as you follow the non-CBU examples, which are actively maintained.

**Comment by TamerGezici** [comment]
Thanks for your answers. That clarifies a lot for me.

> * marsbar is not integrated, and it is not even in the plans. I usually use roiextract on firstlevel betas or contrasts to get estimates.

I was talking about this module when I said marsbar: https://github.com/automaticanalysis/automaticanalysis/blob/master/aa_modules/aamod_marsbar.m

**Comment by TamerGezici** [comment]
Finally, what does `aamod_biascorrect_meanepi` do? From the header I see that it inherits from `aamod_biascorrect`.  

I see that `ds000114_motor.xml` contains both structural and epi bias correction. What does the latter do? Shall I add it as well?

**Comment by tiborauer** [comment]
I forgot about the `aamod_marsbar` module. I have not touched it for a while, but feel free to use (and report ;)).

`aamod_biascorrect_meanepi` correct bias for the meanepi, as its name suggests. You may need to use if there is a considerable RF bias in your EPI, but I do not use it regularly.

**Comment by TamerGezici** [comment]
Right now I am running AA on WSL to test how FSL integration works. I am particularly interested `aamod_bet`. The module suggests doing this somewhere between realignment and normalization. Shall I run this right before normalization, or shall I also take into account it's position in relation to bias correction and segmentation as well?

**Comment by tiborauer** [comment]
FSL is not integrated as a whole buy rather in parts. BET, for example, is integrated and used in some examples, as well.

However, you do not need BET for fMRI analysis with SPM. In fact, it sometimes makes registration/normalisation worse. I use BET mostly for DTI.

**Comment by TamerGezici** [comment]
I haven't used BET myself so I asked a member in our lab who uses it. She said we mainly use it to visualize brain activation on the patient's unnormalized brain directly. However when you do that, apparently the skull is rendered as well so we remove the skull to visualize things better. I thought we were analyzing data on BET'ed images but it turns out this is just to visualize things.

**Comment by tiborauer** [comment]
You can add `aamod_bet` just before the `aamod_firstlevel_threshold`. Make sure you add the module which processes structural stream.

**Comment by TamerGezici** [comment]
Once again, thank you so much for your answers.

I showed our preprocessing analysis pipeline to a few lab members today. So far, the approach members in the lab took for preprocessing was to use the SPM GUI using the tutorial in this [youtube video](https://www.youtube.com/watch?v=i39j-t7eRiY&t=2s). 

What they claimed is, and what I also confirmed -- that overall running things with AA is slower than using the gui itself. For example, realignment or slicetiming takes about 1-2 minutes when you do it through GUI for a single subject for a single session, however when you run AA it takes much longer (5-6 minutes).

Why is it that it takes longer for the outputs to be generated, when you run AA?

**Comment by tiborauer** [comment]
- aa does data management (copying and sorting the data as inputs and outputs to make sure that things work the same for 1-2-many session), sanity checks, QA (realignment plots), and provenance tracking. Because of this overhead, things are more organised, transparent, and reproducible, and you do not have to worry about e.g. filename prefixes if you change the order of realignment and slicetiming
- I am not sure whether the settings for aa and the GUI were identical, i.e. you were doing the same thing. Also, if you use automaticSO for slicetiming, then aa detects the slice acquisition scheme based on JSON and set the timings accordingly; which is more precise then the default slicetiming approach.
- aa main strength is that doing 10-20-100 participants does not take much longer than 1, as long as you have enough computing power

**Comment by TamerGezici** [comment]
Thanks. To clarify, using AA is definitely better for me. I needed an answer for those who were complaining about speed :) Indeed when you utilize parallel computing things will become incredibly fast. I have not been able to properly utilize this just yet.

> * I am not sure whether the settings for aa and the GUI were identical, i.e. you were doing the same thing. Also, if you use automaticSO for slicetiming, then aa detects the slice acquisition scheme based on JSON and set the timings accordingly; which is more precise then the default slicetiming approach.

Yes. Those were same. Slicetiming and realignment are just examples, overall using GUI is much faster. For all steps. 

For example, smoothing takes 2.5 minutes with GUI, 

```
------------------------------------------------------------------------
04-Jul-2022 20:07:26 - Running job #7
------------------------------------------------------------------------
04-Jul-2022 20:07:26 - Running 'Smooth'
04-Jul-2022 20:10:56 - Done    'Smooth'
```

Smoothing with AA takes around 5-10 minutes. So I wanted to check why is it slower, and if there is a way to speed things up (apart from using PCT)

**Comment by TamerGezici** [comment]
> * Also, if you use automaticSO for slicetiming, then aa detects the slice acquisition scheme based on JSON and set the timings accordingly; which is more precise then the default slicetiming approach.

I have defined slicetiming myself. My json headers are available in the script. If it is a better approach to use automaticSO I will definitely utilize this.

**Comment by tiborauer** [comment]
From where do you take your time estimates for aa?

For slicetiming: the automaticSO is more accurate than just using the sliceorder because it corrects for actual slice times and not just estimates based on TR and slice number. The difference may not be huge depending on the use case and the system. However, Siemens does not distribute slice acquisition equally within a TR, which the default (GUI-based) slicetiming assumes.

**Comment by TamerGezici** [comment]
> 
> For slicetiming: the automaticSO is more accurate than just using the sliceorder because it corrects for actual slice times and not just estimates based on TR and slice number. The difference may not be huge depending on the use case and the system. However, Siemens does not distribute slice acquisition equally within a TR, which the default (GUI-based) slicetiming assumes.

Thanks. I will use that then.

> From where do you take your time estimates for aa?

It is a rough guess of what I've experienced while running the scripts. 

However, I tend to also look at the console output in MATLAB. For example, I am running preprocessing for a single session single participant right now.

AA output:

```

SPM12: spm_realign (v7141)                         20:38:26 - 04/07/2022
========================================================================
Completed                               :          20:42:18 - 04/07/2022

SPM12: spm_reslice (v7141)                         20:42:18 - 04/07/2022
========================================================================
Completed                               :          20:44:37 - 04/07/2022
Working with session 1: 
 output stream epi  aamod_realign_00001 sub-01  written with 1 file(s)
Warning: Removing "C:\Program Files\MATLAB\spm12\external\fieldtrip\compat\matlablt2012a" from your path.
See http://www.fieldtriptoolbox.org/faq/should_i_add_fieldtrip_with_all_subdirectories_to_my_matlab_path/ 
 output stream realignment_parameter  aamod_realign_00001 sub-01  written with 1 file(s)
 output stream meanepi  sub-01  written with 1 file(s)
 output stream fd  aamod_realign_00001 sub-01  written with 1 file(s)
MODULE aamod_realign COMPLETED

	 	 	 Elapsed time = 0h:6m:15s
	 	 	 ...at = 20:44:41 (4/7/2022)
MODULE aamod_slicetiming PENDING: SPM slice timing for F:\fMRI\HCFprep\results\test_2\aamod_slicetiming_00001\sub-01\done_aamod_slicetiming_00001

MODULE aamod_slicetiming RUNNING: SPM slice timing for F:\fMRI\HCFprep\results\test_2\aamod_slicetiming_00001\sub-01
 retrieving stream epi from F:\fMRI\HCFprep\results\test_2\aamod_realign_00001\sub-01 to F:\fMRI\HCFprep\results\test_2\aamod_slicetiming_00001\sub-01
 retrieving stream epi from F:\fMRI\HCFprep\results\test_2\aamod_realign_00001\sub-01 to F:\fMRI\HCFprep\results\test_2\aamod_slicetiming_00001\sub-01
 retrieving stream epi_dicom_header from F:\fMRI\HCFprep\results\test_2\aamod_epifromnifti_00001\sub-01 to F:\fMRI\HCFprep\results\test_2\aamod_slicetiming_00001\sub-01
 executing

SPM12: spm_slice_timing (v6130)                    20:44:43 - 04/07/2022
========================================================================
Number of slices is...                  :                             32
Time to Repeat (TR) is...               :                              2
Parameters are specified as...          :                  slice indices
Completed                               :          20:45:40 - 04/07/2022
 output stream epi  aamod_slicetiming_00001 sub-01  written with 1 file(s)
 output stream sliceorder  aamod_slicetiming_00001 sub-01  written with 1 file(s)
MODULE aamod_slicetiming COMPLETED
```




GUI output:

```
------------------------------------------------------------------------
04-Jul-2022 19:38:47 - Running job #3
------------------------------------------------------------------------
04-Jul-2022 19:38:47 - Running 'Realign: Estimate & Reslice'

SPM12: spm_realign (v7141)                         19:38:47 - 04/07/2022
========================================================================
Warning: Removing "C:\Program Files\MATLAB\spm12\external\fieldtrip\compat\matlablt2010b" from your path.
See http://www.fieldtriptoolbox.org/faq/should_i_add_fieldtrip_with_all_subdirectories_to_my_matlab_path/ 
Warning: "C:\Program Files\MATLAB\spm12\external\fieldtrip\compat\matlablt2010b" not found in path. 
> In rmpath (line 71)
In isrow (line 35)
In setdiff>setdiffR2012a (line 202)
In setdiff (line 157)
In matlab.graphics.illustration.Legend.autoUpdateCallback
In print (line 36)
In spm_print (line 99)
In spm_realign>plot_parameters (line 527)
In spm_realign (line 168)
In spm_run_realign (line 31)
In cfg_run_cm (line 29)
In cfg_util>local_runcj (line 1717)
In cfg_util (line 972)
In cfg_ui>MenuFileRun_Callback (line 710)
In gui_mainfcn (line 95)
In cfg_ui (line 53) 
Printing 'Graphics' figure to:
  C:\Users\tamer\Desktop\study3\input\sub-01_out\spm_2022Jul04.ps
Completed                               :          19:39:43 - 04/07/2022

SPM12: spm_reslice (v7141)                         19:39:43 - 04/07/2022
========================================================================
Completed                               :          19:40:20 - 04/07/2022
04-Jul-2022 19:40:20 - Done    'Realign: Estimate & Reslice'
04-Jul-2022 19:40:20 - Done

------------------------------------------------------------------------
04-Jul-2022 19:41:31 - Running job #4
------------------------------------------------------------------------
04-Jul-2022 19:41:31 - Running 'Slice Timing'

SPM12: spm_slice_timing (v6130)                    19:41:31 - 04/07/2022
========================================================================
Number of slices is...                  :                             32
Time to Repeat (TR) is...               :                              2
Parameters are specified as...          :                  slice indices
Completed                               :          19:41:54 - 04/07/2022
04-Jul-2022 19:41:54 - Done    'Slice Timing'
04-Jul-2022 19:41:54 - Done

------------------------------------------------------------------------
04-Jul-2022 19:54:04 - Running job #5
------------------------------------------------------------------------
04-Jul-2022 19:54:04 - Running 'Coregister: Estimate & Reslice'

SPM12: spm_coreg (v7320)                           19:54:04 - 04/07/2022
========================================================================
Completed                               :          19:54:26 - 04/07/2022

SPM12: spm_reslice (v7141)                         19:54:26 - 04/07/2022
========================================================================
Completed                               :          19:54:27 - 04/07/2022
04-Jul-2022 19:54:27 - Done    'Coregister: Estimate & Reslice'
04-Jul-2022 19:54:27 - Done


```

**Comment by tiborauer** [comment]
Do you use 4D NIfTI (single file combining all 3d volumes for the session/run) for both cases?

**Comment by TamerGezici** [comment]
I ran both of these for a single session, DICOM imported image. I did DICOM import from SPM gui.

**Comment by tiborauer** [comment]
You can switch off 4D NIfTI by `aap.options.NIFTI4D = 0;`

**Comment by TamerGezici** [comment]
The ones I tested on SPM GUI were indeed 3D NIfTIs (it didn't occur to me that this would make a huge difference). And the ones I used with AA were 4D NIfTIs. I wasn't expecting it that to make much a huge difference. When we were comparing AA with SPM GUI I had a friend with me, he had suggested to use DICOM import because I didn't do much SPM GUI preprocessing before and he said he was unfamiliar with 4D NII's. So actually if we had used the same files, it would probably take the same time.

I will see if switching off 4D NIfTI makes any difference in terms of speed. Right now I am running it to check.

**Comment by TamerGezici** [comment]
Even though you switch off 3D NIfTI, running tsdiffana or reorienttomidle etc. generates output files as a single file. So at the upcoming steps, AA deals with single image files.

**Comment by tiborauer** [comment]
aa also uses SPM 's DICOM converter when starting from DICOMs

tsdiffana does not generate EPI output
reorienttomidle uses `spm_run_reorient`. It is possible that it also generates 4D NIfTI as default. I have not looked into it because I prefer 4D NIfTI anyway for the abovementioned reason.

TBH, I never paid attention to speed unless for real-time application.

**Comment by TamerGezici** [comment]
I agree. Speed also doesn't matter much for me. I will explain why this approach is better if anyone complains about speed.

**Comment by TamerGezici** [comment]
I figured out why 3D NIfTI's were converted back to 4D. They need to be 3D from the start. I was giving them as 4D and hoping that AA would expand them once and then move on from there. That wasn't the case.

Some lab members will analyze on their own personal computers. So speed of analysis is important for those people. I noticed that add_subject accepts 3D NIfTI so I decided to give it a try. And the analysis was pretty fast. To be fair I may also want to stick to using 3D. And it may be worth looking into why it takes so long for it to process 4D NIfTI.

However, I ran into one issue. I am adding subjects like this:

`aap = aas_addsubject(aap,subj,'functional',{func_files},'structural',{subject_data_anat});`

func_files is a single session cell array with 3D NIfTI images:

![image](https://user-images.githubusercontent.com/11014942/177410783-f6890842-fa5b-47a0-ab04-b92b4d50a06a.png)

The only issue here is that I am not sure if it is possible to provide the hdr in this setup. Is it possible? And if it is not, would it be straight forward for me to edit the code and put a PR so that hdr's can be given along with 3D files?

**Comment by TamerGezici** [comment]
Okay, nevermind! I think it works fine when you put the cell array of images inside a cell array like this and then in a struct:

```
    tmp_struct = struct('fname',{func_files},'hdr',fullfile(func_hdr.folder,func_hdr.name));
    aap = aas_addsubject(aap,subj,'functional',{tmp_struct},'structural',{subject_data_anat});
```

**Comment by TamerGezici** [comment]
Dear @tiborauer 

`autoDetectSO `does not work for me.

```
Error using spm_slice_timing (line 125)
Input is neither slice indices nor slice times.
```

I only need to specify the ref slice, right? 

Here's what my DICOM header looks like:

```
{
	"Modality": "MR",
	"MagneticFieldStrength": 3,
	"ImagingFrequency": 123.237,
	"Manufacturer": "Siemens",
	"ManufacturersModelName": "TrioTim",
	"InstitutionName": "UMRAM_AC6DEA_Ankara",
	"InstitutionalDepartmentName": "Department",
	"InstitutionAddress": "Street_StreetNo_City_District_TR_ZIP",
	"DeviceSerialNumber": "35397",
	"StationName": "MRC35397",
	"PatientPosition": "HFS",
	"ProcedureStepDescription": "AUSAF_TAMER",
	"SoftwareVersions": "syngo_MR_B17",
	"MRAcquisitionType": "2D",
	"SeriesDescription": "MoCoSeries",
	"ProtocolName": "session_1_MoCo",
	"ScanningSequence": "EP",
	"SequenceVariant": "SK_OSP",
	"ScanOptions": "FS",
	"SequenceName": "_epfid2d1_64",
	"ImageType": ["ORIGINAL", "PRIMARY", "M", "ND", "NORM", "MOCO", "MOSAIC"],
	"SeriesNumber": 4,
	"AcquisitionTime": "18:59:54.732500",
	"AcquisitionNumber": 1,
	"ImageComments": "Reference_volume_for_motion_correction.",
	"SliceThickness": 3,
	"SpacingBetweenSlices": 3.75,
	"SAR": 0.154153,
	"EchoTime": 0.03,
	"RepetitionTime": 2,
	"FlipAngle": 78,
	"PartialFourier": 1,
	"BaseResolution": 64,
	"ShimSetting": [
		-2176,
		8069,
		2036,
		594,
		71,
		-253,
		61,
		159	],
	"TxRefAmp": 313.201,
	"PhaseResolution": 1,
	"PhaseOversampling": 0.2,
	"VendorReportedEchoSpacing": 0.00053,
	"ReceiveCoilName": "32Ch_Head",
	"CoilString": "C:HEA;HEP",
	"PulseSequenceDetails": "%SiemensSeq%_ep2d_bold",
	"PercentPhaseFOV": 100,
	"PhaseEncodingSteps": 77,
	"AcquisitionMatrixPE": 64,
	"ReconMatrixPE": 64,
	"BandwidthPerPixelPhaseEncode": 49.008,
	"ParallelReductionFactorInPlane": 2,
	"EffectiveEchoSpacing": 0.000318826,
	"DerivedVendorReportedEchoSpacing": 0.000531376,
	"TotalReadoutTime": 0.020086,
	"PixelBandwidth": 2232,
	"DwellTime": 3.5e-06,
	"PhaseEncodingDirection": "j-",
	"SliceTiming": [
		0,
		-0.0625,
		-0.1275,
		-0.19,
		-0.2525,
		-0.315,
		-0.3775,
		-0.44,
		-0.5025,
		-0.565,
		-0.6275,
		-0.69,
		-0.7525,
		-0.8175,
		-0.88,
		-0.9425,
		-1.005,
		-1.0675,
		-1.13,
		-1.1925,
		-1.255,
		-1.3175,
		-1.38,
		-1.4425,
		-1.5075,
		-1.57,
		-1.6325,
		-1.695,
		-1.7575,
		-1.82,
		-1.8825,
		-1.945	],
	"ImageOrientationPatientDICOM": [
		0.999936,
		0.003331,
		0.0108182,
		4.70324e-09,
		0.955721,
		-0.294274	],
	"InPlanePhaseEncodingDirectionDICOM": "COL",
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20181125  (JP2:OpenJPEG) GCC9.3.0"
}
```

**Comment by tiborauer** [comment]
This is your unprocessed DICOM headers, however, epifromnifti extends it with further info: https://github.com/automaticanalysis/automaticanalysis/blob/6377d85ca5e89e769729065f981c27590e5457ec/aa_modules/aamod_epifromnifti.m#L71-L75
You should look at the .mat file in the session folder for the aamod_slicetiming stage.

For debugging, I suggest using `dbstop if error`, which halts the execution if an error arises. Then you can explore the variables (at various levels) and trace back the issue.

**Comment by tiborauer** [comment]
Sliecetimes MUST always be non-negative values because they represent the time relative to the acquisition time of the volume. Descending order does not mean you go back in time. :) Your slicetime should be like this:

1.9450 1.8825 1.8200 ... 0

Have you entered these slice times manually?

**Comment by TamerGezici** [comment]
Ah, I see. Sorry for my ignorance. 

I did not enter these slice times manually. Please check the DICOM header in` .json` format I shared above. The values are negative there too.

However, could it be that this is some sort of mess up due to dcm2niix? Because I looked at the DICOM header myself using pydicom and can't get to see any slicetiming field here. What is your suggestion?

```
Dataset.file_meta -------------------------------
(0002, 0000) File Meta Information Group Length  UL: 178
(0002, 0001) File Meta Information Version       OB: b'\x00\x01'
(0002, 0002) Media Storage SOP Class UID         UI: MR Image Storage
(0002, 0003) Media Storage SOP Instance UID      UI: 1.3.12.2.1107.5.2.32.35397.2022031310451445253727428
(0002, 0010) Transfer Syntax UID                 UI: Explicit VR Little Endian
(0002, 0012) Implementation Class UID            UI: 1.3.12.2.1107.5.2
(0002, 0013) Implementation Version Name         SH: 'MR_VB17A'
-------------------------------------------------
(0008, 0005) Specific Character Set              CS: 'ISO_IR 100'
(0008, 0008) Image Type                          CS: ['ORIGINAL', 'PRIMARY', 'M', 'ND', 'NORM', 'MOCO', 'MOSAIC']
(0008, 0012) Instance Creation Date              DA: '20220313'
(0008, 0013) Instance Creation Time              TM: '104514.640000'
(0008, 0016) SOP Class UID                       UI: MR Image Storage
(0008, 0018) SOP Instance UID                    UI: 1.3.12.2.1107.5.2.32.35397.2022031310451445253727428
(0008, 0020) Study Date                          DA: '20220313'
(0008, 0021) Series Date                         DA: '20220313'
(0008, 0022) Acquisition Date                    DA: '20220313'
(0008, 0023) Content Date                        DA: '20220313'
(0008, 0030) Study Time                          TM: '094638.109000'
(0008, 0031) Series Time                         TM: '104514.625000'
(0008, 0032) Acquisition Time                    TM: '104512.757500'
(0008, 0033) Content Time                        TM: '104514.640000'
(0008, 0050) Accession Number                    SH: ''
(0008, 0060) Modality                            CS: 'MR'
(0008, 0070) Manufacturer                        LO: 'SIEMENS'
(0008, 0080) Institution Name                    LO: 'UMRAM //AC6DEA//Ankara'
(0008, 0081) Institution Address                 ST: 'Street StreetNo,City,District,TR,ZIP'
(0008, 0090) Referring Physician's Name          PN: ''
(0008, 1010) Station Name                        SH: 'MRC35397'
(0008, 1030) Study Description                   LO: 'AUSAF^TAMER'
(0008, 103e) Series Description                  LO: 'MoCoSeries'
(0008, 1040) Institutional Department Name       LO: 'Department'
(0008, 1050) Performing Physician's Name         PN: ''
(0008, 1070) Operators' Name                     PN: 'TAMER'
(0008, 1090) Manufacturer's Model Name           LO: 'TrioTim'
(0008, 1140)  Referenced Image Sequence  3 item(s) ---- 
   (0008, 1150) Referenced SOP Class UID            UI: MR Image Storage
   (0008, 1155) Referenced SOP Instance UID         UI: 1.3.12.2.1107.5.2.32.35397.2022031310421845285726727
   ---------
   (0008, 1150) Referenced SOP Class UID            UI: MR Image Storage
   (0008, 1155) Referenced SOP Instance UID         UI: 1.3.12.2.1107.5.2.32.35397.2022031310353917871125980
   ---------
   (0008, 1150) Referenced SOP Class UID            UI: MR Image Storage
   (0008, 1155) Referenced SOP Instance UID         UI: 1.3.12.2.1107.5.2.32.35397.2022031310353520917225976
   ---------
(0010, 0010) Patient's Name                      PN: 'sub19_UMTA'
(0010, 0020) Patient ID                          LO: '22.03.13-09:46:22-DST-1.3.12.2.1107.5.2.32.35397'
(0010, 0030) Patient's Birth Date                DA: '19970313'
(0010, 0040) Patient's Sex                       CS: 'M'
(0010, 1010) Patient's Age                       AS: '025Y'
(0010, 1030) Patient's Weight                    DS: '63.0'
(0018, 0020) Scanning Sequence                   CS: 'EP'
(0018, 0021) Sequence Variant                    CS: ['SK', 'OSP']
(0018, 0022) Scan Options                        CS: 'FS'
(0018, 0023) MR Acquisition Type                 CS: '2D'
(0018, 0024) Sequence Name                       SH: '*epfid2d1_64'
(0018, 0025) Angio Flag                          CS: 'N'
(0018, 0050) Slice Thickness                     DS: '3.0'
(0018, 0080) Repetition Time                     DS: '2000.0'
(0018, 0081) Echo Time                           DS: '30.0'
(0018, 0083) Number of Averages                  DS: '1.0'
(0018, 0084) Imaging Frequency                   DS: '123.237753'
(0018, 0085) Imaged Nucleus                      SH: '1H'
(0018, 0086) Echo Number(s)                      IS: '1'
(0018, 0087) Magnetic Field Strength             DS: '3.0'
(0018, 0088) Spacing Between Slices              DS: '3.7500001324836'
(0018, 0089) Number of Phase Encoding Steps      IS: '77'
(0018, 0091) Echo Train Length                   IS: '1'
(0018, 0093) Percent Sampling                    DS: '100.0'
(0018, 0094) Percent Phase Field of View         DS: '100.0'
(0018, 0095) Pixel Bandwidth                     DS: '2232.0'
(0018, 1000) Device Serial Number                LO: '35397'
(0018, 1020) Software Versions                   LO: 'syngo MR B17'
(0018, 1030) Protocol Name                       LO: 'session_1'
(0018, 1251) Transmit Coil Name                  SH: 'Body'
(0018, 1310) Acquisition Matrix                  US: [64, 0, 0, 64]
(0018, 1312) In-plane Phase Encoding Direction   CS: 'COL'
(0018, 1314) Flip Angle                          DS: '78.0'
(0018, 1315) Variable Flip Angle Flag            CS: 'N'
(0018, 1316) SAR                                 DS: '0.15095239380566'
(0018, 1318) dB/dt                               DS: '0.0'
(0018, 5100) Patient Position                    CS: 'HFS'
(0019, 0010) Private Creator                     LO: 'SIEMENS MR HEADER'
(0019, 1008) [CSA Image Header Type]             CS: 'IMAGE NUM 4'
(0019, 1009) [CSA Image Header Version ??]       LO: '1.0'
(0019, 100a) [NumberOfImagesInMosaic]            US: 32
(0019, 100b) [SliceMeasurementDuration]          DS: '20.0'
(0019, 100f) [GradientMode]                      SH: 'Fast*'
(0019, 1011) [FlowCompensation]                  SH: 'No'
(0019, 1012) [TablePositionOrigin]               SL: [0, 0, -1297]
(0019, 1013) [ImaAbsTablePosition]               SL: [0, 0, -1297]
(0019, 1014) [ImaRelTablePosition]               IS: [0, 0, 0]
(0019, 1015) [SlicePosition_PCS]                 FD: [-572.98795176, -585.60268331, 16.89462894]
(0019, 1016) [TimeAfterStart]                    DS: '1.945'
(0019, 1017) [SliceResolution]                   DS: '1.0'
(0019, 1018) [RealDwellTime]                     IS: '3500'
(0019, 1025) [RBMoCoTrans]                       FD: [0.0, 0.0, 0.0]
(0019, 1026) [RBMoCoRot]                         FD: [0.0, 0.0, 0.0]
(0019, 1028) [BandwidthPerPixelPhaseEncode]      FD: 49.008
(0019, 1029) [MosaicRefAcqTimes]                 FD: Array of 32 elements
(0020, 000d) Study Instance UID                  UI: 1.3.12.2.1107.5.2.32.35397.30000022030109185845300000112
(0020, 000e) Series Instance UID                 UI: 1.3.12.2.1107.5.2.32.35397.2022031310450158025127215.0.0.0
(0020, 0010) Study ID                            SH: '1'
(0020, 0011) Series Number                       IS: '4'
(0020, 0012) Acquisition Number                  IS: '1'
(0020, 0013) Instance Number                     IS: '1'
(0020, 0032) Image Position (Patient)            DS: [-572.98795175552, -585.60268330637, 16.894628938962]
(0020, 0037) Image Orientation (Patient)         DS: [1, -1e-016, 0, 1e-016, 0.99780146819131, -0.0662739019167]
(0020, 0052) Frame of Reference UID              UI: 1.3.12.2.1107.5.2.32.35397.1.20220313103348171.0.0.0
(0020, 1040) Position Reference Indicator        LO: ''
(0020, 1041) Slice Location                      DS: '-21.952689235765'
(0020, 4000) Image Comments                      LT: Array of 39 elements
(0028, 0002) Samples per Pixel                   US: 1
(0028, 0004) Photometric Interpretation          CS: 'MONOCHROME2'
(0028, 0010) Rows                                US: 384
(0028, 0011) Columns                             US: 384
(0028, 0030) Pixel Spacing                       DS: [3, 3]
(0028, 0100) Bits Allocated                      US: 16
(0028, 0101) Bits Stored                         US: 12
(0028, 0102) High Bit                            US: 11
(0028, 0103) Pixel Representation                US: 0
(0028, 0106) Smallest Image Pixel Value          US: 0
(0028, 0107) Largest Image Pixel Value           US: 1454
(0028, 1050) Window Center                       DS: '610.0'
(0028, 1051) Window Width                        DS: '1264.0'
(0028, 1055) Window Center & Width Explanation   LO: 'Algo1'
(0029, 0010) Private Creator                     LO: 'SIEMENS CSA HEADER'
(0029, 0011) Private Creator                     LO: 'SIEMENS MEDCOM HEADER2'
(0029, 1008) [CSA Image Header Type]             CS: 'IMAGE NUM 4'
(0029, 1009) [CSA Image Header Version]          LO: '20220313'
(0029, 1010) [CSA Image Header Info]             OB: Array of 11152 elements
(0029, 1018) [CSA Series Header Type]            CS: 'MR'
(0029, 1019) [CSA Series Header Version]         LO: '20220313'
(0029, 1020) [CSA Series Header Info]            OB: Array of 89332 elements
(0029, 1160) [Series Workflow Status]            LO: 'com'
(0032, 1060) Requested Procedure Description     LO: 'AUSAF TAMER'
(0040, 0244) Performed Procedure Step Start Date DA: '20220313'
(0040, 0245) Performed Procedure Step Start Time TM: '094638.171000'
(0040, 0253) Performed Procedure Step ID         SH: 'MR20220313094638'
(0040, 0254) Performed Procedure Step Descriptio LO: 'AUSAF^TAMER'
(0051, 0010) Private Creator                     LO: 'SIEMENS MR HEADER'
(0051, 1008) [CSA Image Header Type]             CS: 'IMAGE NUM 4'
(0051, 1009) [CSA Image Header Version ??]       LO: '1.0'
(0051, 100a) [Unknown]                           LO: 'TA 00.02'
(0051, 100b) [AcquisitionMatrixText]             LO: '64*64'
(0051, 100c) [Unknown]                           LO: 'FoV 1152*1152'
(0051, 100e) [Unknown]                           LO: 'Tra>Cor(-3.8)'
(0051, 100f) [CoilString]                        LO: 'C:HEA;HEP'
(0051, 1011) [PATModeText]                       LO: 'p2'
(0051, 1012) [Unknown]                           SH: 'TP 0'
(0051, 1013) [PositivePCSDirections]             SH: '+LPH'
(0051, 1016) [Unknown]                           LO: 'p2 M/ND/NORM/MOCO/MOSAIC'
(0051, 1017) [Unknown]                           SH: 'SL 3.0'
(0051, 1019) [Unknown]                           LO: 'A1/FS'
(7fe0, 0010) Pixel Data                          OW: Array of 294912 elements
```

**Comment by TamerGezici** [comment]
Looks like this could indeed be a dmc2niix issue. I will check with them.

**Comment by TamerGezici** [comment]
The issue was due to Siemens', which messes up slice orders. dcm2niix fixes this, but only in newer versions. I solved this issue by updating dcm2niix.
