### ISSUE TITLE
Fieldmap echo time error.

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#341]
Hi again, I am running into this error:

```
WARNING: Error during retrieving Fieldmap Echo Times: Reference to non-existent field 'volumeTE'.
WARNING: Manual settings are used:   ms and 

**** automatic analysis failed - see reason and line numbers below
ERROR: No value is specified
for help, see the aa wiki
Error using aas_log (line 67)
aa error:
see above (or set aap.options.verbose)


Error in aamod_fieldmap2VDM (line 89)
                if isempty(job.defaults.defaultsval.et), aas_log(aap,true,'ERROR: No value is specified'); end

Error in aa_feval (line 15)
    [varargout{:}]=feval(funcname,varargin{:});

Error in aa_feval_withindices (line 4)
[aap,resp]=aa_feval(mfile_alias,aap,task,ci{:});

Error in aa_doprocessing_onetask (line 191)
            [aap,~]=aa_feval_withindices(mfile_alias,aap,task,indices);

Error in aaq_localsingle/runall (line 15)
                aa_doprocessing_onetask(obj.aap,job.task,job.k,job.indices);

Error in aa_doprocessing (line 361)
            taskqueue.runall(dontcloseexistingworkers, false);

Error in HCF_analysis_fieldmap_B (line 151)
aa_doprocessing(aap);
 
67          error('aa:internal','aa error:\n%s\n','see above (or set aap.options.verbose)')
```

I checked the headers.

The fieldmap_dicom_header.mat file contents (inside fieldmap2VDM folder)

I'm not sure if the echo time value here is correct, considering it is different than the one in the DICOM .json header.

```
    AcquisitionTime: [1×14 double]
           EchoTime: 5.1900
     RepetitionTime: 400
          DwellTime: 0.0300
           volumeTR: 0.4000
```

Echo time inside the .json header of magnitude1 file is different:

```
{
	"Modality": "MR",
	"MagneticFieldStrength": 3,
	"ImagingFrequency": 123.24,
	"Manufacturer": "Siemens",
	"ManufacturersModelName": "TrioTim",
	"InstitutionName": "UMRAM //AC6DEA//Ankara",
	"InstitutionalDepartmentName": "Department",
	"InstitutionAddress": "Street StreetNo,City,District,TR,ZIP",
	"DeviceSerialNumber": "35397",
	"StationName": "MRC35397",
	"PatientPosition": "HFS",
	"ProcedureStepDescription": "AUSAF^TAMER",
	"SoftwareVersions": "syngo MR B17",
	"MRAcquisitionType": "2D",
	"SeriesDescription": "gre_field_mapping",
	"ProtocolName": "gre_field_mapping",
	"ScanningSequence": "GR",
	"SequenceVariant": "SP",
	"SequenceName": "*fm2d2r",
	"ImageType": ["ORIGINAL", "PRIMARY", "M", "ND"],
	"SeriesNumber": 9,
	"AcquisitionTime": "14:52:23.950000",
	"AcquisitionNumber": 1,
	"SliceThickness": 3,
	"SpacingBetweenSlices": 3.75,
	"SAR": 0.187417,
	"EchoNumber": 1,
	"EchoTime": 0.00519,
	"RepetitionTime": 0.4,
	"FlipAngle": 60,
	"PartialFourier": 1,
	"BaseResolution": 64,
	"ShimSetting": [
		-2158,
		8266,
		2000,
		1095,
		115,
		113,
		308,
		155	],
	"TxRefAmp": 272.968,
	"PhaseResolution": 1,
	"ReceiveCoilName": "32Ch_Head",
	"CoilString": "C:HEA;HEP",
	"PulseSequenceDetails": "%SiemensSeq%\\gre_field_mapping",
	"CoilCombinationMethod": "Adaptive Combine",
	"MatrixCoilMode": "SENSE",
	"PercentPhaseFOV": 100,
	"PercentSampling": 100,
	"PhaseEncodingSteps": 64,
	"AcquisitionMatrixPE": 64,
	"ReconMatrixPE": 64,
	"PixelBandwidth": 260,
	"DwellTime": 3e-05,
	"PhaseEncodingDirection": "j-",
	"SliceTiming": [
		0.20313,
		0,
		0.21875,
		0.01563,
		0.21875,
		0.03125,
		0.23438,
		0.03125,
		0.25,
		0.04688,
		0.26563,
		0.0625,
		0.28125,
		0.07813,
		0.29688,
		0.09375,
		0.29688,
		0.09375,
		0.3125,
		0.10938,
		0.32813,
		0.125,
		0.34375,
		0.14063,
		0.35938,
		0.15625,
		0.35938,
		0.15625,
		0.375,
		0.17188,
		0.39063,
		0.1875	],
	"ImageOrientationPatientDICOM": [
		1,
		2e-16,
		0,
		-2e-16,
		0.964557,
		-0.263873	],
	"ImageOrientationText": "Tra>Cor(-15.3)",
	"InPlanePhaseEncodingDirectionDICOM": "COL",
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20211006"
}
```

**Comment by TamerGezici** [comment]
And also, this is how the fieldmap resides in the aap structure:

![image](https://user-images.githubusercontent.com/11014942/182440863-f5a3938b-07f9-46ea-9ceb-f6a87467b03f.png)

fname field contents:

`'E:\fMRI\fr-pr-3-AA\fmri_raw_bids\bids_3D\sub-31\ses-1\fmap\sub-31_ses-1_run-1_magnitude1.nii'	'E:\fMRI\fr-pr-3-AA\fmri_raw_bids\bids_3D\sub-31\ses-1\fmap\sub-31_ses-1_run-1_magnitude2.nii'	'E:\fMRI\fr-pr-3-AA\fmri_raw_bids\bids_3D\sub-31\ses-1\fmap\sub-31_ses-1_run-1_phasediff.nii'`

**Comment by tiborauer** [comment]
It seems you have the ["Phase-difference map and at least one magnitude image" use case](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-1-phase-difference-map-and-at-least-one-magnitude-image), however, your JSON header does not correspond to it, as it should have `EchoTime1` and `EchoTime2` instead of `EchoTime`. `aamod_fieldmapfromnifti` also expects them:
https://github.com/automaticanalysis/automaticanalysis/blob/331702ec9c23307c44012ad2b12b9cf735b36c17/aa_modules/aamod_fieldmapfromnifti.m#L74

**Comment by TamerGezici** [comment]
I see. Let me check the dicom header myself, and perhaps ask about this to dcm2niix developer team.

**Comment by TamerGezici** [comment]
Figured. So, when you do dcm2niix conversion EchoTime1 and Echotime2 are written to the phasediff image not to the magnitude images, so that .json needs to be given as the header.

`subject_data_fmap = struct('fname',{fmaps},'hdr',{fmap_hdrs{3}},'session','*'); `

Where `fmaps `are a cell array with path to each file, and `fmap_hdrs{3}` is the path to the phasediff header, and that is the only header which needs to be provided. Yes, this line https://github.com/automaticanalysis/automaticanalysis/blob/e653871cc9815fdeeadb96246ffc31abd7bf670c/aa_engine/aas_addsubject.m#L66

does explain how it's needed to be provided, but it doesnt specifically say that the hdr need to be the phasediff, so I was giving all headers and hoping AA would manage, but it looks like it only needs one header and that is the phasediff image.

**Comment by TamerGezici** [comment]
I have another question in relation to this. 

Recently started collecting _successful_ fieldmaps. Previously, our protocol was incorrect and was not saving any magnitude images. I fixed the error on our protocol and now scanned new subjects with the proper protocol.  I guess I can not use those subjects for analysis at all.

How do I analyze subjects which have fieldmaps, and those who do not at the same pipeline? Considering there are new modules now, such as the nifti converter, the voxel displacement map module and the realignunwarp module, how can I have a single script and analysis recipe and analyze subjects who have fieldmaps and those who don't at the same analysis?

**Comment by tiborauer** [comment]
Regarding the header: According to [the BIDS specification](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-1-phase-difference-map-and-at-least-one-magnitude-image), only the magnitude image with the shorter TE is required, while the other magnitude is optional. Therefore, only the phasediff header is complete with both TEs. That is why aa assumes phasediff header. We can perhaps make it explicit in `aas_addsubject`. 

I advise against combining data processed with and without fieldmaps. Therefore, such a use case is not (directly supported) in aa. Your best bet is to ignore fieldmaps altogether if you want to analyse all data.
If you still want to combine heterogenous data, you need three scripts:
- preprocessing data with fieldmaps
- preprocessing data without fieldmaps
- analysing preprocessed data connecting to both preprocessed workflows

**Comment by TamerGezici** [comment]
Thanks for your answers. 

> I advise against combining data processed with and without fieldmaps.

Is there any specific reason? Is there something I should becareful about?

**Comment by tiborauer** [comment]
If you process data differently, you cannot expect them to reflect the same process with the same sensitivity and specificity. Using fieldmaps changes intensity, noise level and deformations.

One way to combine these data is to add an additional (set of) nuisance/confounding regressor(s) on the group level to model the different data processing.

**Comment by TamerGezici** [comment]
> If you process data differently, you cannot expect them to reflect the same process with the same sensitivity and specificity. Using fieldmaps changes intensity, noise level and deformations.
> 
> One way to combine these data is to add an additional (set of) nuisance/confounding regressor(s) on the group level to model the different data processing.

Oh yes, indeed. I was also concerned about this. I wasn't sure if I should move on with processing fieldmaps or leave it completely for another study which we can start collecting them properly from the beginning for all participants.

Unfortunately our previous participants do not have magnitude images. Do you know if there is such a use case for fieldmaps with only a phasedifference file? I think fieldmaps are not useful without magnitude images, but I want to check just to be sure.

**Comment by tiborauer** [comment]
No, you cannot use phasediff only, because you cannot register it to the EPI without the magnitude image.
