### ISSUE TITLE
TDT usage example

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#344]
Hi,

Are there any example scripts or tutorials on the usage of TDT with AA? I am interested in doing ROI based and searchlight analysis.

Any script would do the job for me. I think I can figure it out as long as I have some reference to work with.

Thanks a lot.

**Comment by tiborauer** [comment]
Hi,

Thank you for asking!

The TDT pipeline is still in development. A major update is about to arrive soon. I am using it in my current project and I will disseminate the workflow with the project.

I keep you updated.

**Comment by TamerGezici** [comment]
Sure. Thanks I'll be waiting. I wish you good luck with the development.
