### ISSUE TITLE
FIR analysis - specifying a seperate BF for each event seperately.

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#349]
Hello,

We want to specify a BF in our first level model seperately for each event type, for example event 1 can be HRF and event 2 can be FIR so on and so forth. How can I achieve this?

Thanks.

**Comment by tiborauer** [comment]
I am not even sure whether/how it is possible in SPM. You can specify custom BF using the [aas_get_custom_BF](https://github.com/automaticanalysis/automaticanalysis/blob/master/aa_engine/aas_get_custom_BF.m). Please, also look at https://github.com/automaticanalysis/automaticanalysis/blob/ea3ef2f015510aa8e9cd9dbe2255240a91d3adff/aa_engine/aas_firstlevel_model_prepare.m#L181-L193
You have to specufy `aap.tasksettings.aamod_firstlevel_model.xBF.name` accordingly.

**Comment by TamerGezici** [comment]
Yes, indeed. This modifies the BF for all of the model though. We were curious if it's possible to specify for each event seperately. Apparently, Rhodri wrote a script which does exactly this for Ausaf back then. It is possible in SPM but requires some modifications/a custom written SPM function. I will use that instead.

And if I can manage, I may add this as a feature for AA if you want. I'll first need to see what the script does.
