### ISSUE TITLE
Utilizing aamod_compSignal

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#350]
Hi,

I am interested in utilizing this module. In one study we have a tactile task which the participant does by running their fingers across plexiglass which has raised shapes on it. Running your hand/finger across a plexiglass causes limb movement. So I'm guessing this module could be useful for this.

The module says  https://github.com/automaticanalysis/automaticanalysis/blob/ea3ef2f015510aa8e9cd9dbe2255240a91d3adff/aa_modules/aamod_compSignal.m#L3

`aamod_mask_fromsegment  `needs to be ran to do this. This module receives "segmasks" as inputs

However, there is no such module. Closest is `aamod_mask_segment` which provides "segmasks". However, this module requires grey, white, csf inputs. And the regular segmentation (and other segmentation versions I've checked) does not verbatim provide those. They provide "native" versions of those.

My module header is like this:

```
<?xml version="1.0" encoding="utf-8"?>
<aap>
    <tasklist>
        
        <initialisation>	
            <module><name>aamod_study_init</name></module>
        </initialisation>
		
        <main>                    
        <module><name>aamod_structuralfromnifti</name></module>
        <module><name>aamod_epifromnifti</name></module>
        <module><name>aamod_segment_structural</name></module>
        <module><name>aamod_mask_segment</name></module>
        <module><name>aamod_compSignal</name></module>        
        </main>
    </tasklist>
</aap>
```

Error:

```
**** automatic analysis failed - see reason and line numbers below
Stage aamod_mask_segment required input grey is not an output of any stage it is dependent on. You might need to add an aas_addinitialstream command or get the stream from a remote source.
for help, see the aa wiki
```

**Comment by tiborauer** [comment]
`aamod_mask_segment` is a generic module with renameable streams. You should specify the corresponding stream (native or normalised_*) depending on the space of your data.

You can specify the streams by using `aas_renamestream`. E.g.:
`aap = aas_renamestream(aap,aamod_mask_segment_00001,'grey','native_grey','input');`

Also, I recommend using `aamod_segment8` rather than `aamod_segment_structural`. It is based on unified segment and normalise introduced in SPM8.

**Comment by TamerGezici** [comment]
I see! Thank you for your prompt response, and your tip regarding segment. I will change my task list accordingly.

Will compSignal be incorporated as a regressor without any additional modifications? Or do I need to specify something? 

https://github.com/automaticanalysis/automaticanalysis/blob/ea3ef2f015510aa8e9cd9dbe2255240a91d3adff/aa_modules/aamod_firstlevel_model.xml#L99

**Comment by tiborauer** [comment]
If compSignal is present, then it included automatically.

**Comment by TamerGezici** [comment]
Thanks! Take care.

**Comment by TamerGezici** [comment]
Speaking of segment8, would it be better to use the multichannel version of this since we are using a 32 channel head coil as well? @tiborauer

**Comment by tiborauer** [comment]
No. The "multichannel" refers to multimodal (T1+T2) segmentation.

**Comment by TamerGezici** [comment]
> Speaking of segment8, would it be better to use the multichannel version of this since we are using a 32 channel head coil as well? @tiborauer

Thanks.

**Comment by tiborauer** [comment]
This is a value of your choice. The segmented images will be resliced to this voxel size.

**Comment by TamerGezici** [comment]
Can you please help me? I tried compSignal and ran into an error:

```
MODULE aamod_compSignal PENDING: Get signal from the CSF, WM, GM and OOB (if epiBETmask exists) compartments for E:\fMRI\fr-pr-3-AA\HCFprep\module_test\module_test_compsignal2\aamod_compSignal_00001\sub-19\discrB_run-01\done_aamod_compSignal_00001

MODULE aamod_compSignal RUNNING: Get signal from the CSF, WM, GM and OOB (if epiBETmask exists) compartments for E:\fMRI\fr-pr-3-AA\HCFprep\module_test\module_test_compsignal2\aamod_compSignal_00001\sub-19\discrB_run-01
Loaded datecheck was 1cqSvozYeq+7hTJMJz0G5w== and calc 1cqSvozYeq+7hTJMJz0G5w==
Loaded datecheck was +ENW6W77x6NLokOUfJJuEQ== and calc +ENW6W77x6NLokOUfJJuEQ==
 retrieve stream epi [checksum match, not recopied] from E:MRIr-pr-3-AA retrieve stream segmasks [checksum match, not recopied] from E:MRIr-pr-3-AA executing
Load stream from file E:\fMRI\fr-pr-3-AA\HCFprep\module_test\module_test_compsignal2\aamod_compSignal_00001\sub-19\discrB_run-01\stream_epi_inputto_aamod_compSignal_00001.txt...
Load stream from file E:\fMRI\fr-pr-3-AA\HCFprep\module_test\module_test_compsignal2\aamod_compSignal_00001\sub-19\stream_segmasks_inputto_aamod_compSignal_00001.txt...
Removing White Matter voxels near Gray Matter
Grey Matter mask comprises 685692 (685692) voxels
White Matter mask comprises 264608 (441075) voxels
CereberoSpinal Fluid mask comprises 195306 (195306) voxels
The logical indices contain a true value outside of the array bounds.

Error in aamod_compSignal (line 128)
            compTC(e,1) = mean(Y(mGM>0));

Error in aa_feval (line 15)
    [varargout{:}]=feval(funcname,varargin{:});

Error in aa_feval_withindices (line 4)
[aap,resp]=aa_feval(mfile_alias,aap,task,ci{:});

Error in aa_doprocessing_onetask (line 191)
            [aap,~]=aa_feval_withindices(mfile_alias,aap,task,indices);

Error in aaq_localsingle/runall (line 15)
                aa_doprocessing_onetask(obj.aap,job.task,job.k,job.indices);

Error in aa_doprocessing (line 361)
            taskqueue.runall(dontcloseexistingworkers, false);

Error in module_test (line 64)
aa_doprocessing(aap);
```

XML:
```

<?xml version="1.0" encoding="utf-8"?>
<aap>
    <tasklist>
        
        <initialisation>	
            <module><name>aamod_study_init</name></module>
        </initialisation>
		
        <main>                    
        <module><name>aamod_structuralfromnifti</name></module>
        <module><name>aamod_epifromnifti</name></module>
        <module><name>aamod_segment8</name>
            <extraparameters>
                <aap><tasklist><currenttask><settings>
                    <samp>3</samp>
                </settings></currenttask></tasklist></aap>
            </extraparameters>
        </module>
        <module><name>aamod_mask_segment</name></module>
        <module><name>aamod_compSignal</name></module>        
        </main>
    </tasklist>
</aap>

```

**Comment by tiborauer** [comment]
What is you input to aamod_mask_segment?

**Comment by TamerGezici** [comment]
> What is you input to aamod_mask_segment?

```
aap = aas_renamestream(aap,'aamod_mask_segment_00001','grey','native_grey','input');
aap = aas_renamestream(aap,'aamod_mask_segment_00001','white','native_white','input');
aap = aas_renamestream(aap,'aamod_mask_segment_00001','csf','native_csf','input');
```

**Comment by tiborauer** [comment]
Have you checked the images (aamod_coreg_extended outputs) if they are aligned?

**Comment by tiborauer** [comment]
I am not sure I understand. I thought the images are native, i.e., not normalised. Here, however, they all (T1 and EPI) seem aligned with the MNI template.

**Comment by TamerGezici** [comment]
I have no idea. The images above are diagnostic outputs of coreg_extended. I didnt do any normalization. I am not with my computer now but I can check whatever you would ask for to make sure we are on the same page

**Comment by tiborauer** [comment]
Just check with the raw T1 and fMRI data, whether they are aligned with MNI.

**Comment by TamerGezici** [comment]
![image](https://user-images.githubusercontent.com/11014942/193025901-b39b337b-bb92-44ad-90ba-15c33457c85c.png)

![image](https://user-images.githubusercontent.com/11014942/193026077-ef409797-b841-442c-85dd-4a323a15f719.png)

These are the raw data inputs which I am giving to AA.

**Comment by TamerGezici** [comment]
I went on MRICROGL and opened the standard MNI template, and added the EPI image as an overlay:

![image](https://user-images.githubusercontent.com/11014942/193026446-8969db00-b864-49c7-bdd8-704f0315a115.png)

**Comment by TamerGezici** [comment]
And this is what it looks like when it's normalized.

![image](https://user-images.githubusercontent.com/11014942/193026743-a12f9f2b-18d3-480f-8472-a8ea91c26adf.png)

**Comment by tiborauer** [comment]
Where is the EPI normalisation in your pipeline?

**Comment by TamerGezici** [comment]
I may have misunderstood correctly, but I am assuming you are referring to my last image and asking for my tasklist. Here's the tasklist.

Do note I have not moved onto segment8 just yet, this is an old analysis of mine. The last picture I posted was generated from the pipeline I share below.

```
<?xml version="1.0" encoding="utf-8"?>
<aap>
    <tasklist>
        
        <initialisation>	
            <module><name>aamod_study_init</name></module>
        </initialisation>
		
        <main>                    
        <!-- preprocessing -->
        <module><name>aamod_structuralfromnifti</name></module>
        <module><name>aamod_epifromnifti</name></module>
        <module><name>aamod_tsdiffana</name></module>
        <module><name>aamod_realign</name></module> 
        <module><name>aamod_slicetiming</name>
            <extraparameters>
                <aap><tasklist><currenttask><settings>
                    <autodetectSO>1</autodetectSO>
                    <refslice>16</refslice>
                </settings></currenttask></tasklist></aap>
            </extraparameters>
        </module>
        <module><name>aamod_coreg_extended</name></module>
        <module><name>aamod_biascorrect_structural</name></module>
        <module><name>aamod_segment_structural</name></module>
        <module><name>aamod_norm_write_epi</name></module>
        <module><name>aamod_smooth</name>
            <extraparameters>
                <aap><tasklist><currenttask><settings>
                    <FWHM>8</FWHM>
                </settings></currenttask></tasklist></aap>
            </extraparameters>
        </module>
        <!-- first-level model -->
        <module><name>aamod_firstlevel_model</name>
            <extraparameters>
                <aap><tasklist><currenttask><settings>
                <includemovementpars>1</includemovementpars>
                    <xBF>
                        <UNITS>secs</UNITS>
                        <name>hrf</name>
                    </xBF>
                </settings></currenttask></tasklist></aap>
            </extraparameters>
        </module>
        <module><name>aamod_firstlevel_contrasts</name></module> 
        <!-- second-level model -->
        <module><name>aamod_secondlevel_model</name></module>	
        <module><name>aamod_secondlevel_contrasts</name></module>
        </main>
    </tasklist>
</aap>
```

**Comment by tiborauer** [comment]
OK. So the aamod_coreg_extended is working. Can you just check the inputs of the aamod_compSignal, i.e., the images within the module?

BTW, can you use debug mode (dbstop if error) to stop the execution at the error? Then show:
```matlab
size(Y))
size(mGM)
```

**Comment by TamerGezici** [comment]
There is a structurals folder:

![image](https://user-images.githubusercontent.com/11014942/193055020-0df34ebb-fb64-4e55-9b5b-dac9dd871efe.png)

The session folder contains only realigned (rsub-) files, stream_epi_inputto_aamod_compSignal_00001.txt and aap_parameters_aamod_compSignal_00001.mat

```
K>> size(Y)

ans =

    64    64    32

K>> size(mGM)

ans =

   176   224   256
```

**Comment by TamerGezici** [comment]
> Where is the EPI normalisation in your pipeline?

I understood correctly, right? Just to clarify:

- I initially showed you how my raw data is overlayed on MNI template.
- Then I showed you what it looks like when it's normalized from a different pipeline. This pipeline is seperate from my compSignal pipeline. 

The compSignal pipeline, which I shared earlier above, does not have normalization.

**Comment by tiborauer** [comment]
I think I know what the issue is. Even though your images are coregesitered, they are not resliced, which means they are aligned but with their original non-matching resolution.
Instead of coreg_extended, you should use the coreg_general module, which reslice the images by default (`doReslice=1`). I suggest adding it after mask_segment, so all the structural processing takes advantage of the higher resolution of T1. Since it is a generic module, you need to specify the inputs (the outputs will be automatically renamed):

```matlab
aap = aas_renamestream(aap,'aamod_coreg_general_00001','reference','meanepi','input');
aap = aas_renamestream(aap,'aamod_coreg_general_00001','input','grey_mask','input');
aap = aas_renamestream(aap,'aamod_coreg_general_00001','append','white_mask','input');
aap = aas_renamestream(aap,'aamod_coreg_general_00001','append','csf_mask','input');
aap.tasksettings.aamod_coreg_general.roptions.interp = 0;
```
The last line ensures no interpolation is done, which is essential when you reslice masks.

Make sure you check the output and change `eoptions.cost_fun` if needed.

**Comment by TamerGezici** [comment]
I see. So I modified my tasklist to this:

```
<?xml version="1.0" encoding="utf-8"?>
<aap>
    <tasklist>
        
        <initialisation>	
            <module><name>aamod_study_init</name></module>
        </initialisation>
        <main>                    
            <module><name>aamod_structuralfromnifti</name></module>
            <module><name>aamod_epifromnifti</name></module>
            <module><name>aamod_realign</name></module> 
            <module><name>aamod_slicetiming</name>
                <extraparameters>
                    <aap><tasklist><currenttask><settings>
                        <autodetectSO>1</autodetectSO>
                        <refslice>16</refslice>
                    </settings></currenttask></tasklist></aap>
                </extraparameters>
            </module>
            <module><name>aamod_segment8</name>
                <extraparameters>
                    <aap><tasklist><currenttask><settings>
                        <samp>3</samp>
                    </settings></currenttask></tasklist></aap>
                </extraparameters>
            </module>
            <module><name>aamod_mask_segment</name></module>
            <module><name>aamod_coreg_general</name></module>
            <module><name>aamod_compSignal</name></module>        
        </main>
    </tasklist>
</aap>
```

And I have these streams renamed. Since mask segment receives from segment8 I thought it should remain as it is. I checked each module's outputs and inputs by eye and it should work in theory but it threw an error:

```
**** automatic analysis failed - see reason and line numbers below
Stage aamod_coreg_general required input grey_mask is not an output of any stage it is dependent on. You might need to add an aas_addinitialstream command or get the stream from a remote source.
for help, see the aa wiki
```

```
aap = aas_renamestream(aap,'aamod_mask_segment_00001','grey','native_grey','input');
aap = aas_renamestream(aap,'aamod_mask_segment_00001','white','native_white','input');
aap = aas_renamestream(aap,'aamod_mask_segment_00001','csf','native_csf','input');
aap = aas_renamestream(aap,'aamod_coreg_general_00001','reference','meanepi','input');
aap = aas_renamestream(aap,'aamod_coreg_general_00001','input','grey_mask','input');
aap = aas_renamestream(aap,'aamod_coreg_general_00001','append','white_mask','input');
aap = aas_renamestream(aap,'aamod_coreg_general_00001','append','csf_mask','input');
```

**Comment by tiborauer** [comment]
I forgot a few things! Sorry!
1. aamod_mask_segment also automatically rename its outputs (as you should have been warned during the execution) to correspond to its input (<input>_mask). Therefore, its outputs are 'native_grey_mask', `native_white_mask`, and 'native_csf_mask'.
2. The good is that you do not have to worry about this time because aamod_compSignal does not use any of these. Its input is 'segmasks', which is a single stream collecting the masks. Therefore, you have to coregister this stream rather than the individual ones: `aap = aas_renamestream(aap,'aamod_coreg_general_00001','input','segmasks','input');`. I.e., do not append other streams.

**Comment by TamerGezici** [comment]
I got a hilarious error. The path seems to be messed up for some reason.

```
SPM12: spm_coreg (v7320)                           12:24:50 - 30/09/2022
========================================================================
Completed                               :          12:25:02 - 30/09/2022
Error using fopen
Unable to find file. Ensure file exists and path is valid.

Error in read_hdr_raw (line 20)
fp  = fopen(hname,'r','native');
```

hname =

`    'EEE:::\fffMMMRRRIII\fffrrr---ppprrr---333---AAAAAA\HHHCCCFFFppprrreeeppp\mmmoooddduuullleee___ttteeesssttt\mmmoooddduuullleee___ttteeesssttt___cccooommmpppsssiiigggnnnaaalll___cccooorrreeegggnnneeewww\aaaaaammmoooddd___cccooorrreeeggg___gggeeennneeerrraaalll___000000000000111\sssuuubbb---000222\ssstttrrruuuccctttuuurrraaalllsss\SSS___ccc123sssuuubbb---000222___ssseeesss---111___rrruuunnn---111___TTT111www___111___000000000111...nnniiiiii'`

**Comment by tiborauer** [comment]
Can you print out `sourceimfn`?

**Comment by TamerGezici** [comment]
```
  3×153 char array

    'E:\fMRI\fr-pr-3-AA\HCFprep\module_test\module_test_compsignal_coregnew\aamod_coreg_general_00001\sub-02\structurals\S_c1sub-02_ses-1_run-1_T1w_1_0001.nii'
    'E:\fMRI\fr-pr-3-AA\HCFprep\module_test\module_test_compsignal_coregnew\aamod_coreg_general_00001\sub-02\structurals\S_c2sub-02_ses-1_run-1_T1w_1_0001.nii'
    'E:\fMRI\fr-pr-3-AA\HCFprep\module_test\module_test_compsignal_coregnew\aamod_coreg_general_00001\sub-02\structurals\S_c3sub-02_ses-1_run-1_T1w_1_0001.nii'
```

**Comment by TamerGezici** [comment]
The files do exist, by the way.

**Comment by tiborauer** [comment]
My bad, again.
You are not supposed to directly coregister the mask to the epi due to lack of contrast in the masks. Try:

```matlab
aap = aas_renamestream(aap,'aamod_coreg_general_00001','reference','meanepi','input');
aap = aas_renamestream(aap,'aamod_coreg_general_00001','input','structural','input');
aap = aas_renamestream(aap,'aamod_coreg_general_00001','append','segmasks','input');
```

Also, make sure that aamod_segment8 does not normalise `structural`:
`aap.tasksettings.aamod_segment8.writenormimg = 0;`

If you do need the `structural` to be normalised, then the second line from the block above should be:
`aap = aas_renamestream(aap,'aamod_coreg_general_00001','input','aamod_structuralfromnifti.structural','input');`
to make sure it uses the non-normalised `structural`.

**Comment by TamerGezici** [comment]
> I got a hilarious error. The path seems to be messed up for some reason.
> 
> ```
> SPM12: spm_coreg (v7320)                           12:24:50 - 30/09/2022
> ========================================================================
> Completed                               :          12:25:02 - 30/09/2022
> Error using fopen
> Unable to find file. Ensure file exists and path is valid.
> 
> Error in read_hdr_raw (line 20)
> fp  = fopen(hname,'r','native');
> 
> Error in read_hdr (line 37)
> [hdr,be] = read_hdr_raw(hname);
> 
> Error in nifti (line 26)
>         vol    = read_hdr(fname);
> 
> Error in spm_get_space (line 18)
> N = nifti(P);
> 
> Error in aamod_coreg_general (line 114)
>             spm_get_space(sprintf('%s,%d',sourceimfn,i), spm_matrix(x)\spm_get_space(sprintf('%s,%d',sourceimfn,i)));
> 
> Error in aa_feval (line 15)
>     [varargout{:}]=feval(funcname,varargin{:});
> 
> Error in aa_feval_withindices (line 4)
> [aap,resp]=aa_feval(mfile_alias,aap,task,ci{:});
> 
> Error in aa_doprocessing_onetask (line 191)
>             [aap,~]=aa_feval_withindices(mfile_alias,aap,task,indices);
> 
> Error in aaq_localsingle/runall (line 15)
>                 aa_doprocessing_onetask(obj.aap,job.task,job.k,job.indices);
> 
> Error in aa_doprocessing (line 361)
>             taskqueue.runall(dontcloseexistingworkers, false);
> 
> Error in module_test (line 67)
> aa_doprocessing(aap);
> ```
> 
> hname =
> 
> ` 'EEE:::\fffMMMRRRIII\fffrrr---ppprrr---333---AAAAAA\HHHCCCFFFppprrreeeppp\mmmoooddduuullleee___ttteeesssttt\mmmoooddduuullleee___ttteeesssttt___cccooommmpppsssiiigggnnnaaalll___cccooorrreeegggnnneeewww\aaaaaammmoooddd___cccooorrreeeggg___gggeeennneeerrraaalll___000000000000111\sssuuubbb---000222\ssstttrrruuuccctttuuurrraaalllsss\SSS___ccc123sssuuubbb---000222___ssseeesss---111___rrruuunnn---111___TTT111www___111___000000000111...nnniiiiii'`

I forgot to mention that the functions I was calling were these when I got the error I quoted above.

```
aap = aas_renamestream(aap,'aamod_mask_segment_00001','grey','native_grey','input');
aap = aas_renamestream(aap,'aamod_mask_segment_00001','white','native_white','input');
aap = aas_renamestream(aap,'aamod_mask_segment_00001','csf','native_csf','input');
aap = aas_renamestream(aap,'aamod_coreg_general_00001','reference','meanepi','input');
aap = aas_renamestream(aap,'aamod_coreg_general_00001','input','segmasks','input');
```
__________________________________________________________________________________

Here's what I have atm.

```
aap = aas_renamestream(aap,'aamod_mask_segment_00001','grey','native_grey','input');
aap = aas_renamestream(aap,'aamod_mask_segment_00001','white','native_white','input');
aap = aas_renamestream(aap,'aamod_mask_segment_00001','csf','native_csf','input');
aap = aas_renamestream(aap,'aamod_coreg_general_00001','reference','meanepi','input');
aap = aas_renamestream(aap,'aamod_coreg_general_00001','input','structural','input');
aap = aas_renamestream(aap,'aamod_coreg_general_00001','append','segmasks','input');
aap.tasksettings.aamod_coreg_general.roptions.interp = 0;
aap.tasksettings.aamod_segment8.writenormimg = 0;
```

Here's the new error:

```
Completed                               :          13:26:20 - 30/09/2022
Index exceeds the number of array elements (2).

Error in aamod_coreg_general (line 138)
                spm_reslice(strvcat(targetimfn,deblank(imfnToResolice(e,:))),flags.write(e));

Error in aa_feval (line 15)
    [varargout{:}]=feval(funcname,varargin{:});

Error in aa_feval_withindices (line 4)
[aap,resp]=aa_feval(mfile_alias,aap,task,ci{:});

Error in aa_doprocessing_onetask (line 191)
            [aap,~]=aa_feval_withindices(mfile_alias,aap,task,indices);

Error in aaq_localsingle/runall (line 15)
                aa_doprocessing_onetask(obj.aap,job.task,job.k,job.indices);

Error in aa_doprocessing (line 361)
            taskqueue.runall(dontcloseexistingworkers, false);

Error in module_test (line 69)
aa_doprocessing(aap);
```

`flags.write(e)` is causing the error.

The value of e is 3.

**Comment by TamerGezici** [comment]
Oh hold on. It could be that the results need to be deleted and re-started. Let me see that.

**Comment by TamerGezici** [comment]
No, the error is same.

**Comment by tiborauer** [comment]
OK. It requires a bit more extensive modifications:

aamod_coreg_general, lines 134-175 should be replaced with this:

```matlab
        %% Describe the outputs and Diagnostics 
        % For outputs
        for s = 1:numel(outpstream)
            otherimfn = aas_getfiles_bystream(aap,domain,cell2mat(varargin),outpstream{s});
            otherimfn2 = '';
            for e = 1:size(otherimfn,1)
               
                % Reslice
                if aas_getsetting(aap,'doReslice')
                    spm_reslice(strvcat(targetimfn,deblank(otherimfn(e,:))),flags.write(s));
                else
                    flags.write(s).prefix = ''; % same file
                end

                fpath = spm_file(otherimfn(e,:),'prefix',flags.write(s).prefix);

                % binarise if specified
                if isfield(aap.tasklist.currenttask.settings,'PVE') && ~isempty(aap.tasklist.currenttask.settings.PVE)
                    ninf = spm_vol(fpath);
                    Y = spm_read_vols(ninf);
                    Y = Y>=aap.tasklist.currenttask.settings.PVE;
                    nifti_write(fpath,Y,'Binarized',ninf)
                end
                
                otherimfn2 = strvcat(otherimfn2, fpath);
            end
            
            aap = aas_desc_outputs(aap,domain,cell2mat(varargin),outpstream{s},otherimfn2);
            if strcmp(aap.options.wheretoprocess,'localsingle')
                aas_checkreg(aap,domain,cell2mat(varargin),outpstream{s},inpstream{tInd});
            end
        end
        
        %% Cleanup
        delete(targetimfn);
```

**Comment by TamerGezici** [comment]
I think it worked. 

![diagnostic_compSignal](https://user-images.githubusercontent.com/11014942/193288965-6a15b9a2-4e10-4931-9dce-f659531e163c.jpg)

**Comment by TamerGezici** [comment]
Thanks a lot for your time. I really appreciate it. 

I want to ask if there's anything I need to know about using `coreg_general `vs. `coreg_extended` I'd like to know what it pertains to for my analysis. I plan to use `compSignal `mainly for a specific tactile task and maybe another analysis. I wont be using it for anything else.

Should I move on to `general `on all analysis, or stick to the `extended `version? I have a rough idea on what the extended version does from the comments on top of the function, but I'm not sure how these two compare.

**Comment by tiborauer** [comment]
It depends in which space you want to carry out your analyses.
coreg_general is the simplest and most generic implementation, basically as wrapper around SPM Coreg. It allows registering in any direction (e.g., structural to EPI or EPI to structural).
coreg_extended is a fixed-directional registering tool. It aligns (6 DOF) structural to MNI, then you register your EPI to the structural so that you can apply normalisation parameter calulated based on structural to the EPI.

If you want to perform analysis in native space, I suggest using coreg_extended, just as you did.
If you want to perform analysis in MNI space, I suggest using coreg_extended; however, a different, more flexible implementation splitting the two steps. See [the basic workflow](https://github.com/automaticanalysis/automaticanalysis/blob/master/examples/demos/basic.xml).

**Comment by TamerGezici** [comment]
The native space is the subject space, right? The non-normalized version of the data. 

We intend to do our analysis in MNI space. So from what I gather, since I do structural normalization in the upcoming steps, there is no point in using `coreg_extended `the current way I do. 

I should either implement the methodology in the basic workflow or stick to the `coreg_general `version. Now the key point for me is either to stick to the original SPM Coreg or to the method you suggest. I'll happily stick to your suggestion, but it would be useful for me to know the difference between them. 

I think the second one is better because you first coregister T1 to the structural template and the EPI seperately. I guess SPM does it someother way?

**Comment by tiborauer** [comment]
coreg_extended aligns (6 DOF) the structural to MNI, so the later segmentation+normalisation can be more accurate.

**Comment by TamerGezici** [comment]
In the basic workflow, what do these do?

```
<module><name>aamod_norm_write</name></module> 
<module><name>aamod_norm_write_meanepi</name></module> 
```

And how is it different than just doing:

`<module><name>aamod_norm_write_epi</name></module>
`

**Comment by tiborauer** [comment]
All three of them point to the same code (_aamod_norm_write.m_), so there is not much difference. _aamod_norm_write_epi_ and _aamod_norm_write_meanepi_ are specialised, while _aamod_norm_write_ is a a generic one, which processes epi by default.

Their default parameters (e.g., bounding box) are slightly different. Check out the corresponding XMLs.

**Comment by TamerGezici** [comment]
I see. I will use two-step implementation then. Thank you for your answers and your assistance.
