### ISSUE TITLE
Some clarification on PPI changes in aamod_firstlevel_model

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#355]
The code for adding PPI regressors has been changed in `aamod_firstlevel_model` since I last did a PPI and it's crashing on me. Code in question:

```
% Add PPI if exist
        for sess = subjSessionI
            if aas_stream_has_contents(aap,'session',[subj,sess],'ppi')
                [defCov, ind] = aas_getsetting(aap,'modelC','session',[subj sess]);
                if ~isempty(defCov)
                    covToRemove = [];
                    PPIs = cellstr(aas_getfiles_bystream(aap,'session',[subj,sess],'ppi'));
                    for indDefPPI = find(cellfun(@(x) ~isempty(regexp(x,'^ppidef_.*', 'once')), {defCov.covariate.name}))
                        defPPI = defCov.covariate(indDefPPI);
                        covToRemove(end+1) = indDefPPI;
                        fnPPI = PPIs{contains(spm_file(PPIs,'basename'),defPPI.vector')};
                        dat = load(fnPPI); PPI = dat.PPI;                        

                        if ~any(strcmp({aap.tasksettings.(modname(1:modnameind-1))(modindex).modelC(ind).covariate.name},['Phys_' PPI.xY.name]))
                            aap = aas_addcovariate(aap,modname,...
                                aas_getsubjname(aap,subj),aas_getsessname(aap,sess),...
                                ['Phys_' PPI.xY.name],PPI.Y,0,1);
                        end
                        aap = aas_addcovariate(aap,modname,...
                            aas_getsubjname(aap,subj),aas_getsessname(aap,sess),...
                            strrep(defPPI.name,'ppidef_',''),PPI.ppi,0,1);
                        %                     aap = aas_addcovariate(aap,modname,...
                        %                         aas_getsubjname(aap,subj),aas_getsessname(aap,sess),...
                        %                         ['Psych_' psych],PPI.P,0,1);
                    end
                    aap.tasksettings.(modname(1:modnameind-1))(modindex).modelC(ind).covariate(covToRemove) = []; % remove original definition
                end
            end
        end
        % update current sesstings
        aap.tasklist.currenttask.settings.modelC = aap.tasksettings.(modname(1:modnameind-1))(modindex).modelC;
```

Two questions:

1) The new code is looking for PPI regressors as covariates (cf. ~isempty(defCov)). Why? And how? It didn't used to work this way. Is the usage change documented somewhere?

2) The interaction (ppi) and physiological regressors are added here, but the call to `aas_addcovariate` for the psychological regressor is commented out. Is this a typo? Aren't all three required in a PPI model?

**Comment by tiborauer** [comment]
You are right, I still owe documentation...
The PPI has been changed in #246. My implementation follows that of SPM's with some convenience features.

The tasklist should contain an `aamod_vois_extract` to define the VOIs (you can define more than one). See the [module header](https://github.com/automaticanalysis/automaticanalysis/blob/master/aa_modules/aamod_vois_extract.xml) for further details. The VOI can be (`VOI.type`)
- `sphere` with radius = `VOI.size`/2
- `mask`, which is generated by thresholding the last input with 0.5
- `roi`, which is generated by taking an ROI (`VOI.centredefinition.roival`)  from an atlas (last input)

I case of a spherical VOI, its centre can be
- the centre of the ROI (VOI.centre = `roicentre`)
- local maximum activartion within the ROI (VOI.centre = `roimaximum`) based on a contrast selected by its name (`VOI.centredefinition.contrast`).

The tasklist should also contain an `aamod_ppi_prepare`, which prepares the PPI covariates as defined by `aas_addcoveriate`. See [its help](https://github.com/automaticanalysis/automaticanalysis/blob/master/aa_engine/aas_addcovariate.m) fo further details.

**Comment by jones-michael-s** [comment]
Hi Tibor,

Thanks for the fast reply!

Do you have an example script that uses the new PPI modules? That might be the easiest way to sort this out.

**Comment by tiborauer** [comment]
I have a script, however, it is not based on open data, and it is quite complex because it also includes multivariate analysis and several models (branching). I can perhaps send you some code snippets 'offline'.

**Comment by jones-michael-s** [comment]
I think I understand the tasklist -- perhaps just a snippet demonstrating the use of aas_addcovariate? 

I'd be happy to generate an example script for the repo using public data (once I figure out proper usage!)

**Comment by tiborauer** [comment]
Email sent

**Comment by jones-michael-s** [comment]
Thanks!
