### ISSUE TITLE
aamod_glmdenoise issues

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#359]
Hi,

Forking from the issue here: https://github.com/automaticanalysis/automaticanalysis/issues/345#issuecomment-1293976539

I am running GLMdenoise on my data. I ran into an error during model estimation:

```
Error using spm_est_non_sphericity
Please check your data: There are no significant voxels.
```

I understand that this is not an AA issue but with SPM. I searched the internet and came across these:

https://www.nitrc.org/forum/forum.php?thread_id=5838&forum_id=1144

http://windstalker.pbworks.com/w/page/81870254/SPM%20Setting%20Issue

I tried changing the masking threshold [here ](https://github.com/automaticanalysis/automaticanalysis/blob/b332aaec0c0654cdd144ddddead00b2aa4ea868d/aa_modules/aamod_firstlevel_model.xml#L38)to inf as suggested, but that didn't fix anything.

I guess this relates to the BET procedure.

I looked at one of my normalized EPI images using MRICroGL and the images show nothing. It's a 4KB file which doesn't seem to have a brain in it. Just blank, blackness.

The last BET related output is reslicing, then that goes to normalization. Which outputs something like this:

![image](https://user-images.githubusercontent.com/11014942/200074073-b0038d35-9a4c-412e-9ded-4ce8412e8962.png)

Could it be that it doesn't work with 3D NIfTI?

**Comment by tiborauer** [comment]
Increasing the masking threshold (to inf) eliminates all voxels. You should lower it. Try 0.1.

I am afraid the filenames do not tell me anything. You should check the data (i.e. how the images look like).

Finally, if it is not an aa issue, you should not post it here but rather drop me or the SPM mailing list an email.

**Comment by TamerGezici** [comment]
Sorry, what I meant by "it is an SPM issue" is that the error is in SPM toolbox, not some aa module etc. Otherwise it is an AA issue since the root cause is due to something going wrong with BET.

Changing masking threshold to 0.1 didn't change anything.

I checked the BET re-sliced images. They look fine. I guess the issue is due to 3D NIfTI. I shared the screenshot to demonstrate it's outputs. There is one file only, and that is `bet_meanasub-01_ses-1_task-discrB_run-01_bold_001`

I guess BET should be done on each image right? I will see if the issue is due to 3D NIfTI and get back to you.

**Comment by tiborauer** [comment]
What do you mean by "the error is in SPM toolbox"? Is some part of SPM missing or not initialised? BET is not part of SPM.

I am afraid I have never used GLMdenoise and I have not used 3D NIfTI for over ten years (since I reaslied that SPM can also handle 4D NIfTI :)); therefore, I may not be able to help you on this.

**Comment by TamerGezici** [comment]
Haha, sorry. There is no error in SPM. It's just that the error pops during `spm_est_non_sphericity`. I am aware that BET is a part of FSL.

I switched to 4D NIfTI for testing purposes. But the error persists. I understand that it may be tricky to solve some module you've never used before.

I think the issue is BET itself. Can you please tell me what is the expected output of `aamod_bet_epi_reslicing`?

I will share some screenshots. Hopefully these will be useful. 


My output of bet reslicing is a single file which is only 513KB 

![image](https://user-images.githubusercontent.com/11014942/200163334-6c8531ff-27bd-4cc2-b3c6-dd3a12b51a28.png)

I think this is a single volume. Shouldn't it be the whole volume (all acquisitions of that run)? The file looks fine under MRIcroGL. It is a BET'ed brain.

![image](https://user-images.githubusercontent.com/11014942/200163359-1c476581-01db-4b4a-b43a-72d7313d2f21.png)

But I think it is a single acquisition? Otherwise the file should have been larger, right?

My normalization output looks like this:

![image](https://user-images.githubusercontent.com/11014942/200163436-1f3582a2-178a-4874-9a34-bba7da0fc8b2.png)

wrasub-01 file (output) is a blank file. There is no image when I inspect it under MRIcroGL. I think there could be something going wrong in normalization? The input, ra-sub-01 looks fine however that image is not BET'ed (ie. I can see the skull) so maybe I need to explicitly tell to receive BET'ed image as input? 

But before that I need to understand if BET is working properly to begin with.

**Comment by tiborauer** [comment]
Your BET output looks good. If you BET a 4D NIfTI, then each volume should look like this (apart from some movement, of course).
I am not familiar with MRIcroGL because I use FSLeyes which allows you browse across the  volumes in a 4D NIfTI.

I can also tell based on the file sizes that the wrasub file is not good. I wonder whether you managed to sort out the bounding box (https://github.com/automaticanalysis/automaticanalysis/issues/345#issuecomment-1295925378).

**Comment by TamerGezici** [comment]
Ah yes, well the bounding box setting I used was this. I forgot to check this with you.

```
aap.tasksettings.aamod_norm_write.bb = [-90.8153 -144.8140 -176.6066 90.1332 115.1490 113.1649];
aap.tasksettings.aamod_norm_write_meanepi.bb = [-90.8153 -144.8140 -176.6066 90.1332 115.1490 113.1649];
```

Which I found out by doing:

`spm_get_bbox('D:\studies\analysis\tamer_study3\B_block\linux_test_4D\aamod_segment8_00001\sub-01\structurals\msub-01_ses-1_run-1_T1w_1_0001.nii')`

**Comment by TamerGezici** [comment]
You can also browse across volumes in 4D NIfTI using this tool. And that is what I was asking.

Does BET reslicing generate a single volume or is it supposed to be all volumes of a run? Because this file corresponds to a single volume of a run (probably the first image acquired)

**Comment by tiborauer** [comment]
Your bounding box definition is not correct (the order of numbers is wrong). Pleas check the description in https://github.com/automaticanalysis/automaticanalysis/blob/b332aaec0c0654cdd144ddddead00b2aa4ea868d/aa_modules/aamod_norm_write.xml#L14 I think that is why you get an empty image.

Based on the file size of rasub, I think it is 4D NIfTI. But you can also check its dimension with `fslsize`.

**Comment by TamerGezici** [comment]
Gosh! How dumb I am. Should have paid more attention to the bb. 

rasub is 4D NIfTI for sure, but it is not BET'ed. I will try explicitly defining BET reslicing output as input for normalization using renamestream and see what happens.

**Comment by TamerGezici** [comment]
I don't think what I mentioned above will work. I also just noticed that I am running 2 runs for my analysis but bet_reslicing is doing it's thing for only one run. I have 1 folder which is run 1, run 2 is not there.

Also I want to make sure that this BET reslicing input is correct. I haven't received an explicit confirmation from you. Is  bet reslicing input supposed be a single volume file? Because for my case it is.

**Comment by tiborauer** [comment]
As far as I can tell, [aamod_bet_epi_reslicing](https://github.com/automaticanalysis/automaticanalysis/blob/master/aa_modules/aamod_bet_epi_reslicing.xml) reslices meanepi only. 
I think you will need [aamod_bet_epi_masking](https://github.com/automaticanalysis/automaticanalysis/blob/master/aa_modules/aamod_bet_epi_masking.xml) to apply the (mean)epi mask on the runs.

**Comment by TamerGezici** [comment]
Sure I will try this. 

I have a question related to these modules with "meanepi" in them by the way. Do these do any modifications to the data? I think all they do is do something on the average epi of a run? Is it for diagnostic usage?

**Comment by tiborauer** [comment]
I am not sure what you mean "data". meanepi is also data.

**Comment by tiborauer** [comment]
meanepi is typically used during spatial preprocessing (coregistration, BET), and the typical workflow is that estimation is done on the meanepi and applied on the epi (i.e. the run(s)).

**Comment by TamerGezici** [comment]
> meanepi is typically used during spatial preprocessing (coregistration, BET), and the typical workflow is that estimation is done on the meanepi and applied on the epi (i.e. the run(s)).

Ah okay, I see. 

I modified the relevant parts of my task list to have these:

```
        <module><name>aamod_bet</name></module>
        <module><name>aamod_bet_meanepi</name></module>
        <module><name>aamod_bet_epi_reslicing</name></module> 
        <module><name>aamod_bet_epi_masking</name></module> 
```

Which threw an error.

```
Arrays have incompatible sizes for this operation.

Error in mask_img (line 21)
    elseif all(size(M) == size(Y))

Error in aamod_bet_epi_masking (line 25)
        mask_img(Mimg, EPIimg);
```

**Comment by TamerGezici** [comment]
And the images that mask_img calls are:

```
K>> Mimg

Mimg =

    'D:\studies\analysis\tamer_study3\B_block\linux_test_4D\aamod_bet_epi_masking_00001\sub-01\discrB_run-01\rbet_meanasub-01_ses-1_task-discrB_run-01_bold_brain_mask.nii'

K>> EPIimg

EPIimg =

    'D:\studies\analysis\tamer_study3\B_block\linux_test_4D\aamod_bet_epi_masking_00001\sub-01\discrB_run-01\rasub-01_ses-1_task-discrB_run-01_bold.nii'
```

**Comment by tiborauer** [comment]
I see. The code of [mask_img](https://github.com/automaticanalysis/automaticanalysis/blob/master/extrafunctions/mask_img.m) is not adjusted for 4D NIfTI. You may want to give it a go. Please, keep in mind that it is also used in [aamod_secondlevel_randomise](https://github.com/automaticanalysis/automaticanalysis/blob/master/aa_modules/aamod_secondlevel_randomise.m).

If you want to avoid any conflict, you may want to simply implement its (adjusted) functionality in aamod_bet_epi_masking rather than calling the function.

**Comment by TamerGezici** [comment]
Does that mean it will work if I try with 3D NIfTI? My initial thought that I should be using 4D NIfTI stemmed from the fact that I had seen a single volume output for bet reslice. But that is also the case for 4D. So it shouldn't make a difference.

And since the task list requires 3D NIfTI, I tried it and the most recent error is gone now. But now 

 Because I did, and it moved on from there. But now we're back to this error:

```
    ** The images do not all have the same dimensions. **
The function assumes that a voxel in one image corresponds with
the same  voxel in another.   This  is not a safe assumption if
the  image dimensions differ.   Please  ensure  that  you  have
processed all the image data in the same way (eg. check spatial
normalisation bounding-boxes, voxel-sizes etc).
Here are the dimensions of the image volumes.  This list can be
used to determine which file(s) are causing the problem.

[61 87 98]  D:\studies\analysis\tamer_study3\B_block\linux_test\aamod_GLMdenoise_00001\sub-01\discrB_run-01\wrasub-01_ses-1_task-discrB_run-01_bold_001.nii
[64 64 32]  D:\studies\analysis\tamer_study3\B_block\linux_test\aamod_GLMdenoise_00001\sub-01\discrB_run-01\rbet_meanasub-01_ses-1_task-discrB_run-01_bold_001_brain_mask.nii


** The images do not all have same orientation and/or voxel sizes. **
The function assumes that a voxel in one image  corresponds exactly
with  the same voxel in another.   This is not a safe assumption if
the orientation information  in the headers or .mat files says that
the images are oriented differently. Please ensure that you process
all data correctly. For example, you may have realigned the images,
but not actually resliced them to be in voxel-wise alignment.
Here are the orientation matrices of the image volumes.   This list
can be used to determine which file(s) are causing the problem.

[-3 0 0 93.1332; 0 3 0 -147.814; 0 0 3 -179.607]  D:\studies\analysis\tamer_study3\B_block\linux_test\aamod_GLMdenoise_00001\sub-01\discrB_run-01\wrasub-01_ses-1_task-discrB_run-01_bold_001.nii
[-2.99257 0.0902437 -0.23847 97.2533; 0.117498 2.96516 -0.550612 -121.913; -0.17531 0.44687 3.70168 -43.6037]  D:\studies\analysis\tamer_study3\B_block\linux_test\aamod_GLMdenoise_00001\sub-01\discrB_run-01\rbet_meanasub-01_ses-1_task-discrB_run-01_bold_001_brain_mask.nii



**** automatic analysis failed - see reason and line numbers below
Image orientation mismatch. You may need to reslice your meanepi before epi bet reslice - do you have aamod_norm_write_meanepi in your tasklist?
```

**Comment by TamerGezici** [comment]
By the way, normalization output is BET'ed now: (wrasub)

![image](https://user-images.githubusercontent.com/11014942/200174014-dba48a20-0208-48fa-995f-98f68666b5e2.png)

But it is significantly darker (?) than it's input (rsub)

![image](https://user-images.githubusercontent.com/11014942/200174050-56911fcb-86e8-4346-8b38-dbd58540ade1.png)

**Comment by TamerGezici** [comment]
And the normalized output appears to be BET'ed as well.

**Comment by tiborauer** [comment]
Have you checked that the geometry (bb and vox) should be the same for norm_write and norm_write_meanepi?

**Comment by TamerGezici** [comment]
Here are my task settings.

```
aap.tasksettings.aamod_norm_write.bb = [-90.8153 90.1332 -144.8140 115.1490 -176.6066 113.1649];
aap.tasksettings.aamod_norm_write_meanepi.bb = [-90.8153 90.1332 -144.8140 115.1490 -176.6066 113.1649];
aap.tasksettings.aamod_norm_write.vox = [3 3 3];
aap.tasksettings.aamod_norm_write_meanepi.vox = [3 3 3];
aap.tasksettings.aamod_segment8.vox = 3;
aap.tasksettings.aamod_segment8.samp = 3;
```

**Comment by tiborauer** [comment]
OK. I have also noticed that you mix normalised and native images:
D:\studies\analysis\tamer_study3\B_block\linux_test\aamod_GLMdenoise_00001\sub-01\discrB_run-01\wrasub-01_ses-1_task-discrB_run-01_bold_001.nii - **normalised**
D:\studies\analysis\tamer_study3\B_block\linux_test\aamod_GLMdenoise_00001\sub-01\discrB_run-01\rbet_meanasub-01_ses-1_task-discrB_run-01_bold_001_brain_mask.nii - **native**

I am not sure which one you need for GLMdenoise. Maybe it works for either until you are consitent.

**Comment by TamerGezici** [comment]
I'm sorry, I didn't understand what I need to do at this case? Shall I not do normalization?

**Comment by tiborauer** [comment]
As I said, I cannot help you with what the GLMdenoise requires; however, I would assume that it works with both native and normalised data as long as they are consistent.

**Comment by TamerGezici** [comment]
> As I said, I cannot help you with what the GLMdenoise requires; however, I would assume that it works with both native and normalised data as long as they are consistent.

I asked Johan Carlin for help, he said that he has not seen much advantage of using GLMdenoise and it is problematic to do CV after denoising due to it's internal CV method. So I changed my mind on using this.
