### ISSUE TITLE
ENH - Symbolic link option for model estimation while copying files

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#361]
I really like the idea of copying input files to their working folder before working on them, however this really slows things down particularly when I am doing model estimation. The estimation of the model is quicker than the file copying process, which is kind of frusturating since It's unnecessary time spent waiting for the execution to finish.

I wanted to ask if you'd allow me to modify the script for the implementation of symbolic links to input files only for model estimation and particularly when using remote connected pipelines.

I suggest implementing temporary symbolic links instead of copying, and then removing these links after the model has been estimated.

P.S It will be an optional thing, those who want to use the copy file system may keep the option disabled for themselves.

**Comment by tiborauer** [comment]
I am not against the idea; however, please check the discussions in #220 and #313.

**Comment by TamerGezici** [comment]
I see that the implementation would be more sophisticated than I'd imaged initially. 

What I understand is that we can have this option only for modules with `ismodified` stream tag.
However the real deal is copying imaging data, so `.nii` files. They make the bulk of the data.

So I was thinking of enabling symlink only for .nii files, and anything else can just be copied as it is. Though, I can see that this implementation requires a much detailed understanding of the internal working of AA. 

If you were to implement this, what would your approach be? Speaking in terms of pseudocode and conceptually.

**Comment by tiborauer** [comment]
First, you have to think in streams rather than files.
Second. the epi stream for aamod_firstlevel_model is ismodified=0: https://github.com/automaticanalysis/automaticanalysis/blob/1094ed7ac978ef2eb9f066c8eed41ed828b578fa/aa_modules/aamod_firstlevel_model.xml#L93 Therefore, it is not an issue here.

The main issue is that you use Windows, AFAIR. Therefore, you have to figure out how to make symbolic link in Windows and modify the corresponding section https://github.com/automaticanalysis/automaticanalysis/blob/1094ed7ac978ef2eb9f066c8eed41ed828b578fa/aa_engine/aas_retrieve_inputs_part2.m#L137-L140 to make it similar to https://github.com/automaticanalysis/automaticanalysis/blob/1094ed7ac978ef2eb9f066c8eed41ed828b578fa/aa_engine/aas_retrieve_inputs_part2.m#L142-L151

**Comment by tiborauer** [comment]
Also, you may want to add a `aap.options.symlinks` option

**Comment by TamerGezici** [comment]
What is the use of the third code block you posted above (142-151) in Linux? As far as I understand, it's a hardlink which still means the content of the file is copied? That's what I understood when I read the web.

For my use case, I think a softlink is what I should do?

**Comment by tiborauer** [comment]
Yes, you are correct! However, you should implement both ideally and leave the choice to the user by also adding `aap.options.symlinks` (mutually exclusive with `aap.options.hardlinks`).

As far as I remember, the main motivation behind using hardlinks rather than symlinks is that MATLAB does not handle symbolic links well on some networks (including ours). So please check!

**Comment by TamerGezici** [comment]
What should I do for `aas_copyfromremote`? By the way, I forgot to create a PR for this -- here

https://github.com/automaticanalysis/automaticanalysis/blob/1094ed7ac978ef2eb9f066c8eed41ed828b578fa/aa_engine/aas_copyfromremote.m#L106

I added so that if it's Windows, it copies files instead of rsync.

Now for symbolink links what should I do? (If it's possible at all)

**Comment by TamerGezici** [comment]
I am curious if we can use copyfromremote without actually copying, ONLY if the host and local are the same machine.

**Comment by TamerGezici** [comment]
Here's the problem:

`aas_copyfromremote` is called in several sections when doing a remote pipeline, and it retrieves files which also are not neuroimaging files (txt files related to modules, aap structure files etc). Making a symlink for those files would be silly, so I need to figure out a way to only filter relevant files and symlink those. 

I could add a parameter to the function so that we can use symlink only if that parameter is true, and for other cases  (such as retrieve_inputs_part1 and aas_connectAApipelines) it will be false.

So only this part (?) will have the flag:

https://github.com/automaticanalysis/automaticanalysis/blob/1094ed7ac978ef2eb9f066c8eed41ed828b578fa/aa_engine/aas_retrieve_inputs_part2.m#L87-L94

And other parts will have the flag as false.

Then I can use mklink in `aas_copyfromremote ` instead of copy when that flag is true.

**Comment by tiborauer** [comment]
I would not use symbolic link for remote data because it may live on a network drive and may 'disappear'.

**Comment by TamerGezici** [comment]
> I would not use symbolic link for remote data because it may live on a network drive and may 'disappear'.

I see. What about making the remote symbolic link as a seperate option? 

Because I use remote connected pipelines on the local machine, for the sole purpose of keeping results and scripts neater.

I have a task script which does preprocessing, and then I use seperate scripts for different models. And those models are connected using remote connection, because I also prefer setting the results directory apart from the main preprocessing results directory. It keeps things more organized for me, and also allows me to distribute preprocessed data across other lab members.

**Comment by tiborauer** [comment]
It sounds reasonable. I only wanted to make the vulenrability of such connection more explicit.

**Comment by TamerGezici** [comment]
> It sounds reasonable. I only wanted to make the vulenrability of such connection more explicit.

Thanks!

What type of files go through this? 

https://github.com/automaticanalysis/automaticanalysis/blob/1094ed7ac978ef2eb9f066c8eed41ed828b578fa/aa_engine/aas_retrieve_inputs_part2.m#L87-L94


Is it just NIfTI? Anything I should pay attention to?

**Comment by tiborauer** [comment]
I do think aa distiguishes file types. It process all files regardless of their type.

And I would also advise against filtering for NIfTI because there may be other larger files, e.g., for M/EEG.

**Comment by TamerGezici** [comment]
Sure. So, then I'm assuming only doing symbolic links for `streamfiles(depind).fns` is the best option. Because this will be the stream of files which will be analyzed, and all other files are AA related files so they should be copied, not symlink'ed.

**Comment by tiborauer** [comment]
Yes, you can limit the solution to stream files.
However, I would rather implement linking in `aas_copyfromremote` with a switch `allowsymlink` set in `aas_retrieve_inputs_part2` depending on the options.
