### ISSUE TITLE
BUG - Error in iTT toolbox cell_index.m during AA initialization

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#362]
iTT toolbox works fine on its own. However, when I try running AA having the toolbox installed, it throws an error:

I am guessing the `cell_index` in iTT toolbox is different than the one AA uses, which could be the reason of this error.

When I uninstall iTT toolbox the issue sorts itself out.

```
Unrecognized function or variable 'test'.

Error in cell_index (line 16)
if isempty(test)

Error in parse_selected_sessions (line 28)
if cell_index(varargin,'subject')

Error in aas_getN_bydomain (line 63)
        aap=parse_selected_sessions(aap,sessions);

Error in aas_dependencytree_allfromtrunk>allfromtrunk (line 14)
[N, I] = aas_getN_bydomain(aap,domaintree{1},indices);

Error in aas_dependencytree_allfromtrunk>allfromtrunk (line 18)
                deps=allfromtrunk(aap,domaintree(2:end),[indices Nind],deps);

Error in aas_dependencytree_allfromtrunk (line 8)
    deps=allfromtrunk(aap,domaintree,[],{});

Error in aa_doprocessing (line 279)
        deps=aas_dependencytree_allfromtrunk(aap,domain);

Error in studyB_sr_newcoreg (line 63)
aa_doprocessing(aap);
 
16  if isempty(test)
K>> lines

lines =

  0×0 empty cell array

K>> str

str =

    'subject'

K>> nl

nl =

     1

K>> ni
Not enough input arguments.
```

**Comment by tiborauer** [comment]
Yes, you are right. You can try replacing the function in iTT with that in aa. Alternatively, you can rename the function and its references in iTT.

**Comment by TamerGezici** [comment]
> Yes, you are right. You can try replacing the function in iTT with that in aa. Alternatively, you can rename the function and its references in iTT.

Shall I do the former, and submit a PR to iTT repository?

**Comment by tiborauer** [comment]
Sure!
Does the function in aa works in iTT?

**Comment by TamerGezici** [comment]
> Sure! Does the function in aa works in iTT?

I'll need to test that first, I'll let you know.
