### ISSUE TITLE
Second level contrast issue when session counts and regressors do not match across all participants

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#363]
Sorry for the high volume of issues I have been creating lately :).

It is not extremely urgent, but I ran into an issue.

So I have some subjects who have 3 runs, and some who have a single run.

Some participants are missing regressors, so when defining their contrast vector, I am accounting for the positions, and removing those regressors which don't exist. So a different call to aas_addcontrast for each subject seperately, as well as seperate for each session. 

So what I'd been doing was calling

` aap = aas_addcontrast(aap, 'aamod_firstlevel_contrasts', subject_number, aa_session_specifier,curr_contrast_vector,curr_contrast, 'T');
`
Where `aa_session_specifier` is the name of the session added to aap using `aas_addsession`

Defined like this:

`aa_session_specifier = ['singlesession:',session_name];`

I was using singlesession, but now the contrasts become like this:

Here, each contrast for each session has become seperate.

![diagnostic_aamod_firstlevel_contrasts](https://user-images.githubusercontent.com/11014942/203295585-c357ad2b-ac7e-4dc3-9da1-69248ed8f02a.jpg)

Which previously, was like this:

Where each contrast were an average of all sessions (I guess)

![image](https://user-images.githubusercontent.com/11014942/203295914-167884f2-9a8e-44f4-90e5-b8d58e101829.png)

Now the problem is that since each participant's contrast vector is different, I can not use something like:

 'sessions:SESS01+SESS02+SESS03'; etc.

I need to define each subject's session contrast vector seperately.

However, when I do that, the contrasts for each session are seperated?

Is the solution here to use `uniquebysession`?

**Comment by tiborauer** [comment]
I would define contrast averaging across all (available) sessions. I cannot see why you cannot use a session-specific contrast definition. You only have to make sure that you define the session according to their availability.

**Comment by tiborauer** [comment]
Why do not you specify only the 2 contrast combining all available sessions for all participants?

**Comment by TamerGezici** [comment]
> Why do you not specify only the 2 contrast combining all available sessions for all participants using `'sameforallsessions'`?

Because the contrast vector for each participant is different (because some participants are missing some regressors)

**Comment by tiborauer** [comment]
If the regressors you want to use are the same across participants and sessions (i.e., some may have additional regressors of no interest), then you can specify contrasts using regressor names consistent across participants and sessions, in which case you can also use `'sameforallsessions'`.
If not then, `'uniquebysession'` is your only option.

**Comment by TamerGezici** [comment]
Yes, the regressors are same and exist in all sessions, except for a few participants.

Assume a regressor called "RS_END" is missing for sub-01, on session 2. But it exists on all other sessions. My approach was to remove that regressor's corresponding weight from the contrast vector, and add it as `singlesession:SESS02` for that participant's specific session.

Is it possible to do what you're suggesting by using a numerical contrast vector, instead of regressor names?

**Comment by TamerGezici** [comment]
The issue is, "RS_END" can also be a regressor of interest, however it may not be the only one. For example, "RS_END" could be -1, along with "RS_START", which is also -1. So the regressor is missing, but the contrast can still be formed because the participant has "RS_START"

**Comment by TamerGezici** [comment]
Okay, nevermind. I don't see a reason why to not use regressor names while defining the contrast. Looks neater and is less fool proof. Let me try.

**Comment by TamerGezici** [comment]
> If "RS_START" and "RS_END" are equivalent, then you may want to call them simply "RS" to improve consistency.

Well technically they are resting states taken at the beginning of the run and the one at the end. It kind of depends on what you are interested in looking at. In one contrast they can be the same thing, in another they can be different things. It depends.

**Comment by TamerGezici** [comment]
Using regressor names work very well. Thanks a lot for helping.
