### ISSUE TITLE
Combining several different experiments to a single analysis - missing sessions

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#366]
I have 4 different studies distributed across 160+ participants.  

Each participant has a small subset of the tasknames available to them. In other words, they have "missing" sessions.

Not all participants have the tasks listed below.

```
tasknames = {'fixnback_run-01','fixnback_run-02','fixnback_run-03','evenodd_run-01','lrlocalizer_run-01','varnback_run-01','varnback_run-02','varnback_run-03','metacog_run-01','spatialwm_run-01','spatialwm_run-02','nback_run-01','nback_run-02','nback_run-03','nback_run-04','meta_run-01','discr_run-01','discr_run-02','discr_run-03','discr_run-04','easydiff_run-01','thinkrest_run-01','flang_run-01','flang_run-02','gonogo_run-01','thinkrest_run-01','twozeroback_run-01','sentencecomp_run-01','obl_run-01','obl_run-02'};

for i = 1:size(tasknames,2)
    aap = aas_addsession(aap,tasknames{i}); 
end
```

What I do is, I add data using `aas_addsubject `by looping over this tasknames cell array and finding .nii files which match the name of the task. If I find them, I add them like this:

`subject_data_func{end+1} = struct('fname',{func_files},'hdr',fullfile(func_hdr.folder,func_hdr.name)); `

If I don't find a taskname for that participant, I simply do:

`subject_data_func{end+1} = struct('fname',{},'hdr','');`

Which I later on add like this:

`aap = aas_addsubject(aap,subj,'functional',subject_data_func,'structural',{subject_data_anat});`

However, this analysis does not work. It processes some participants but most of them are untouched.

I'm not sure how AA deals with such situation. I will post the messages AA generates tomorrow. It basically skips the participants for some reason. And marks the steps as "done" without modifying any data.

**Comment by TamerGezici** [comment]
`WARNING: No inputs selected for stream meanepi. --> MODULE aamod_norm_write_meanepi will be SKIPPED`

This is the error (it happens to all modules) though

**Comment by tiborauer** [comment]
1. To be honest, if your dataset is so heterogenous, you might better process them separately. 
2. The missing session is typically marked with an empty array `[]` rather than with a struct with empty items.
3. If you add new data or change the specification, I suggest to remove al modules for that participant because aa will not reprocess them leading to missing and skipped sessions/subjects.

**Comment by tiborauer** [comment]
If you change the empty session specification, then you may need to 'reset' that participant (i.e., remove all modules for that participant).

Why do not you specify only the common sessions?

**Comment by tiborauer** [comment]
I think it is doable as long as the contrasts names are the same across subjects. However, if the data is heterogenous, then you have to do a lot of manual work.

My suggestion would be to analyse homogeneous datasets separately, and combine only the firstlevel contrasts (probably even outside aa).

**Comment by TamerGezici** [comment]
> I think it is doable as long as the contrasts names are the same across subjects. However, if the data is heterogenous, then you have to do a lot of manual work.
> 
> My suggestion would be to analyse homogeneous datasets separately, and combine only the firstlevel contrasts (probably even outside aa).

I was hoping so as well. We'll see how it turns out. And I may end up analyzing them outside of AA if it doesn't play out that well. Thanks a lot for your answers.
