### ISSUE TITLE
Changing root directory

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#367]
I installed a new drive and would like to move all results to the new drive on the computer. However, I think the root directory (aap.acq_details.root) in the aap structure for the main analysis and the one in each module needs to be updated because otherwise the analysis will try accessing them in the old folder (?) 

Is there an easy way to do this?

**Comment by tiborauer** [comment]
If you want to carry on with the analysis, the  you only need to change the path in your script, an aa will pick up the thread.
However, keep in mind that the aap structures in the already processed modules will not change, which might be an issue if you want to use them, e.g., for pipeline connection.

To update the aap structure, you need to change the `aap.acq_details.root` on the top and in the internal structure:
```matlab
aap.acq_details.root = CURRENTROOT;
aap.internal.aap_initial.acq_details.root = CURRENTROOT;
```
and save the aap structure.

**Comment by TamerGezici** [comment]
I was intending to use it with pipeline connection. (Receive final output of preprocessing and do GLM) I guess then I'll need to re-preprocess the data in the new directory.

**Comment by tiborauer** [comment]
You do not have to re-process but update the aap structures; however, it might be easier depending on the amount and complexity of the data and the available computational power.

**Comment by TamerGezici** [comment]
I need to go into each module's aap.acq_details.root for each participant and update, right? I may just rather re-analyze than do that haha!

**Comment by TamerGezici** [comment]
I wrote a script that does this.

Shall we implement this to the repo as well? How should I go about it?

```
old_root = 'F:\fr-pr-3\A_block';
new_root = 'F:\fr-pr-3\move_test';
search_path = 'F:\fr-pr-3\move_test\studyA_prep';

[~,d]=dos(['dir /s /b ' fullfile(search_path,'aap_parameters*.mat')]);  % OS dir command
d=textscan(d,'%s','delimiter','\n'); d=d{:};   % convert string to cellstr array
for i=1:length(d)
    %disp(d{i});
    aap = load(d{i},"aap").aap;
    old_path = aap.acq_details.root;
    new_path = strrep(old_path,old_root,new_root);
    aap.acq_details.root = new_path;
    save(d{i},"aap");
end
```

**Comment by tiborauer** [comment]
Searching files and folders is much easier and cross-platform compatible with `spm_select`.

You have to change not only `aap.acq_details.root` but also `aap.internal.aap_initial.acq_details.root`.

The line `aap = load(d{i},"aap").aap` looks 'pythonic' to me and I do not think will work in MATLAB. Only `load(d{i},"aap")` should suffice.

**Comment by TamerGezici** [comment]
Do you know if spm_select can give the full path of the files?

`[a b] = spm_select('ExtFPListRec', pwd, 'aap_parameters*.mat');`
this returns directories where the aap_parameter files exist, not their full path.

**Comment by tiborauer** [comment]
Try FPListRec instead ExtFPListRec. And use .* instead of * to match any character any times. I suggest you to study the spm_select documentation (at the top of the function) and the regular expressions, which it uses as a search pattern.

**Comment by TamerGezici** [comment]
Thanks. I had been consulting the spm_select documentation for a good 30 mins but I couldn't figure out the problem.

`[files dirs] = spm_select('FPListRec', pwd, 'aap_parameters.*');`

Provided that all files which contain "aap_parameters" are matrices, it should work. Which is the case when I ran the function.

**Comment by tiborauer** [comment]
That is why I also suggested studying regular expressions.

**Comment by TamerGezici** [comment]
Yeah, I agree. So here's my regex version.

`[files,dirs] = spm_select('FPListRec', search_path, '.*aap_parameters.*\.mat$');`

**Comment by tiborauer** [comment]
Sure! But it is more like an aa tool than part of the engine, because users are likely to call it outside an aa workflow. Therefor, name it `aa_change_root` and put into _\<aa path\>/aa_tools_
