### ISSUE TITLE
FIR contrasts when using regressor names as contrast vector

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#374]
What is the way to set FIR contrast vectors when using regressor names to specify the contrast vector?

I would have expected something like this, but since special symbols are not liked in regressor names, it doesn't work and I'm assuming it would take it as a wildcard.

ie. `+1xREG1*bf(1)|+1xREG1*bf(2)|-1xREG2*bf(1)|-1xREG2*bf(2) `etc.

**Comment by tiborauer** [comment]
Check the help of `aas_addcontrast.m`

**Comment by TamerGezici** [comment]
> Check the help of `aas_addcontrast.m`

Is it this part?

https://github.com/automaticanalysis/automaticanalysis/blob/3f84a0a7b6225e1d6ec25c9fcf901769818c311e/aa_engine/aas_addcontrast.m#L65

I'd seen this, but I thought this was related to something else.

**Comment by tiborauer** [comment]
Yes. As far as I know about FIR, it is modelling with a multi-order basis function. But you can check the SPM.xBF.

**Comment by TamerGezici** [comment]
Thanks. This seems to be the way, indeed.
