### ISSUE TITLE
Realignment graph differences

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#376]
Hi,

Someone from our lab brought to my attention one realignment plot that was generated from preprocessing through GUI (not using AA):

![image](https://user-images.githubusercontent.com/11014942/223501735-c4342c1d-0bb0-49d8-8785-edf204bd5e6b.png)

I was surprised since this subject had been preprocessed on AA as well and I had looked into their movement graphs before and if I had seen movement larger than 3mm, I'd have taken note. Below, there is a combined graph for both runs:

Note: I am aware that AA shows ~1200 images vs. the SPM graph that shows ~1500 images. That is because the person preprocessing was also processing an additional fMRI run that was not used in the previous analysis.

![image](https://user-images.githubusercontent.com/11014942/223502332-35c9eeae-1cf6-4b04-9ea0-a3ab11dd81ea.png)

The movement spike that SPM shows after image 500 seems to be much more than what AA deems it to be.

The first 1200 images correspond to two seperate runs. You can ignore anything after 1200 images.

run 1:
![diagnostic_aamod_realign_obl_run-01](https://user-images.githubusercontent.com/11014942/223503322-0cf2cda2-fe19-4990-83c7-022db6731ec9.jpg)

run 2:
![diagnostic_aamod_realign_obl_run-02](https://user-images.githubusercontent.com/11014942/223503313-f20e9c36-53b6-4aef-b835-35a19555c61c.jpg)

**Comment by TamerGezici** [comment]
I forgot to add:

I checked the realignment parameters my lab mate was using and they are exactly same with AA's regular realignment module.

**Comment by TamerGezici** [comment]
I've asked her to realign by doing "register to first" as that seems to be the default for AA. Let's see what that brings.

**Comment by tiborauer** [comment]
I have looked into the issue, and it seems only a plotting difference. SPM plots the amount of movement relative to the first image of the **first** run. aa plots the realignment parameters, which shows movement relative to the first image of the **corresponding** run (i.e., it discards between-run movements).
The main point, however, is that the realignment parameters and the images themselves should be the same for both.

**Comment by tiborauer** [comment]
Also, there is not much difference between "register to mean" and "register to first", however, "register to mean" takes twice longer.

**Comment by tiborauer** [comment]
If you look at the transformations (.mat files) resulting from realign, then they should be the same, and you should be able to see a non-zero 4x4 matrix for the first image of all except the first runs. SPM plot is calculated from these transformations.

**Comment by TamerGezici** [comment]
Thanks a lot for the clarification.

Can you please look at SPM's plot  and notice the ~10mm movement at image ~510

In AA, this movement is there as well, but the amount is much less than 10mm. 

Since both of these correspond to the first run, I would assume that the amount would be same, regardless of how it's plotted.

What I don't understand is, what do I do now? I was approached with the SPM graph with the question: "Hey Tamer, this participant moved more than 3mm, what do I do?" and then I was like, "I know this participant, he has not moved that much!" And I see that the movement is much less in AA. So I am not sure what kind of criteria I should apply for exclusion.

**Comment by TamerGezici** [comment]
> If you look at the transformations (.mat files) resulting from realign, then they should be the same, and you should be able to see a non-zero 4x4 matrix for the first image of all except the first runs. SPM plot is calculated from these transformations.

I guess you meant the rp files. These are txt's. They are similar, but not exactly same. But I guess the difference would be from the rtm parameter.

**Comment by tiborauer** [comment]
I should see the plots, the mat-files and the rp files myself, but this movement at ~550 and ~1100 look like between run movements, which is where aa plots 'resets' to zero (just like the rp files). I have never seen such a clear step-wise within-run movement. It is usually look more like a spike.

When I meant transformation, I meant the mat-files next to the images. They are 4x4 matrices for each volume, and describe the transformation relative to the first image of the first run. The rp files describe 6 DOF movement relative to the first image of the corresponding run (i.e. the first row is ~0s).

**Comment by TamerGezici** [comment]
The only .mat file next to the images is a file called "FD.mat" which is a double with the size of number of images per run x 1

**Comment by TamerGezici** [comment]
> But you should better know how much volmes per run you have and where are the jumps.

For the first run, there are 597 volumes, the movement is around 550, which would mean this movement occurred during the run.

**Comment by tiborauer** [comment]
This is my take on realignment (after some slight modification):
![image](https://user-images.githubusercontent.com/4816041/224112716-7da773a2-0e81-43ad-88ac-50f7d4a245a7.png)

As you can see, there is a _sub-01_task-auditory_bold.mat_ file, which stores the transformation in a 4x4xN matrix (in case of a 4D NIfTI with N volumes).

**Comment by TamerGezici** [comment]
I ran the SPM Chapter 30 script with that dataset and that transformation file is generated.

The task list is similar. The script doesn't have any specifications for realignment.

The only the difference between this dataset and my dataset could be that I am using 3D NIfTI.

**Comment by tiborauer** [comment]
I am using reproa now, but it also uses the same spm_realign under the hood. 
If you use 3D NIfTI, then you may have one mat file for every volumes. Of course, it is also possible that the NIfTI headers contains them, and that is why they are not saved separately.
I suggest stopping the script before realising, and then you can read out the transformations from the headers.

**Comment by TamerGezici** [comment]
I guess it is in the NIfTI header. Does it look like this?

```
>> a = niftiinfo('rasub-03_ses-1_task-discrA_run-01_bold_001.nii')

a = 

  struct with fields:

                 Filename: 'F:\fr-pr-3\A_block\studyA_prep\aamod_realign_00001\sub-03\discrA_run-01\rasub-03_ses-1_task-discrA_run-01_bold_001.nii'
              Filemoddate: '15-Dec-2022 17:08:44'
                 Filesize: 262496
                  Version: 'NIfTI1'
              Description: 'spm - realigned'
                ImageSize: [64 64 32]
          PixelDimensions: [3 3 3.7500]
                 Datatype: 'int16'
             BitsPerPixel: 16
               SpaceUnits: 'Millimeter'
                TimeUnits: 'Second'
           AdditiveOffset: 0
    MultiplicativeScaling: 1
               TimeOffset: 0
                SliceCode: 'Unknown'
       FrequencyDimension: 0
           PhaseDimension: 0
         SpatialDimension: 0
    DisplayIntensityRange: [0 0]
            TransformName: 'Sform'
                Transform: [1×1 affine3d]
                  Qfactor: -1
                      raw: [1×1 struct]

>> a.Transform

ans = 

  affine3d with properties:

                 T: [4×4 double]
    Dimensionality: 3

>> a.Transform.T

ans =

   -2.9964         0    0.1465         0
         0    3.0000         0         0
    0.1832         0    3.7455         0
   96.3787  -96.3811  -37.0704    1.0000
```

**Comment by TamerGezici** [comment]
@tiborauer I feel like the scale on these realignment plots may be wrong. Yesterday I had a patient who was very fidgety in the MRI scanner, I was watching the images generated real-time through the inline display. I saw him move way more than a slice during the scan and when I realigned using AA, It shows movement around a mm at most, however in the EPI images I saw how aggressive the movement was.

**Comment by tiborauer** [comment]
Have you tried realignment using SPM GUI?

>  in the EPI images I saw how aggressive the movement was

Do you mean before or after realignment (or both)? You should be aware if that the realignment parameters and plot is not the measure of true movement but only what has been estimated and corrected. So, if you can see movement after realignment, that this movement is not represented in the parameters and the plot.

**Comment by TamerGezici** [comment]
I have not done SPM GUI realignment. But I'll do it and let you know.

The movement I saw is on the raw data, before realignment.

I will also show you how much movement there is by pictures of the images.

**Comment by tiborauer** [comment]
Also, check the movement visually on the realigned data.

**Comment by TamerGezici** [comment]
Okay, my hunch was wrong. Sorry.

SPM GUI and AA realignment plots do agree for this particular subject.

For the subject I mentioned in the first post I will do the realignment myself and check. I had not done that yet. I think there is something fishy going on with the realignment my lab mate did.

**Comment by TamerGezici** [comment]
@tiborauer 

I'm so ashamed and sorry, I hope you'll accept my sincere apoligies... It seems like this movement is indeed between-run displacement.

By only realigning the last 15 images of the first run and the first 15 images of the second run, I can see where the movement occured.

I have been trying to push Lab members to use AA and I have converted some to use it. 

I have a quick question, just for clarification. Are these between-run movements important? Assuming AA does not plot them, they should not be that important. And my impression is that lab members who do not use AA so far have been taking these as excessive movement. But I guess one should consider displacement within the run, and ignore movement across runs when the scanner is off.

**Comment by tiborauer** [comment]
I am glad it has been sorted.

> I have a quick question, just for clarification. Are these between-run movements important? Assuming AA does not plot them, they should not be that important. And my impression is that lab members who do not use AA so far have been taking these as excessive movement. But I guess one should scrutinize displacement within the run, and ignore movement across runs when the scanner is off.

Automatic Analysis (aa; please, be aware of the small letter when abbreviating it :)) plots the rp files rather than the transformations. For modelling (where the rp files are used) POV, the between-run movement is irrelevant because the runs are modelled separately (constant terms at the right end of the design). For QA POV, the between-run movement can be important because it might reduce the overlap across runs and thus the final FOV; especially the translation along the z-axis in case of (the typical) axial slices. That is why it is strongly recommended to use AutoAlign (Siemens) and/or reduce the between-run communication and break to the minimum.

**Comment by TamerGezici** [comment]
Thanks a lot for your answer. Yes, indeed. In terms of the FOV, the window may shift and brain coverage may change due to within run movements.  Which is something I have been paying attention to. But it is relieving to hear that in terms of modelling it does not change anything. I will announce this information to my lab members.
