### ISSUE TITLE
Two step coregisteration algorithm

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#378]
Hi,

I am writing a paper and I just want to make sure I have explained the two-step coregisteration algorithm correctly. (For example, the one in fmri_advanced.xml)

The two-step coregisteration algorithm implemented in aa was used. Where the T1 image acquired at the beginning of the scanning session was first coregistered to the MNI (T1?) structural template. Then the mean EPI volume was reoriented to this anatomical image and then transformations acquired from here were used to coregister EPI series to the structural image.

I think this is how it is. I may have gotten it wrong so please do let me know. I tried finding an explanation from articles which cite aa, but I couldn't.

Edit:

I just now found this: 
![image](https://user-images.githubusercontent.com/11014942/226169127-7ec3cbfa-1e9a-4f62-a781-ebe096430549.png)

https://www.jneurosci.org/content/jneuro/36/49/12412.full.pdf

**Comment by tiborauer** [comment]
The section in Power et al., 2012 describes the use of `coreg_extended`. If you used `coreg_extended_1 `and `coreg_extended_2 `, then you should leave out the reference to the EPI template:
"The structural image was coregistered to the SPM T1 template. The mean functional EPI was then coregistered to the structural image. Coregistration parameters of the mean EPI were subsequently applied to all functional images."

**Comment by TamerGezici** [comment]
> The section in Power et al., 2012 describes the use of `coreg_extended`. If you used `coreg_extended_1 `and `coreg_extended_2 `, then you should leave out the reference to the EPI template: "The structural image was coregistered to the SPM T1 template. The mean functional EPI was then coregistered to the structural image. Coregistration parameters of the mean EPI were subsequently applied to all functional images."

Thank you so much.
