### ISSUE TITLE
Modules with no output streams *sometimes* crash

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#383]
Hello all,

I was recently testing a module (aamod_movie) that does not define any output streams.

It turns out the scheduler would crash depending on where the module appeared in the tasklist

This was fine:

```
        <module><name>aamod_meantimecourse_epi</name></module>  
        <module><name>aamod_moviecorr_meantimecourse</name></module>
        <module><name>aamod_moviecorr_summary</name></module>
        <module><name>aamod_movie</name></module>
```

This resulted in aas_getstreams crashing:

```
        <module><name>aamod_movie</name></module>
        <module><name>aamod_meantimecourse_epi</name></module>  
        <module><name>aamod_moviecorr_meantimecourse</name></module>
        <module><name>aamod_moviecorr_summary</name></module>
```

Here, aas_getstreams (line 31) is trying to get the names of the output streams and crashes because the struct field is empty.

I implemented a simple fix: just wrap the code in a try-catch:

```
try
    streams = task.([streamtype 'streams']).stream;
catch
    streams = [];
    return;
end
```

This fixes the problem as far as my testing can tell and has so far not created other problems. However, I'm always wary of changing things in the scheduler code and wanted to run this by the group for a sanity check...

**Comment by tiborauer** [comment]
I prefer a solution with a (specific) condition check rather than handling (potentially unrelated) exceptions. How about;
```matlab
if isstruct(task.([streamtype 'streams'])) && isfield(task.([streamtype 'streams']),'stream')
    streams = task.([streamtype 'streams']).stream;
else
    streams = [];
    return;
end
```
