### ISSUE TITLE
Contrast names.txt  shows regressor names

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#385]
Not a big deal, but I found that the "CONTRAST_NAMES.txt" file here contains regressor names instead.

I tried finding the code in which this file is created, but I could not.

![image](https://github.com/automaticanalysis/automaticanalysis/assets/11014942/6131f5d6-a8db-4433-bb45-b494a6076784)

**Comment by tiborauer** [comment]
Here is the line which writes the file https://github.com/automaticanalysis/automaticanalysis/blob/f7849b18297c277e3603e06e35010a437520d2eb/aa_modules/aamod_firstlevel_contrasts.m#L335
It writes out `convec_names`, which indeed includes the regressor names.

I think @jones-michael-s wrote that part (as Peelle Lab): https://github.com/automaticanalysis/automaticanalysis/commit/19387c68b4d17d4d032ef093754e8e87badff1df

**Comment by TamerGezici** [comment]
Ahh, turns out I could not find the line because of some aa version mismatch. I had two different aa versions on the computer I ran the code, and the one I checked the repository

**Comment by jones-michael-s** [comment]
Yep, that was my addition. We can change the filename if it would be less confusing.

FYI: I added this because the SPM plot of the design matrix typically only shows a subset of the regressors in the column labels (because the full set usually doesn't fit).
