### ISSUE TITLE
Usage of DARTEL

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#388]
Hello,

I have a study in which due to the second level masking of SPM, we end up losing activation at the posterior sides of the brain.

So I used DARTEL, and the template that is generated from `aamod_dartel_createtemplate` (for example, wTemplate and Template)

What is the difference between these two templates? Is one the group average, and the other one is group averaged to normalized space? Furthermore, when I do second level using DARTEL, are the results normalized as well, so should I use wTemplate to visualize results?

Lastly, both templates show gray matter or whitematter only, and the render resolution is a little low. Is there a way to make this template more MNI-like (ie., show all of the brain, not just GM, WM differences)

**Comment by tiborauer** [comment]
Hi,

Correct, the Template* are the the group average, while the wTemplate* are the ones in MNI space. However, they are templates only, including GM and WM only (as you noted), and used by DARTEL. I do not recommend using any of them for visualisation.

I suggest using the MNI template (from FSL, which is high-res) or the group-average of the normalised T1 images.

**Comment by TamerGezici** [comment]
Thanks a lot for your answers. 

>  or the group-average of the normalised T1 images.

How can I obtain this?

**Comment by tiborauer** [comment]
Use aamod_dartel_norm_write to normalise the structural stream (typically the T1 images).

Set `aap.tasksettings.aamod_secondlevel_threshold.overlay.template = 'averaged_structurals'`

**Comment by TamerGezici** [comment]
Thanks a lot.

You may recall from our previous meeting that I was running into this second level masking issue caused by participants with smaller brains relative to the MNI template. Because of this, activity that corresponds to the occipital cortex/pole in these participants, instead moves more towards the midline. Which misrepresents the finding.

I used DARTEL, but the issue remains. In fact, in terms of activation t-maps, I can not see any difference between DARTEL normalized and regular normalization on the MNI template.

But when I render this based on the Template* or wTemplate, I do see those activations at the surface of cortex. 

Furthermore, when I eyeball and compare wTemplate with Template, I see that they are identical. Which makes me think if I may have done something wrong?

**Comment by TamerGezici** [comment]
> I used DARTEL, but the issue remains. In fact, in terms of activation t-maps, I can not see any difference between DARTEL normalized and regular normalization on the MNI template.

Okay, there is some subtle differences, but in terms of the spread of activity that I see, they are mostly similar.

**Comment by tiborauer** [comment]
> Furthermore, when I eyeball and compare wTemplate with Template, I see that they are identical. Which makes me think if I may have done something wrong?

The Template and wTemplate in the module folder are identical; however, the actual (non-normalised) DARTAL template is in the structural folder of the first subject. Check out _stream_dartel_template_outputfrom_aamod_dartel_createtemplate_00001_ for the path.

**Comment by tiborauer** [comment]
I also suggest rerunning the analysis from scratch (unless you did so already) to avoid using already existing files from the other workflow.

**Comment by TamerGezici** [comment]
I did, but I will re-preprocess because I noticed I had not set writenormimg for smoothing to 0.

Also, does `aamod_norm_write_dartel ` also do smoothing? The output files are named "swarsub" which indicates smoothing. Because I did smoothing myself as well, they ended up becoming "sswarsub". So I removed smoothing and set the FWHM to my desired value for the normalization module itself.

**Comment by tiborauer** [comment]
> I did, but I will re-preprocess because I noticed I had not set `writenormimg `for segmentation to 0.

That explains the similar results.

> I removed smoothing and set the FWHM to my desired value for the normalization module itself.

Good.

**Comment by TamerGezici** [comment]
I've been playing around with this for the last few days, and as far as I can see:

DARTEL doesn't change much in terms of activation at the occipital pole. For example, 5 participants who have small brains have common activation in their calcarine sulcus, but since their brains are small, when they are normalized their activity falls more towards the anterior of the calcarine sulcus.

Using the averaged structurals is good in terms of showing the actual location of activation, but the resolution is low, which makes it not so nice looking for the paper.
