### ISSUE TITLE
Create first level design matrix without estimation

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#390]
For LD-t analysis, I need to create a design matrix but there is no need to do any fitting and estimation.

I was about to add a new module that only creates a design matrix, but then I saw these two functions: `aamod_firstlevel_model_2_convolve` and `aamod_firstlevel_model_1_config`

So I am assuming there is no need to create a new module, as these two would most possibly generate a design matrix?

**Comment by tiborauer** [comment]
@jooh created these modules. I have never used them, but I understand that they split the process of first-level modelling, so they should work for you. However, they may not be up-to-date with the 'vanilla' module (e.g., in implementing PPI).
