### ISSUE TITLE
DARTEL preprocessing error when all participants have different types of sessions.

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#393]
I have some subjects and specific sessions, but subjects either have a 1) memory localizer or 2) visual nback task

Both tasks have an n-back component to them, so I was interested in looking at some task related activity in this set of participants common between these two tasks.

```
subj_list = {'sub-10','sub-13','sub-14','sub-15','sub-23','sub-25','sub-26','sub-28'};
tasknames = {'memorylocalizer_run-01','memorylocalizer_run-02','visnback_run-01','visnback_run-02'};

for i = 1:size(tasknames,2)
    aap = aas_addsession(aap,tasknames{i}); 
end
```

I got an error for sub-23, (which is the first subject that doesn't have a memorylocalizer)

```
Error using load
Must be a text scalar.

Error in aamod_norm_write_dartel (line 98)
            xfm = load(xfmfile); xfm = xfm.xfm;

Error in aa_feval (line 15)
    [varargout{:}]=feval(funcname,varargin{:});

Error in aa_feval_withindices (line 4)
[aap,resp]=aa_feval(mfile_alias,aap,task,ci{:});

Error in aa_doprocessing_onetask (line 191)
            [aap,~]=aa_feval_withindices(mfile_alias,aap,task,indices);

Error in aaq_localsingle/runall (line 15)
                aa_doprocessing_onetask(obj.aap,job.task,job.k,job.indices);

Error in aa_doprocessing (line 361)
            taskqueue.runall(dontcloseexistingworkers, false);

Error in prep_dartel (line 47)
aa_doprocessing(aap); % This is where the analysis begins
```

```
K>> xfmfile

xfmfile =

  5×1 cell array

    {0×0 char}
    {0×0 char}
    {0×0 char}
    {0×0 char}
    {0×0 char}

```

**Comment by TamerGezici** [comment]
Also let me share these details:

```
K>> aap,aap.tasklist.currenttask

aap = 

  struct with fields:

    directory_conventions: [1×1 struct]
                  options: [1×1 struct]
             gui_controls: [1×1 struct]
              acq_details: [1×1 struct]
                 timeouts: [1×1 struct]
                   schema: [1×1 struct]
                 tasklist: [1×1 struct]
             tasksettings: [1×1 struct]
    aap_beforeuserchanges: [1×1 struct]
                      spm: [1×1 struct]
                 internal: [1×1 struct]
                      aap: [1×1 struct]


ans = 

  struct with fields:

          epiprefix: []
    extraparameters: [1×1 struct]
           settings: [1×1 struct]
       inputstreams: [1×1 struct]
      outputstreams: [1×1 struct]
               name: 'aamod_norm_write_meanepi_dartel_00001'
              index: 1
       modulenumber: 14
             domain: 'subject'
           modality: 'MRI'
```

and my task list:

```
<?xml version="1.0" encoding="utf-8"?>
<aap>
    <tasklist>
        <initialisation>
            <module><name>aamod_study_init</name></module>
        </initialisation>
        <main>
                        
            <!-- Structural -->
          
            <module><name>aamod_structuralfromnifti</name></module>
            <module><name>aamod_coreg_extended_1</name></module>
            <module><name>aamod_biascorrect_structural</name></module>
            <module><name>aamod_segment8_multichan</name></module>
            <module><name>aamod_dartel_createtemplate</name></module>
            <module><name>aamod_dartel_norm_write</name></module>
          
            <!-- Functional -->
          
            <module><name>aamod_epifromnifti</name></module>
            <module><name>aamod_tsdiffana</name></module>	
            
            <module><name>aamod_realign</name></module>
            <module><name>aamod_slicetiming</name></module>
            <module><name>aamod_tsdiffana</name></module>
            <module><name>aamod_coreg_extended_2_epi</name></module>
            
            <module><name>aamod_norm_write_dartel</name></module> 
            <module><name>aamod_norm_write_meanepi_dartel</name></module> 
        </main>
    </tasklist>
</aap>
```

**Comment by tiborauer** [comment]
How did you add the subjects/session? Did you follow https://github.com/automaticanalysis/automaticanalysis/blob/e1796d20a222ebdfc843b4ae79b8b299f4738ff8/aa_engine/aas_addsubject.m#L44?

**Comment by TamerGezici** [comment]
I believe so, yes.

Furthermore, as far as I remember, this error does not happen when I use a non-DARTEL pipeline. B

**Comment by tiborauer** [comment]
Can you please confirm by checking your master script and/or the aap structure?
Also, can you confirm that it is DARTEL-specific?

**Comment by TamerGezici** [comment]
It is DARTEL specific, because a USR that doesn't use this task list worked fine. The only difference between the DARTEL script and the regular script is the task list. 

```
K>> aap.acq_details.sessions.name

ans =

    'memorylocalizer_run-01'


ans =

    'memorylocalizer_run-02'


ans =

    'visnback_run-01'


ans =

    'visnback_run-02'

K>> aap.acq_details.subjects(1).seriesnumbers{1, 1}  

ans =

  1×4 cell array

    {1×1 struct}    {0×0 double}    {0×0 double}    {0×0 double}

K>> aap.acq_details.subjects(8).seriesnumbers  

ans =

  1×1 cell array

    {1×4 cell}

K>> aap.acq_details.subjects(8).seriesnumbers{1, 1}  

ans =

  1×4 cell array

    {1×1 struct}    {1×1 struct}    {0×0 double}    {0×0 double}

K>> aap.acq_details.subjects(7).seriesnumbers{1, 1}

ans =

  1×4 cell array

    {0×0 double}    {0×0 double}    {1×1 struct}    {1×1 struct}

K>> aap.acq_details.subjects(7).seriesnumbers{1, 1}{1, 3}  

ans = 

  struct with fields:

    fname: {1×338 cell}
      hdr: 'E:\patient_studies\raw_data\bids_ses\sub-26\ses-preop01\func\sub-26_ses-preop01_task-visnback_run-01_bold.json'

K>> 
```

**Comment by tiborauer** [comment]
> It is DARTEL specific, because a UMS that doesn't use this task list worked fine. The only difference between the DARTEL script and the regular script is the task list.

I suspect it is a dependency rather than a module-specific issue mainly because the task should not be triggered at all for a missing session.

I would check at https://github.com/automaticanalysis/automaticanalysis/blob/e1796d20a222ebdfc843b4ae79b8b299f4738ff8/aa_engine/aa_doprocessing.m#L279, whether/why the task is to be executed.

**Comment by TamerGezici** [comment]
> > It is DARTEL specific, because a UMS that doesn't use this task list worked fine. The only difference between the DARTEL script and the regular script is the task list.
> 
> I suspect it is a dependency rather than a module-specific issue mainly because the task should not be triggered at all for a missing session.
> 
> I would check at
> 
> https://github.com/automaticanalysis/automaticanalysis/blob/e1796d20a222ebdfc843b4ae79b8b299f4738ff8/aa_engine/aa_doprocessing.m#L279
> 
> , whether/why the task is to be executed.

I went up with dbup after the error until I was at the function, and looked at deps,

I am not sure if this was the right approach though. Because let me know if there is a specific stage of the code which I need to debug this part.

```
K>> deps

deps =

  8×1 cell array

    {1×2 cell}
    {1×2 cell}
    {1×2 cell}
    {1×2 cell}
    {1×2 cell}
    {1×2 cell}
    {1×2 cell}
    {1×2 cell}

K>> deps{1}

ans =

  1×2 cell array

    {'subject'}    {[1]}
```

**Comment by tiborauer** [comment]
I do not think offline debugging is efficient. You can send me your `aap` structure, and I try taking a look at it. I assume you use the latest version of the central aa.

**Comment by tiborauer** [comment]
# Dependency
I have looked at the dependency using the following code (taken from aa_doprocessing):
```matlab
k = find(strcmp({aap.tasklist.main.module.name},'aamod_norm_write_dartel'));
[~, stagename]=fileparts(aap.tasklist.main.module(k).name);
domain=aap.schema.tasksettings.(stagename)(index).ATTRIBUTE.domain;
aap=aas_setcurrenttask(aap,k);
deps=aas_dependencytree_allfromtrunk(aap,domain);

```
deps is the list of all data to be processed at the current stage. It is a 15x1 cell on the session level in contrast with the one you showed on GitHub (8x1 cell on the subject level), so I assume you stopped at a different module.
Anyway, this deps hold the following data as listed by the code:
```matlab
cellfun(@(d) d{2}, deps, 'UniformOutput',false)
ans =

  15×1 cell array

    {[1 1]}
    {[2 1]}
    {[2 2]}
    {[3 1]}
    {[3 2]}
    {[4 1]}
    {[4 2]}
    {[5 3]}
    {[5 4]}
    {[6 1]}
    {[6 2]}
    {[7 3]}
    {[7 4]}
    {[8 1]}
    {[8 2]}
```
It correctly shows that subject 5 (sub-23) as no session 1  and 2 (memorylocalizer_run-01 and memorylocalizer_run-02), which means that the dependency is correct.

 # XFM
Having looked at the code, and your error, the xfm-file (usually `dartel_templatetomni_xfm.mat` in subject- or session-level) cannot be found, generated by the `aamod_dartel_norm_write` in your tasklist.

**Comment by TamerGezici** [comment]
Both types of subjects seem to have the xfm-file, though:

The paths are present at the top side.

![image](https://github.com/automaticanalysis/automaticanalysis/assets/11014942/98523a24-0b99-4854-bfcd-0d4dbe719251)

![image](https://github.com/automaticanalysis/automaticanalysis/assets/11014942/dee9dae1-e6f0-49e7-a5ce-a9e6149d1ef5)

**Comment by tiborauer** [comment]
Is the `dartel_templatetomni_xfm` stream also present in `aamod_norm_write_dartel` for sub-23?

**Comment by TamerGezici** [comment]
![image](https://github.com/automaticanalysis/automaticanalysis/assets/11014942/bcc3d6a6-f583-463e-8ebb-860efcad7834)

![image](https://github.com/automaticanalysis/automaticanalysis/assets/11014942/b0dfbba6-1cb7-438e-b979-348a62ac0552)

**Comment by TamerGezici** [comment]
> ```matlab
> k = find(strcmp({aap.tasklist.main.module.name},'aamod_norm_write_dartel'));
> [~, stagename]=fileparts(aap.tasklist.main.module(k).name);
> domain=aap.schema.tasksettings.(stagename)(index).ATTRIBUTE.domain;
> aap=aas_setcurrenttask(aap,k);
> deps=aas_dependencytree_allfromtrunk(aap,domain);
> ```

There is nothing in those directories apart from these. 

Inside the the session directory, I find:



![image](https://github.com/automaticanalysis/automaticanalysis/assets/11014942/c84d2571-ac8c-4e41-965b-098f1112453e)

![image](https://github.com/automaticanalysis/automaticanalysis/assets/11014942/7a3f1162-6211-490c-ab0c-024ef3affe08)

**Comment by tiborauer** [comment]
Wait! I do not understand how the stages are done (EPI output and done file) if there was an error.

**Comment by TamerGezici** [comment]
> Wait! I do not understand how the stages are done (EPI output and done file) if there was an error.

Hahaha. Okay. I thought you were aware of this.

Before creating this issue I myself tried debugging it, that's why while creating the issue I wanted to emphasize that the error appears to be in (due to it ending here in run time)

`aamod_norm_write_dartel `

But actually happens DURING this module:

'aamod_norm_write_meanepi_dartel_00001'

**Comment by TamerGezici** [comment]
By the way, considering that I actually don't use `aamod_norm_write_meanepi_dartel_00001` for any analysis (as far as I remember) I could technically omit this module altogether. 

We can still try solving it of course.

**Comment by tiborauer** [comment]
The question remains regarding the XFM file (now in `aamod_norm_write_meanepi_dartel_00001`):
- Do you have the stream and the file in the module
- If yes, check why https://github.com/automaticanalysis/automaticanalysis/blob/e1796d20a222ebdfc843b4ae79b8b299f4738ff8/aa_modules/aamod_norm_write_dartel.m#L89 or https://github.com/automaticanalysis/automaticanalysis/blob/e1796d20a222ebdfc843b4ae79b8b299f4738ff8/aa_modules/aamod_norm_write_dartel.m#L94 cannot pick it.

**Comment by TamerGezici** [comment]
The file exists under for sub-10,

![image](https://github.com/automaticanalysis/automaticanalysis/assets/11014942/b80d4b6e-2fa6-4399-8d84-b2aee877b649)


But not for sub-23

![image](https://github.com/automaticanalysis/automaticanalysis/assets/11014942/d34022e7-f222-4dd8-8f6a-66efc54aa04a)


K>> aas_getpath_bydomain(aap,aap.tasklist.currenttask.domain,cell2mat(varargin))

ans =

    'E:\patient_studies\analysis\group\prep_dartel\aamod_norm_write_meanepi_dartel_00001\sub-23'

**Comment by TamerGezici** [comment]
Furthermore, it seems like down the line, the call here returns nothing:

https://github.com/automaticanalysis/automaticanalysis/blob/e1796d20a222ebdfc843b4ae79b8b299f4738ff8/aa_engine/aas_getfiles_bystream_multilevel.m#L26C19-L26C19

```
K>> img

img =

  0×0 empty char array

K>> md5

md5 =

  0×0 empty char array

K>> streamdesc

streamdesc =

  0×0 empty char array
```

**Comment by TamerGezici** [comment]
Inside the function, the workspace looks like this:

![image](https://github.com/automaticanalysis/automaticanalysis/assets/11014942/57408f77-3838-49bd-ba74-7e625c3077cb)

**Comment by tiborauer** [comment]
How was/is sub-13? Was the stream found or created for them?

**Comment by TamerGezici** [comment]
I understand that you are talking about this:

![image](https://github.com/automaticanalysis/automaticanalysis/assets/11014942/34dfaa0f-eeed-4106-a945-1a40a668de5e)

**Comment by tiborauer** [comment]
Yes. As you can see, the XFM file is (correctly) detected missing and generated at this stage for this subject, it means that https://github.com/automaticanalysis/automaticanalysis/blob/e1796d20a222ebdfc843b4ae79b8b299f4738ff8/aa_modules/aamod_norm_write_dartel.m#L85 was `false`.

The question is why it is `true` for sub-23.

**Comment by TamerGezici** [comment]
> Yes. As you can see, the XFM file is (correctly) detected missing and generated at this stage for this subject, it means that
> 
> https://github.com/automaticanalysis/automaticanalysis/blob/e1796d20a222ebdfc843b4ae79b8b299f4738ff8/aa_modules/aamod_norm_write_dartel.m#L85
> 
> was `false`.
> The question is why it is `true` for sub-23.

Since I did not need this specific module's outputs, I ignored the issue and carried on with my analysis. Since it is not a major issue anymore, we can close the issue. 

It may be worth checking if this issue would have any correspondence to reproa, otherwise I'd say it is not worth burying time into it.

Feel free to close the issue, if so.
