### ISSUE TITLE
BUG - aas_addcontrasts crashing when subjects have different number of sessions

### ISSUE THREAD

**Issue by jones-michael-s** [automaticanalysis/automaticanalysis#395]
Hello,

Ran into a problem adding contrasts when using a BIDS dataset having subjects with differing number of sessions. I can reproduce the error using only two subjects -- the first having two sessions and the second having four (footnote: I'm not sure "sessions" is the preferred terminology, but its the term I will use). Here's what I mean in terms of the BIDS data structure:

```
sub-01 / ses-01 / func / ...
sub-01 / ses-02 / func / ...
sub-02/ ses-01 / func / ...
sub-02 / ses-02 / func / ...
sub-02 / ses-03 / func / ...
sub-02 / ses-04 / func / ...
```

Note sub-01 has two sessions and sub-02 has four.  After I call `aas_processBIDS`, I try to add a contrast:

`aap = aas_addcontrast(aap, 'aamod_firstlevel_contrasts', '*', 'sameforallsessions', [1], 'HW','T');                
`

This crashes with:

```
Index exceeds array bounds.

Error in aas_get_series (line 26)
    seriesnum=series{outsess};

Error in aas_addcontrast (line 282)
            [~, mriser] = aas_get_series(aap,'functional',subj,sess);
```

If I modify the data so that sub-02 only has three sessions, or two, it appears to work properly (at least the design matrix and other diagnostic images look correct).

Further testing indicates there is nothing magic about 2 vs 4 sessions. As long as the number of sessions differ by more than one, the crash happens.

I've tracked down the problem to this block of code in:

https://github.com/automaticanalysis/automaticanalysis/blob/10b3425d2a99e294e5df1454df15b6a262d1028b/aa_engine/aas_get_series.m#L15-L23

The way this gets used is `aas_processBIDS` adds the maximum number of sessions across all subjects (4, in this example). Then, `aas_addcontrast` loops over the maximal number of sessions and calls `aas_get_series` as a means of determining whether the session exists for a given subject. (if the subject doesn't define the sesssion, `aas_addcontrast` doesn't add the contrast for that session for that subject). 

If the number of sessions is equal, or only differs by one the code works. If it differs by more then one, "outsess" is eventually set to a value that exceeds array bounds and crashes when used later on the series array.

Can someone help me understand what this block of code does? It seems to be generating some kind of adjustment based on a difference between `aap.acq_details.subjects.mriname` and `aap.acq_details.subjects.seriesnumbers` but I can't decypher it beyond that...

I do a `aap.acq_details.input.combinemultiple = true` in my script, but I don't see any other setting that might be relevant (I could be wrong).

Any thoughts?
Thanks.

**Comment by tiborauer** [comment]
I am afraid there is some confusion between BIDS and aa. 
- aa "session" corresponds to BIDS "run" (regardless of the task)
BIDS "session" corresponds to visits, which is not coded in aa. `aas_processBIDS` overcomes this in two ways, depending on `aap.acq_details.input.combinemultiple`.
  - If `True`, it collapses the (BIDS) session and (BIDS) runs and generates the (aa) session name by adding the (BIDS) session name as a suffix to the (BIDS) run name.
  If `False`, it treats (BIDS) sessions as separate subjects and generates a subject name by adding the (BIDS) session name as a suffix.

I hope it helps.

For further debugging:
Can you describe which `subj` and `sess` it crashes at? Can you perhaps also attach your `aap`?

**Comment by tiborauer** [comment]
`aas_get_series` gives you the visit/(BIDS) session number and the series specification. From aa's POV, if you have two visits with two and three runs, respectively, then 
- visit 1/ run 1 -> aa session 1
- visit 1/ run 2 -> aa session 2
- visit 2/ run 1 -> aa session 3
- visit 2/ run 2 -> aa session 4
- visit 2/ run 3 -> aa session 5

**Comment by jones-michael-s** [comment]
Ok, I've had a chance to follow up on this with a minimal script that reproduces the crash.

**Analysis-1:** sub-01 (3 "sessions"), sub-02 (2 "sessions")
**Result:** runs (subjects can be added in either order)

**Analysis-2:** sub-01 (3 "sessions"), sub-03 (7 "sessions")
**Results:** crashes (order in which subjects are added doesn't matter)

Here's design matrix and contrast summary for Analysis 1 / Subject 1

![DESIGN_MATRIX](https://github.com/automaticanalysis/automaticanalysis/assets/25826038/7a7bd46e-e1e4-4fc7-a003-faf78acc445d)
![diagnostic_aamod_firstlevel_contrasts](https://github.com/automaticanalysis/automaticanalysis/assets/25826038/36e93efd-a586-403d-8dfa-257893a93835)


Here's design matrix and contrast summary for Analysis 1  / Subject 2

![DESIGN_MATRIX](https://github.com/automaticanalysis/automaticanalysis/assets/25826038/8e79c508-62c0-4bc1-8506-02d78edf428c)

![diagnostic_aamod_firstlevel_contrasts](https://github.com/automaticanalysis/automaticanalysis/assets/25826038/a9aabffa-a2f9-4a4a-bd0a-a197e08dd620)

Here's tasklist and userscript:

```
clear all;
aa_ver5; 
aap = aarecipe('addcontrast_crash.xml');

% -------------------------------------------------------------------------
% setup
% -------------------------------------------------------------------------

aap.acq_details.root = '/path/to/root';
aap.directory_conventions.analysisid = 'RESULTS';
aap.directory_conventions.rawdatadir = '/path/to/BIDSdata';

aap.options.NIFTI4D = 1;
aap.acq_details.input.combinemultiple = true;

% -------------------------------------------------------------------------
% data selection
% -------------------------------------------------------------------------

% Testing 3 subjects:
%
%   sub-01 has 3 sessions
%   sub-02 has 7 sessions
%   sub-03 has 2 sessions

SID = { 'sub-01', 'sub-02' };     % crashes
% SID = { 'sub-02', 'sub-01' };     % crashes
% SID = { 'sub-01', 'sub-03' };     % works
% SID = { 'sub-03', 'sub-01' };     % works

aap = aas_processBIDS(aap,[],[],SID); 

% -------------------------------------------------------------------------
% contrast definition
% -------------------------------------------------------------------------

aap = aas_addcontrast(aap, 'aamod_firstlevel_contrasts_00001', '*', 'sameforallsessions', [1 0], 'AONLY','T');                
aap = aas_addcontrast(aap, 'aamod_firstlevel_contrasts_00001', '*', 'sameforallsessions', [0 1], 'AV','T');                

aa_doprocessing(aap);
```

```
<?xml version="1.0" encoding="utf-8"?>
<aap>
    <tasklist>
        <initialisation>	
            <module><name>aamod_study_init</name></module>
        </initialisation>
		
        <main>      
          
        <module><name>aamod_epifromnifti</name></module>     
        <module><name>aamod_firstlevel_model</name></module>
        <module><name>aamod_firstlevel_contrasts</name></module>        
        
        </main>
    </tasklist>
</aap>
```

Here's the aap struct for Analysis 1 (I can't attach the aap struct for Analysis 2 because aa crashes before an aap struct is generated).

[aap_parameters.mat.zip](https://github.com/automaticanalysis/automaticanalysis/files/14655243/aap_parameters.mat.zip)

Thanks for any help!
M

**Comment by tiborauer** [comment]
Thanks, Mike!

You can manually save the `aap` structure before `aas_addcontrast`.

**Comment by jones-michael-s** [comment]
> You can manually save the aap structure before aas_addcontrast.

D'oh! :-)

In my own defense, I wasn't sure it would contain useful information at such an early stage).

Anyway, here is aap with sub-01 and sub-02 (which generates the crash)

[aap_from_crash.mat.zip](https://github.com/automaticanalysis/automaticanalysis/files/14701973/aap_from_crash.mat.zip)

**Comment by jones-michael-s** [comment]
Thanks TIbor!

This indeed seems to have fixed the problem.

Would you like me to submit a PR with this?

**Comment by jones-michael-s** [comment]
I have submitted and merged a PR with this update.
