### ISSUE TITLE
Diagnostics

### ISSUE THREAD

**Issue by tiborauer** [automaticanalysis/automaticanalysis#61]
I have noticed that there is an inconsistency in placing diagnostics, which is bad, because some of them are ignored during the report generation. Some of them are in the subjects' folders, some of them are in the module's folder, and some of them are in a separate "diagnistics" folder. I personally prefer:
1. subjetc-level diagnostics going to the subjetcs' folders,
2. mudule-level summaries/statistics going to the corresponding module's folder
to keep results and diagnostics in the same place.

Another option could be using "diagnostics" folder both
1. in the subjetcs' folders (for the subjetc-level diags.) and
2. in the corresponding module's folder (for the summaries),
and puttign the diagnostics there.

**Comment by jpeelle** [comment]
Bumping this up for general discussion. We discussed:

- Being consistent across all modules about where we save diagnostic images, and how they are named
- Possibly expanding reporting to have different levels of granularity or detail, either as option in headers/aap, or by having a slightly more complicated html structure with multiple pages

The main thing is to be consistent and continue to improve the reporting (which we find very useful!).
